### ISSUE TITLE
Comments section doesn't work anymore

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#11]
A few days ago I went to check the comments of a video but suddenly it just doesn't show anymore, even the loading spinner doesn't. This could definitely be an innertube issue.

**Comment by YukisCoffee** [comment]
This is definitely an InnerTube issue. Specifically, they displaced the comment continuation's `itemSectionRenderer` and added before it another `itemSectionRenderer` that has a different markup.

The function currently used for selecting the comment section is hacky, it just selects the first `itemSectionRenderer` in the watch contents and doesn't bother checking if it's specifically for comment section markup.

Will fix ASAP.

**Comment by YukisCoffee** [comment]
Fixed in c3097bb4ad6299adf12ca6a5054b67d228f98a78.
