### ISSUE TITLE
Channel about page shows errors

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#111]
https://www.youtube.com/c/markiplier/about

Warning: preg_replace(): Empty regular expression in D:\xampp\htdocs\models\Channels\Channels4\MChannelAboutMetadata.php on line 70

**Comment by YukisCoffee** [comment]
Haha, sorry it took so long for us to get to this. It was a few quick typo fixes due to another change across the codebase.

Fixed in 8b989793de2e418098a345149aad8cf589acd095. Closing...
