### ISSUE TITLE
misc install guide typo

### ISSUE THREAD

**Issue by SpinThwomp** [Rehike/Rehike#114]
>Unlike Linux, you will have to manually install it manually.

read it aloud :\

**Comment by aubymori** [comment]
[hey you should check this out](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

**Comment by SpinThwomp** [comment]
ill keep it in mind for the future lmfao, you can close the issue
