### ISSUE TITLE
Add the ability to create community posts directly from your own Community tab

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#116]
In Polymer, you can create community posts directly from the Community tab, as shown here:
![image](https://user-images.githubusercontent.com/107463768/196069169-ddcd1b68-3f5c-41e0-8182-6df6e6a4db8b.png)
But, in Rehike, you just... can't.
![image](https://user-images.githubusercontent.com/107463768/196069229-edb5a6b8-cd83-4d5f-bd06-9072551ffc36.png)

**Comment by aubymori** [comment]
See #117
