### ISSUE TITLE
"date added" button is missing

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#118]
![image](https://user-images.githubusercontent.com/107463768/196078859-9d650fd1-e9d1-49a7-8aa6-f301fbe55fe8.png)
In previous versions, it was next to the "list/grid" menu. Now, it's gone.

**Comment by YukisCoffee** [comment]
YouTube themselves removed this from their API. We'll look into it, but no ETA.

**Comment by randomperson189** [comment]
The weird thing though is that I still have the option to sort by oldest for video channels
![image](https://user-images.githubusercontent.com/32617562/196170254-58c7762c-9b06-419b-bf72-ea5e39330baa.png)
![image](https://user-images.githubusercontent.com/32617562/196170330-b8f0facf-2b93-4113-b92f-d1ce09452ea4.png)

**Comment by YukisCoffee** [comment]
@randomperson189 YouTube changes roll out progressively to their different servers. So you may have the old behaviour for a while longer than other people or may get it instantly. In addition to this, they have an experiment system that complicates things even more - behaviour can be rolled out to simply a few users.

**Comment by randomperson189** [comment]
hmm, well I still think there could be a workaround by doing the continuations in reverse

**Comment by randomperson189** [comment]
It seems youtube added a new sort by popular option to polymer so I think it should be added to rehike

**Comment by Nightlinbit** [comment]
The new rich channels work a bit differently. Perhaps they'll also reintroduce sort by old, which would be very useful; though, seeing as the feature is not on newer mobile clients, it doesn't seem entirely likely that they will.

**Comment by Nightlinbit** [comment]
Might I add, it's interesting that you got a sort of hybrid response with this. You only lack the sort option itself, but actual users with a richGridRenderer here lack any view at all (only the channel header persists). I wonder why they'd remove sort from the old browse layout.

**Comment by Nightlinbit** [comment]
Finally, they did remove the ability to sort serverside it seems. At least, passing the URL parameters now does nothing at all. Worst case scenario seems unfortunately likely -- that we need to bruteforce all the way to the bottom and render from the bottom up.

**Comment by aubymori** [comment]
Fixed by 71748e26539c49c9557556995a23dda2ee634250.

Closing...
