### ISSUE TITLE
Clicking page numbers on the video search page does nothing

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#119]
![image](https://user-images.githubusercontent.com/32617562/196170611-dd113fc1-65c5-4944-b66d-45b4d65a0146.png)
I'm trying to click these buttons on the video search page but it doesn't do anything

**Comment by YukisCoffee** [comment]
Huh?? Lol

This is the oddest bug to result from hitchhiker's JS. Middle clicking the links should work tho.
