### ISSUE TITLE
YouTube Picker Doesn't Work

### ISSUE THREAD

**Issue by sydia1103** [Rehike/Rehike#12]
I have noticed that the YouTube Picker at the bottom doesn't work properly. Clicking on any of the options, it says loading for half a second and then disappears. According to Fiddler, this is because of picker_ajax, which doesn't exist. I assume you will implement this when you add more languages?

**Comment by YukisCoffee** [comment]
Will be implemented with i18n, no ETA.

**Comment by sydia1103** [comment]
i18n has now been implemented in the new-mvc branch. Will the picker also been implemented too?

**Comment by YukisCoffee** [comment]
The i18n update is preliminary. By i18n, I meant alongside the ability to use Rehike in another language itself.

Right now, this functionality does not exist, so we are focusing our efforts on other major parts.

**Comment by kawapure** [comment]
Finished in 8dc3444.
