### ISSUE TITLE
Homepage doesn't show videos after clearing browsing data

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#121]
So I cleared my browsing data including cookies, etc and went to youtube but what happened is the homepage didn't display any videos, the loading bar just disappears
![image](https://user-images.githubusercontent.com/32617562/196180487-06140f2a-e28c-4175-bc5e-2626bb6d4080.png)
![image](https://user-images.githubusercontent.com/32617562/196180659-169c9bd7-ab9b-46e0-bec8-d12aa1fd82e2.png)
This issue never happened before the recent WEB V2 shelves update

**Comment by YukisCoffee** [comment]
Known bug and cause. Will be fixed when VISITOR_INFO1_LIVE can be automatically populated by Rehike. Until then, you can manually populate the cookies by visiting [/?enable_polymer=1](//www.youtube.com/?enable_polymer=1).

**Comment by randomperson189** [comment]
Alright, I also wanted to mention that continuations don't work either just in case you didn't know

**Comment by YukisCoffee** [comment]
Browse continuations are always breaking in Rehike, so I guess that's to be expected lol

**Comment by aubymori** [comment]
Fixed by dd58d7d38e43dbb557a64b189c1a2e221ef7721a.

Closing...
