### ISSUE TITLE
Share button doesn't work when logged in (bug)

### ISSUE THREAD

**Issue by PANMARSAG14** [Rehike/Rehike#128]
When logged in, when you press Share button, it doesn't do anything, it just lights up.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/qF11yrH/chrome-0w-P2-RQabz0.png" alt="chrome-0w-P2-RQabz0" border="0"></a>

**Comment by aubymori** [comment]
Yeah, I have no idea what's going on here. It works completely fine for me. Maybe you're clicking it too early, before the JS has fully loaded, which isn't a Rehike problem, but rather a Hitchhiker problem.
![image](https://user-images.githubusercontent.com/44238627/196707273-e72324b1-11b8-43bd-8e1b-15d6f1db916b.png)

**Comment by PANMARSAG14** [comment]
Problem solved. It was some uBlock Origin filter messing things in Hitchhiker. I'm closing this issue.
