### ISSUE TITLE
No links for radio/playlist renderers

### ISSUE THREAD

**Issue by Objectful** [Rehike/Rehike#13]
`Notice:
 Undefined property: stdClass::$videoId in B:\xampp\htdocs\views\utils\AndroidW2w15Parser.php on line 101`

I'm assuming it's because it treats playlist renderers as normal videos and tried to get `videoId`, which doesn't exist.

**Comment by YukisCoffee** [comment]
Oof, I thought I did everything I could to avoid that too.

Fixed by d7a6ae90c544bd00265802cf9f7cd64bb7eb15d8.
