### ISSUE TITLE
Channel videos page doesn't work

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#131]
When I go to the videos page of a channel e.g. https://www.youtube.com/c/markiplier/videos nothing seems to show up
![image](https://user-images.githubusercontent.com/32617562/198534752-993c55a6-f943-4cab-94fc-e512a035ef0f.png)

**Comment by randomperson189** [comment]
![image](https://user-images.githubusercontent.com/32617562/198597990-bc9757b2-31c7-435f-aafa-341118893399.png)
So I typed it in the console and got these errors

**Comment by randomperson189** [comment]
Do you know how I do that? I'm still not so good at javascript

**Comment by randomperson189** [comment]
So I ran this command `console.log(JSON.stringify(document.querySelector("ytd-browse").data,null,2))` and I got these results, is this correct?
[dump.txt](https://github.com/Rehike/Rehike/files/9888700/dump.txt)

**Comment by Nightlinbit** [comment]
This has a richGridRenderer, which Rehike doesn't currently know how to render. The response is correct, however Rehike will need some modification to convert these into hitchhiker renderers again.

**Comment by YukisCoffee** [comment]
Fixed by 9812834e82d02d2319b2235f7fd1ff4d0d6ecb2b.

Closing...
