### ISSUE TITLE
View Full Playlist Header is broken

### ISSUE THREAD

**Issue by Minebunny99** [Rehike/Rehike#132]
title says all 
![image](https://user-images.githubusercontent.com/78270001/198587891-6baad21e-1e0e-4b06-914a-191f7353fc28.png)
and errors
![image](https://user-images.githubusercontent.com/78270001/198588039-168029fe-34be-4f4d-8ed3-50039c650a68.png)

**Comment by YukisCoffee** [comment]
Christ, fucking InnerTube moment.

I think now's going to be the least stable time, they're currently redesigning so we have to stay one step behind.

**Comment by Nightlinbit** [comment]
> Christ, fucking InnerTube moment.
> 
> I think now's going to be the least stable time, they're currently redesigning so we have to stay one step behind.

New layout is rolling out to more people now. For now, I recommend we bruteforce our way to a visitor cookie that has it, then patch these bugs.

**Comment by YukisCoffee** [comment]
Playlists still generally working fine for me as of 2022/11/02 21:18 JST. Christ these InnerTube updates are getting sporadic.

**Comment by aubymori** [comment]
Fixed by some commit.

Closing...
