### ISSUE TITLE
Description not showing

### ISSUE THREAD

**Issue by Objectful** [Rehike/Rehike#133]
It also happens in v3. 

![image](https://user-images.githubusercontent.com/73402079/199229908-8d93c70d-301c-4506-8bce-112d65523d5b.png)

It should have this description :

![image](https://user-images.githubusercontent.com/73402079/199230079-23fe6b7b-c947-426d-803b-e007b9eef55c.png)

**Comment by YukisCoffee** [comment]
I can't replicate this. If you can still get this on your end at all, could you please dump a watch InnerTube request for us?

**Comment by randomperson189** [comment]
I remember making an issue for this #87, it doesn't happen to me anymore but I'm glad to see that I wasn't the only one having this issue

**Comment by Objectful** [comment]
> 

This is the whole response:
https://raw.githubusercontent.com/Objectful/files/main/data.json
The description is in `"attributedDescriptionBodyText"`

**Comment by Objectful** [comment]
> I can't replicate this. If you can still get this on your end at all, could you please dump a watch InnerTube request for us?

This is the whole response:
https://raw.githubusercontent.com/Objectful/files/main/data.json
The description is in `"attributedDescriptionBodyText"`

**Comment by aubymori** [comment]
> > I can't replicate this. If you can still get this on your end at all, could you please dump a watch InnerTube request for us?
> 
> This is the whole response: https://raw.githubusercontent.com/Objectful/files/main/data.json The description is in `"attributedDescriptionBodyText"`

My reaction to that information:
![05775](https://user-images.githubusercontent.com/44238627/199600570-19fbefd1-445a-4dbc-84a9-e966a79eb149.gif)

Like holy shit this data format is so fucked. I genuinely want to fucking kill whoever thought this was a good idea.

**Comment by YukisCoffee** [comment]
> > I can't replicate this. If you can still get this on your end at all, could you please dump a watch InnerTube request for us?
> 
> This is the whole response: https://raw.githubusercontent.com/Objectful/files/main/data.json The description is in `"attributedDescriptionBodyText"`

Nevermind.

We're just going to.... Bye bye video descriptions! It was nice knowing you.

WHAT THE ABSOLUTE FUCK DID THEY DO WHAT DID THEY DO WHAT DID THEY DO WHAT DID THEY DO WHAT DID THEY DO WHAT DID THEY DO WHAT DID THEY DO WHAT DID THEY DO WHAT DID THEY DO WHAT DID THEY DO WHAT DID THEY DO WHAT DID THEY DO WHAT DID THEY DO WHYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

**Comment by aubymori** [comment]
Sorry, but this is absolutely impossible to debug without a visitor data that has this experiment. Won't fix until someone finds one and gives it. (P.S. Visitor data is the `VISITOR_INFO1_LIVE` cookie)

**Comment by Objectful** [comment]
> Sorry, but this is absolutely impossible to debug without a visitor data that has this experiment. Won't fix until someone finds one and gives it. (P.S. Visitor data is the `VISITOR_INFO1_LIVE` cookie)

This is my cookie `GjK6W7fAROY`. It only happens on my main account

**Comment by aubymori** [comment]
Oof sorry, I forgot to say but yesterday I discovered that my alt account has the experiment. Might be able to produce a fix with it.

**Comment by aubymori** [comment]
Somehow Rehike, like, nullifies this???? Like, in Polymer my alt has the `attributedDescription` (the new, awful one), but on Rehike the response has the normal `description` (based runs). I'm just gonna close this for now, and if this pops up again, reopen this.

**Comment by AshtyBoi** [comment]
it is happening again
also uh here's an error that pops up in the watch page i'm pretty sure it's related to this goofy ahh description problem but idk
`Warning:
Undefined property: stdClass::$subtitle
C:\xampp\htdocs\models\Watch\Watch8\MVideoSecondaryInfoRenderer.php:103`

**Comment by aubymori** [comment]
That particular error was just fixed, update Rehike and see if it still happens.

**Comment by AshtyBoi** [comment]
oh wait the description is still there on incognito 
and it was there even before i updated
so i guess my main account got the shitty experiment 💀

**Comment by aubymori** [comment]
New description is back. I'm going to fucking kill myself. Reopening.
