### ISSUE TITLE
Missing "Watch later" icon on videos

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#134]
![image](https://user-images.githubusercontent.com/107463768/199456962-59cc4da2-ce6f-45a9-9e05-ef9ea5c405f1.png)
Please fix this.

**Comment by YukisCoffee** [comment]
Hi, we've been updating the internal button code to reflect InnerTube better and this got caught up in the crossfire.

Fixed by 5f29fdd0c88877b75b04a855a07eaac7e6579c7c. Closing...
