### ISSUE TITLE
subscribe button only has one subscriber on owner videos

### ISSUE THREAD

**Issue by ineedseriousmentalhelp** [Rehike/Rehike#139]
![image](https://user-images.githubusercontent.com/109477049/199636579-400912ce-de12-4829-99bb-4c9bfca8a3cd.png)
heres the watchpage
![image](https://user-images.githubusercontent.com/109477049/199636618-cd01c291-cb9f-46d1-abb7-83042594e54a.png)
and here's channel

**Comment by YukisCoffee** [comment]
It actually shouldn't appear at all on your own uploads...

**Comment by aubymori** [comment]
> ![image](https://user-images.githubusercontent.com/109477049/199636579-400912ce-de12-4829-99bb-4c9bfca8a3cd.png) heres the watchpage ![image](https://user-images.githubusercontent.com/109477049/199636618-cd01c291-cb9f-46d1-abb7-83042594e54a.png) and here's channel

This is fixed by b068ceb2c6e28c1ae672f18208e89a8316aa4d63, closing...
