### ISSUE TITLE
All Channels have no Playlists

### ISSUE THREAD

**Issue by sydia1103** [Rehike/Rehike#14]
I went to check the playlists of a channel, but it said there were none in Rehike. In normal YouTube, I am sure that there are playlists. Going to the direct playlist link gives an error message. I am sure there was a commit that showed experimental channel playlists, but it seems that doesn't work anymore.

**Comment by YukisCoffee** [comment]
It's working on my end using the latest `master` commit: d7a6ae90c544bd00265802cf9f7cd64bb7eb15d8

I guess this is where we as the developers need to start introducing some form of version logging. More details would be appreciated, thanks!

![image](https://user-images.githubusercontent.com/99076687/169226551-e62f2677-6774-44bd-b0da-a439f17846d5.png)
![image](https://user-images.githubusercontent.com/99076687/169226746-b466042a-d4e4-40de-9c8f-b810094fdcf2.png)
![image](https://user-images.githubusercontent.com/99076687/169226841-52f7ca37-6721-4d5c-8121-cf40e949e2a7.png)
![image](https://user-images.githubusercontent.com/99076687/169227016-2d1ceff1-80b3-412c-95d3-858fb1d54e9c.png)

**Comment by sydia1103** [comment]
I am currently using the version from May 8, the one that fixed the homepage. It seems some channels have playlists, some don't. I know michael mjd has playlists though.  There are no errors displayed, but for some reason it doesn't work for some channels
![Uploading VirtualBox_Windows 7 Professional SP1_22_05_2022_08_34_10.png…]()
. 
![VirtualBox_Windows 7 Professional SP1_22_05_2022_08_30_07](https://user-images.githubusercontent.com/69560065/169697677-94c2a725-4f83-4dd8-8379-f4b7a9570706.png)

**Comment by YukisCoffee** [comment]
This has been solved by some commit on `new-mvc` (and consequently, `exp-signin-rework`).

The issue was a different type of renderer used if a channel had multiple shelves of playlists, which is now supported.

Closing...
