### ISSUE TITLE
Channel trailers are not showing at all

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#141]
![image](https://user-images.githubusercontent.com/107463768/200096937-cba45c85-7ba2-41a7-9e3c-a6538911bec7.png)
_**PLEASE**_ fix this.

**Comment by aubymori** [comment]
Aware of this bug. Have no idea what's causing it. I attempted to update the upsell video's SWF config to one from 2018, and now it just won't load, and I have no idea why. The SWF config seems valid.
