### ISSUE TITLE
If you browse in list mode in channels, then click load more, the next results load in grid.

### ISSUE THREAD

**Issue by TrulyJamal** [Rehike/Rehike#144]

**Comment by YukisCoffee** [comment]
This is a general browse error. It will be fixed as we rewrite the browse architecture.

**Comment by aubymori** [comment]
I don't think browsing in list mode on channels even works...

**Comment by aubymori** [comment]
Fixed in eaec046231407f530ebb82f6a1b4151f317c0b38. Closing.
