### ISSUE TITLE
Channel settings button doesn't show anymore

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#148]
When I'm on my channel or one of my own videos, the channel settings button is instead a disabled subscribe button. Not sure if this is intentional but I'm making an issue just in case
![image](https://user-images.githubusercontent.com/32617562/200212558-04c4c96b-077e-4bd5-a430-1795afa33686.png)

**Comment by aubymori** [comment]
Fixed by d55f0f70705b8dae5db659179eccd95945293ce1.

Closing...
