### ISSUE TITLE
"View as yourself/visitor" feature is missing

### ISSUE THREAD

**Issue by Yacine-Book** [Rehike/Rehike#156]
I remember this being a feature for channels in the old YouTube, where you could view your channel as yourself or a visitor, but it's sadly missing on Rehike, and here's what the feature looks like. Can you implement it to Rehike?
![Screenshot 2022-11-09 161954](https://user-images.githubusercontent.com/117831802/200840878-d3f47c50-15c2-4f8e-b35f-f852fd9b3718.png)

**Comment by aubymori** [comment]
This feature was for editing the different channel layouts and thus falls under Creator Studio. See [this section](https://github.com/Rehike/Rehike/wiki/Frequently-Asked-Questions#cant-you-do-creator-studio) of the FaQ page for more info.
