### ISSUE TITLE
The subscribe button is missing on channels

### ISSUE THREAD

**Issue by Yacine-Book** [Rehike/Rehike#158]
Here's what the subscribe button looks like. For some reason, it's missing on Rehike. Can you fix that?
![Screenshot 2022-11-09 163454](https://user-images.githubusercontent.com/117831802/200843904-2ee56b77-c953-455d-97b3-ff2e5fb7485b.png)

**Comment by YukisCoffee** [comment]
Could you provide a link to this channel? I can't seem to replicate this.

**Comment by Yacine-Book** [comment]
It was every channel that the button was missing from, but I'm pretty sure
it's fixed now
