### ISSUE TITLE
Subscribe button on other channels section doesn't work

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#159]
![image](https://user-images.githubusercontent.com/32617562/201039703-541cf639-66e0-4030-a8e6-e8ff688579be.png)
The subscribe button on the other channels section for example: https://www.youtube.com/c/pyrocynical doesn't seem to work, it also doesn't show as subscribed even though I'm subscribed to PyroLIVE.

This could be added to the Subscriptions Megathread #75

**Comment by YukisCoffee** [comment]
Fixed by ee28794fb9be6edc9dca7fd609f6387161836ebc.

Closing...
