### ISSUE TITLE
YouTube API requests for commenting, uploading, etc? (Idea)

### ISSUE THREAD

**Issue by dogemanwastaken** [Rehike/Rehike#16]
Is it plausible to have the YouTube API replace logging in?

**Comment by YukisCoffee** [comment]
Standard logging in will certainly be supported by Rehike. `exp-signin-rework` branch already has very limited, preliminary work for this. Along with this, there are some plans to test enable logging in on non-`www.youtube.com` domains down the road.

General interactions will all work as normal: including subscription, commenting, adding to playlists, and liking videos. At the moment, we are not concerned with the old Creator Studio interface as we have greater priorities with recreating the rest of the site, however, when we get there, we will experiment with attempting to functionally restore the old uploader interface as well.
