### ISSUE TITLE
Error page is incorrectly positioned

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#161]
![image](https://user-images.githubusercontent.com/32617562/201281165-ff880adf-1f95-482e-a6f1-674a5bc0a8a3.png)
For some reason the rehike error page shows in the corner now instead of in the center and it looks very weird and off

**Comment by aubymori** [comment]
This happens when the `www-error` stylesheet fails to load. Can't replicate this without manually removing it myself. Probably a cache issue.
