### ISSUE TITLE
Play all button doesn't work on playlist page

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#164]
When on a youtube playlist for example https://www.youtube.com/playlist?list=PL3tRBEVW0hiDL09lO0xjKEix84OY27xet the play all button doesn't do anything
![image](https://user-images.githubusercontent.com/32617562/201513510-91558bc1-c5cf-48b7-9544-2e908cdaa8c8.png)

**Comment by aubymori** [comment]
Fixed in 544a3d7609a5a7596f32be5b89b75476fc219c68. Closing.
