### ISSUE TITLE
Crash caused by irregular videos

### ISSUE THREAD

**Issue by YukisCoffee** [Rehike/Rehike#17]
Videos such as https://www.youtube.com/watch?v=7VD3lHKzMPs cause a fatal error, rather than rendering without metadata.

Additional checks must be implemented to ignore missing data, rather than crash on it.

**Comment by aubymori** [comment]
fixed in [new-mvc](https://github.com/Rehike/Rehike/tree/new-mvc)

![image](https://user-images.githubusercontent.com/44238627/176983686-338dcdb7-20c0-405f-b610-44a544281dc7.png)
