### ISSUE TITLE
Warning: Undefined property: stdClass::$subscribeButtonRenderer 

### ISSUE THREAD

**Issue by pbcairo** [Rehike/Rehike#170]
Warning: Undefined property: stdClass::$subscribeButtonRenderer on the channel page. The subscribe button is missing.

**Comment by Nightlinbit** [comment]
Could you clarify the circumstances under which to produce this problem, i.e. logged in/out?

**Comment by aubymori** [comment]
Don't see how this could be happening, since the channel header code has an explicit check to see if subscribe button exists or not. OP also has not given any useful details whatsoever. Closing.

**Comment by pbcairo** [comment]
fixed by using youtube.com instead of 127.0.0.1

**Comment by pbcairo** [comment]
sorry didn't know there were replies here because I forgot to change the notification setting from emails to web notifications
