### ISSUE TITLE
Creator Bar elements are incorrectly positioned

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#174]
The elements on the creator bar seem to be incorrectly positioned, it's also missing some icons
![image](https://user-images.githubusercontent.com/32617562/202240494-f653c93f-91dc-458f-b25a-c47bc1798bdb.png)

This is what it's supposed to look like
![wpt2ruc5pip21](https://user-images.githubusercontent.com/32617562/202240633-717527c9-da0a-436c-aecf-ccb5512abc24.png)

**Comment by aubymori** [comment]
I literally have no idea why this happens. This also happens with player CSS for me at random, and it seems to be a browser-side issue. You're out of luck.
