### ISSUE TITLE
Comments are not showing on most videos

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#176]
The comments section shows this. It never loads anything.
![image](https://user-images.githubusercontent.com/107463768/202328407-6ddfb251-2f6d-49bd-bd85-d70eb0e58332.png)
I think this is an issue with "teaserReplies" in the config, because I had this issue when it was turned on.

**Comment by aubymori** [comment]
Seems like this was an issue relating to the reply button update I did a while back.
