### ISSUE TITLE
Fatal error Uncaught Rehike\Exception\FileSystem\FsFileDoesNotExistException: Attempted to read nonexistent file "i18n/regex/en.json"

### ISSUE THREAD

**Issue by eliardneru** [Rehike/Rehike#180]
file exists, i runned it as administrator, took ownership of the htdocs folder, im not using a proxy, im using 127.0.0.1

![image](https://user-images.githubusercontent.com/74941858/202573662-8a2240da-d520-46c0-96be-117ba5226572.png)

**Comment by jkrosado** [comment]
same issue on macos 11.6.1
Apache/2.4.48
PHP 7.3.29-to-be-removed-in-future-macOS

**Comment by eliardneru** [comment]
i reinstalled my windows and got the same error
ah that motherfucker
what a tool

**Comment by aubymori** [comment]
PHP 7.4.33:
![image](https://user-images.githubusercontent.com/44238627/204104314-dff38666-68b6-46b7-acb7-c35d8c26a3ea.png)

PHP 8.1.10:
![image](https://user-images.githubusercontent.com/44238627/204104318-6ecfe265-f3d8-4257-ac0b-75e54c3c38e5.png)

Looks like this is an issue with PHP <8. Should we bump up the requirement or do you think we can fix this? @YukisCoffee

**Comment by eliardneru** [comment]
> PHP 7.4.33: ![image](https://user-images.githubusercontent.com/44238627/204104314-dff38666-68b6-46b7-acb7-c35d8c26a3ea.png)
> 
> PHP 8.1.10: ![image](https://user-images.githubusercontent.com/44238627/204104318-6ecfe265-f3d8-4257-ac0b-75e54c3c38e5.png)
> 
> Looks like this is an issue with PHP <8. Should we bump up the requirement or do you think we can fix this? @YukisCoffee

![image](https://user-images.githubusercontent.com/74941858/204110429-5c1c3b33-0e04-4e5d-84a1-06b126a1518d.png)
YOOOO, using php 8.1.12 here

**Comment by YukisCoffee** [comment]
Should be fixed now.
