### ISSUE TITLE
Country name doesn't show next to YouTube logo

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#187]
I noticed that the YouTube logo doesn't have your country's abbreviation name next to it.
![image](https://user-images.githubusercontent.com/32617562/202867647-91ba7a9a-407d-43d6-aee1-0196293f2ef7.png)

**Comment by aubymori** [comment]
will be implemented with i18n

**Comment by Nightlinbit** [comment]
Duplicate of #71
