### ISSUE TITLE
Channels on side of own channel page has subscribe text missing and OVER 48 ERRORS

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#188]
![image](https://user-images.githubusercontent.com/107463768/202881117-64d31b5d-2851-44bf-baec-30b1363fd9bf.png)
![image](https://user-images.githubusercontent.com/107463768/202881139-8c4628b0-58ac-47dc-940b-c3ae5c1f890a.png)
PLEASE fix this.

**Comment by randomperson189** [comment]
I remember making a similar issue a while back, it got fixed but now it's come back for some reason

**Comment by YukisCoffee** [comment]
Unfortunately, we can't fix it without additional details. But the error log here is generally useful. It seems like they have an experiment that restructures the data.

**Comment by aubymori** [comment]
![image](https://user-images.githubusercontent.com/44238627/218368550-8c66a9e9-b887-443c-a703-b6bd8cacff84.png)
Seems to work fine now.
