### ISSUE TITLE
Add Shorts and Live Tab like in the new layout

### ISSUE THREAD

**Issue by Pokechan** [Rehike/Rehike#189]
![image](https://user-images.githubusercontent.com/113075002/202914793-224e8e38-ef8f-40ef-bd0e-34e6d731437b.png)
![image](https://user-images.githubusercontent.com/113075002/202914807-1b932cc2-5777-4b86-b2ed-1a38a04e0e1d.png)

**Comment by aubymori** [comment]
Live tab is already accessible with subnav, but Shorts tab isn't. May be added, no ETA.
![image](https://user-images.githubusercontent.com/44238627/202914871-076d48f5-2a56-451a-a6ac-47c5799460a7.png)

**Comment by Pokechan** [comment]
![image](https://user-images.githubusercontent.com/113075002/202914978-027622eb-9d4e-4901-ab12-ba0be7baac0e.png)
weird.. It's empty every time i try to use it

**Comment by aubymori** [comment]
Could you click the button in the bottom right, click the error to expand it, and show what it says? It could help a lot

**Comment by Pokechan** [comment]
![image](https://user-images.githubusercontent.com/113075002/202915918-a1e63d5a-e4ed-4109-999e-58380b578adb.png)
no logs folder??

**Comment by aubymori** [comment]
1. i guess i can't help you sorry
2. holy shit logs folder that is the best idea ever

**Comment by randomperson189** [comment]
Make sure to make it toggleable since I don't want tons of logs in my file system

**Comment by aubymori** [comment]
Fixed in d2d4320284cbe7f795ba9125df6e85df2999b356. Closing.
