### ISSUE TITLE
Rehike pre-init error occured

### ISSUE THREAD

**Issue by ProTaxEvader** [Rehike/Rehike#190]
Rehike pre-init error occurred
Here are the details:

Uncaught Google\Protobuf\Internal\GPBDecodeException: Error occurred during parsing: Unexpected wire type. in C:\xampp\htdocs\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php:355 Stack trace: #0 C:\xampp\htdocs\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(512): Google\Protobuf\Internal\Message->skipField(Object(Google\Protobuf\Internal\CodedInputStream), 55) #1 C:\xampp\htdocs\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(811): Google\Protobuf\Internal\Message->parseFieldFromStream(55, Object(Google\Protobuf\Internal\CodedInputStream), NULL) #2 C:\xampp\htdocs\vendor\google\protobuf\src\Google\Protobuf\Internal\Message.php(775): Google\Protobuf\Internal\Message->parseFromStream(Object(Google\Protobuf\Internal\CodedInputStream)) #3 C:\xampp\htdocs\modules\Rehike\Util\WebV2Shelves.php(34): Google\Protobuf\Internal\Message->mergeFromString('\xC2\x04\xFA\x01GI69nJrKwPs...') #4 C:\xampp\htdocs\controllers\feed.php(81): Rehike\Util\WebV2Shelves::continuationToWeb('4qmFsgLqAhIPRkV...') #5 C:\xampp\htdocs\controllers\feed.php(43): Rehike\Controller\core\NirvanaController@anonymous::whatToWatch(Object(stdClass)) #6 C:\xampp\htdocs\controllers\core\HitchhikerController.php(114): Rehike\Controller\core\NirvanaController@anonymous->onGet(Object(stdClass), Object(Rehike\ControllerV2\RequestMetadata)) #7 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(51): Rehike\Controller\core\HitchhikerController->get(Object(stdClass), '', Object(Rehike\ControllerV2\RequestMetadata)) #8 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(73): Rehike\ControllerV2\GetControllerInstance->_cv2WrappedCallControllerMethod('get', Array) #9 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(209): Rehike\ControllerV2\GetControllerInstance->__call('get', Array) #10 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(156): Rehike\ControllerV2\Router::pointerHandler('feed', 'get') #11 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(26): Rehike\ControllerV2\Router::baseRequestMethod(Array, 'get') #12 C:\xampp\htdocs\router.php(46): Rehike\ControllerV2\Router::get(Array) #13 C:\xampp\htdocs\index.php(51): require('C:\\xampp\\htdocs...') #14 {main} thrown
Technical details

{
    "type": 1,
    "file": "C:\\xampp\\htdocs\\vendor\\google\\protobuf\\src\\Google\\Protobuf\\Internal\\Message.php",
    "line": 355,
    "message": "Uncaught Google\\Protobuf\\Internal\\GPBDecodeException: Error occurred during parsing: Unexpected wire type. in C:\\xampp\\htdocs\\vendor\\google\\protobuf\\src\\Google\\Protobuf\\Internal\\Message.php:355\nStack trace:\n#0 C:\\xampp\\htdocs\\vendor\\google\\protobuf\\src\\Google\\Protobuf\\Internal\\Message.php(512): Google\\Protobuf\\Internal\\Message->skipField(Object(Google\\Protobuf\\Internal\\CodedInputStream), 55)\n#1 C:\\xampp\\htdocs\\vendor\\google\\protobuf\\src\\Google\\Protobuf\\Internal\\Message.php(811): Google\\Protobuf\\Internal\\Message->parseFieldFromStream(55, Object(Google\\Protobuf\\Internal\\CodedInputStream), NULL)\n#2 C:\\xampp\\htdocs\\vendor\\google\\protobuf\\src\\Google\\Protobuf\\Internal\\Message.php(775): Google\\Protobuf\\Internal\\Message->parseFromStream(Object(Google\\Protobuf\\Internal\\CodedInputStream))\n#3 C:\\xampp\\htdocs\\modules\\Rehike\\Util\\WebV2Shelves.php(34): Google\\Protobuf\\Internal\\Message->mergeFromString('\\xC2\\x04\\xFA\\x01GI69nJrKwPs...')\n#4 C:\\xampp\\htdocs\\controllers\\feed.php(81): Rehike\\Util\\WebV2Shelves::continuationToWeb('4qmFsgLqAhIPRkV...')\n#5 C:\\xampp\\htdocs\\controllers\\feed.php(43): Rehike\\Controller\\core\\NirvanaController@anonymous::whatToWatch(Object(stdClass))\n#6 C:\\xampp\\htdocs\\controllers\\core\\HitchhikerController.php(114): Rehike\\Controller\\core\\NirvanaController@anonymous->onGet(Object(stdClass), Object(Rehike\\ControllerV2\\RequestMetadata))\n#7 C:\\xampp\\htdocs\\modules\\Rehike\\ControllerV2\\GetControllerInstance.php(51): Rehike\\Controller\\core\\HitchhikerController->get(Object(stdClass), '', Object(Rehike\\ControllerV2\\RequestMetadata))\n#8 C:\\xampp\\htdocs\\modules\\Rehike\\ControllerV2\\GetControllerInstance.php(73): Rehike\\ControllerV2\\GetControllerInstance->_cv2WrappedCallControllerMethod('get', Array)\n#9 C:\\xampp\\htdocs\\modules\\Rehike\\ControllerV2\\Router.php(209): Rehike\\ControllerV2\\GetControllerInstance->__call('get', Array)\n#10 C:\\xampp\\htdocs\\modules\\Rehike\\ControllerV2\\Router.php(156): Rehike\\ControllerV2\\Router::pointerHandler('feed', 'get')\n#11 C:\\xampp\\htdocs\\modules\\Rehike\\ControllerV2\\Router.php(26): Rehike\\ControllerV2\\Router::baseRequestMethod(Array, 'get')\n#12 C:\\xampp\\htdocs\\router.php(46): Rehike\\ControllerV2\\Router::get(Array)\n#13 C:\\xampp\\htdocs\\index.php(51): require('C:\\\\xampp\\\\htdocs...')\n#14 {main}\n  thrown",
    "messagePreview": "Fatal error: Uncaught Google\\Protobuf\\Internal\\GPBDecodeException: Error occurred durin..."
}

**Comment by ProTaxEvader** [comment]
any issues mentioned are part of the error im not intentionaly mentioning them.

**Comment by aubymori** [comment]
this has been fixed update rehike
