### ISSUE TITLE
live chat having wrong page

### ISSUE THREAD

**Issue by iamatsomeone** [Rehike/Rehike#194]
it should be https://www.youtube.com/live_chat?is_popout=1&v=[vidid] instead of https://www.youtube.com/live_chat?continuation=string for a more reliable live that

**Comment by aubymori** [comment]
1. It's not a popout.
2. There's nothing wrong with using continuation. It's the SimpleFunnel and get live chat code that's the issue.

**Comment by randomperson189** [comment]
I'd like to see live chat fixed soon because it would save me time having to go to polymer layout, and also it doesn't seem hard to fix
