### ISSUE TITLE
channel URL with handle doesn't work

### ISSUE THREAD

**Issue by pbcairo** [Rehike/Rehike#204]
https://youtube.com/@xxx

does not work and gives me 404 error. it worked a few days ago though. I just updated Rehike but it still doesn't work.

**Comment by pbcairo** [comment]
EDIT: some urls with handle work(like the link above), but some other handles doesn't work.

**Comment by aubymori** [comment]
can you find me one that doesn't work and post it here?

**Comment by pbcairo** [comment]
- https://www.youtube.com/@Realstory_MBN
- https://www.youtube.com/@ITSUB

**Comment by aubymori** [comment]
oh god these are some kind of evil redirects and the second one doesnt even work
