### ISSUE TITLE
Could an option to use older hitchhiker layouts be possible?

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#206]
I'm wondering if further down the line that an option to use earlier hitchhiker layouts from like 2013-early 2014 for example would be possible and if so, would there be any plans to do so.

**Comment by Nightlinbit** [comment]
This has never been in the plans for Rehike; it's too much maintanence for too little gain.

**Comment by aubymori** [comment]
It would be possible with a fork, and someone could do that, but we have no plans to do that within main Rehike.
