### ISSUE TITLE
Default banner doesn't work and shows errors

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#208]
Whenever I go to a channel that should have the default banner, it instead doesn't show up and gives this error
![image](https://user-images.githubusercontent.com/32617562/204446050-ad5fcfb5-99a7-45db-940a-62f600143acb.png)

**Comment by YukisCoffee** [comment]
Fixed by 6804d07fa55219cf34683a7d22cbd1c727592b87.

Closing...
