### ISSUE TITLE
I can't get the old layout to load

### ISSUE THREAD

**Issue by alpharetzy** [Rehike/Rehike#211]
I was trying to bring back the old layout with this, but no matter how many times I've done it correctly, it still shows this:
![Screenshot (975)](https://user-images.githubusercontent.com/112749084/205442236-42234dc9-aa18-4001-9a18-63b8942fc931.png)
Can someone help me, please?

**Comment by Felting** [comment]
Show fiddler settings.

**Comment by Objectful** [comment]
Do you have XAMPP opened? If  you do, type in localhost in the address bar and see if it loads. If it loads, your Fiddler settings are set up wrong and if it doesnt show up, you either don't have xampp opened or didnt paste the files into htdocs.

**Comment by alpharetzy** [comment]
I have XAMPP opened and the localhost loads

**Comment by aubymori** [comment]
Any more details?

**Comment by aubymori** [comment]
We're deprecating Fiddler soon with 0.7. Closing.
