### ISSUE TITLE
Bottom comment's reply area does not show

### ISSUE THREAD

**Issue by LemonadeSnake** [Rehike/Rehike#214]
Whenever you open a comment thread and click on the bottom reply button the text box and buttons do not show.

**Comment by aubymori** [comment]
????????

**Comment by LemonadeSnake** [comment]
let me show you i'll get OBS recording

**Comment by LemonadeSnake** [comment]
https://user-images.githubusercontent.com/78671572/205498599-f8c37bfd-ae2f-4d5c-a7d1-499ecf989c7d.mp4

**Comment by LemonadeSnake** [comment]
just realised this mostly happens when you open a reply in notifications, but it has sometimes happened other times

**Comment by aubymori** [comment]
hitchhiker bug
