### ISSUE TITLE
YouTube stops loading when AutoResponder rule is enabled in Fiddler

### ISSUE THREAD

**Issue by retrostalgia** [Rehike/Rehike#215]
Fiddler AutoResponder settings:
![image](https://user-images.githubusercontent.com/111193347/205519442-b6e94a2f-e2d6-4ff6-8c78-55f9ac4fb6fe.png)

YouTube (not Rehike btw, just redux):
![image](https://user-images.githubusercontent.com/111193347/205519508-19237c9f-c105-4c4e-8b7e-f89dd7f32426.png)

Any settings I should change or anything I did wrong (also lmk if theres any more settings you'd like to see)

**Comment by LemonadeSnake** [comment]
dont use redux with rehike or any other custom js like 7kt just my personal suggestion

**Comment by aubymori** [comment]
i can tell you're on firefox, you'll have to export the fiddler certificate to the desktop (Tools > Options > HTTPS > Actions > Export Root Certificate to Desktop) and then install it through the firefox certificate manager in `about:preferences`

**Comment by retrostalgia** [comment]
I'm not on firefox actually, I'm on brave. I assume that since it's chromium I just follow the steps for the chrome version of that process? I thought I already did it but I might have messed something up

**Comment by retrostalgia** [comment]
Speaking of which, I just redid the steps you told me to do, and I'm having the exact same problem.

**Comment by YukisCoffee** [comment]
Try another browser or try using Ctrl+F5 to reload the page without cache.

**Comment by aubymori** [comment]
We're deprecating Fiddler soon with 0.7. Closing.
