### ISSUE TITLE
Shorts thumbnails are stretched

### ISSUE THREAD

**Issue by aubymori** [Rehike/Rehike#22]
YouTube stores shorts thumbnails in an actual 9:16 ratio. Hitchhiker has not been made to handle this aspect ratio,

Appearance in Rehike:
![image](https://user-images.githubusercontent.com/44238627/176983992-d7a41f3a-3b4c-45a0-afae-fb056a350dff.png)

Appearance in Kevlar/Polymer:
![image](https://user-images.githubusercontent.com/44238627/176984019-6a5132d6-88b9-4ab5-a7e5-dfec0182f3b8.png)

How it *should* look in Rehike:
![image](https://user-images.githubusercontent.com/44238627/176984077-c3fa4499-7341-4720-bff1-261dd7877715.png)
(For this screenshot, I corrected the thumbnail width, and applied `width: 196px; display: inline-block;` to the parent `span.yt-thumb-simple`.

**Comment by YukisCoffee** [comment]
This can be fixed by dropping the `sqp` attribute from the thumbnail URL if the aspect ratio is not 16:9.

Or, in other words, using `hq720_2.jpg`/etc. (Or `hqdefault.jpg` if you want the author thumbnail instead of the automatic Shorts one).

**Comment by aubymori** [comment]
Finally.
