### ISSUE TITLE
Youtube's subtitles won't load

### ISSUE THREAD

**Issue by LucasHood1234** [Rehike/Rehike#220]
Everything is so far so good though i noticed that the subtitles in CC doesn't load anything at all. No matter which language i changed. Hope it can be fixed, regards.

**Comment by LucasHood1234** [comment]
Picture for reference: https://cdn.discordapp.com/attachments/803408054304636928/1050088295595507752/Untitled306.png

**Comment by randomperson189** [comment]
I've noticed this issue as well and I have found a workaround for the time being, if you turn off your proxy and then enable subtitles then they should load normally, then you can turn back on your proxy and it will work fine

**Comment by aubymori** [comment]
> Picture for reference: https://cdn.discordapp.com/attachments/803408054304636928/1050088295595507752/Untitled306.png

@LucasHood1234 p.s. you can embed images with the following syntax: `![alt text](url)`
