### ISSUE TITLE
Warning: Undefined property: stdClass::$branch                 

### ISSUE THREAD

**Issue by MultiResearcher** [Rehike/Rehike#225]
I'm on Linux Mint 21 and my PHP version is 8. Every time visit localhost everything loads as intended but I get 2 same errors.

Warning:
Undefined property: stdClass::$branch    
/opt/lampp/htdocs/models/Footer/MFooter.php:65

I assume this has to do with the footer.

**Comment by Nightlinbit** [comment]
Did you download via Git or through the download ZIP feature of GitHub? This is almost certainly referring to the version information displayed in the footer by default.

**Comment by MultiResearcher** [comment]
git clone

**Comment by Nightlinbit** [comment]
Intriguing. Rehike pulls information from the .git folder if it's available, so my guess is this is a Linux-specific difference that wasn't tested for.

For now, you can patch this by replacing line 65 of models/footer/MFooter.php with```php
            $i18n -> primaryVersion($rehikeVersion -> semanticVersion, $rehikeVersion -> branch ?? "unknown branch"),
```

**Comment by MultiResearcher** [comment]
Now there are 0 errors. Thanks!
