### ISSUE TITLE
[Documentation] Natively forwarding Rehike to www.youtube.com.

### ISSUE THREAD

**Issue by Nightlinbit** [Rehike/Rehike#226]
# A preamble

Historically, it has been necessary to install proxy software like Fiddler or mitmproxy in order to use Rehike on the www.youtube.com domain, and little development has been made to move away from that requirement for much of the project's life. Taniko proved it was possible to do it natively (via the hosts file) [in her testing frontend](//github.com/YukisCoffee/hitchhiker), but the approach wasn't implemented in Rehike until very recently.

This feature was finally implemented in secret in Rehike 0.5.714. The rationale for a stealthy implementation is a complicated setup process involving manual configuration of Apache and OpenSSL. Be warned, this is a more complicated setup process at the moment compared to Fiddler.

# What you'll need

You will need to download these self-signed certificates.

  - [Apache certificates](https://cdn.discordapp.com/attachments/1044381225114144780/1050932441264693278/apache_conf_ssl.zip)
  - [Browser certificate](https://cdn.discordapp.com/attachments/1044381225114144780/1050932441549918300/rehike_master_cert.pem)

## Apache certificates

This download contains a zipped folder with three subdirectories. You can extract them anywhere, but it's good to put them with your Apache install. My recommended destinations are:

  - `C:\xampp\apache\conf` (Windows); replace the existing files.
  - `/opt/lampp/etc` (Linux); replace the existing files.
  - `/Applications/XAMPP/xamppfiles/etc` (macOS with XAMPP); replace the existing files.

But any destination will work as long as Apache can read them.

## Browser certificate

This follows the same setup routine as a proxy certificate, so [follow the general Rehike installation instructions.](https://github.com/Rehike/Rehike/wiki/Installation#ssl-certificate-installation) Basically, just install the certificate as a trusted root **authority** in your browser.

Browsers generally respond instantly to certificate installations, however you may have to restart your browser after doing this.

On Windows, it's also recommended to install the certificate as an OS-wide one. To do this, open `certmgr.msc`, right click on "Trusted Root Certification Authorities", go to "All Tasks", and click "Import". In the selection prompt, you may need to click all files to use the PEM file.

# Setting up the Rehike server

Go to the following file:
 - `C:\xampp\apache\conf\extra\httpd-vhosts.conf` (Windows)
 - `/opt/lampp/etc/extra/httpd-vhosts.conf` (Linux)
 - `/Applications/XAMPP/xamppfiles/etc/extra/httpd-vhosts.conf` (macOS with XAMPP)

...and add the following definition to the end of it:
```xml
<VirtualHost 127.0.0.1:443>
   ServerName www.youtube.com
   DocumentRoot "C:/xampp/htdocs"
   SSLEngine on
   SSLCertificateFile "conf/ssl.crt/server.crt"
   SSLCertificateKeyFile "conf/ssl.key/server.key"
   <Directory "C:/xampp/htdocs">
      AllowOverride All
      Require all granted
   </Directory>
</VirtualHost>
```
Obviously, repoint file paths as needed. Linux users will probably have `/opt/lampp/htdocs` as their document root instead.

**After editing your hosts file, you must restart Apache for the changes to take place**. Open XAMPP Control Panel and click the stop button for Apache, and then click start after it shuts down.

# Setting up the native redirection

The final step is getting the operating system to redirect Rehike on its own.

Go to the following file:

  - `C:\Windows\System32\drivers\etc\hosts` (you must open notepad as administrator)
  - `/etc/hosts` (`sudo nano`, etc.)

This file is responsible for manually defining DNS resolutions, but you don't really need to know the technicalities. Just add the following line:
```
127.0.0.1 www.youtube.com
```
After doing so, you may have to clear DNS cache or restart your computer (this is the case on Windows versions prior to 7 and probably some Linux versions). 

# Success?

Following these steps, you should successfully load Rehike without the use of any proxy/middleware.

Right now, you're kinda stuck with Rehike until you comment out the line in the hosts file again. You can bypass Rehike for a single tab by appending the URL parameter `?enable_polymer=1` to it.

# Known limitations

Although it's advised to host Rehike on ports 80 and 443, some programs (particularly on Windows) hijack these ports for their own bullshit and will prevent Apache from starting. However, using a proxy allows you to change the Apache ports and forward YouTube to a non-standard port. This will not work with this approach using hosts file, since it just manages name to IP address resolution.

The simple solution is to stop using Skype, since it has no excuse to hijack :80 and :443 anyway.

# Problems?

I tried to write these instructions in the friendliest manner that came to me, however you can't always be perfect.

Recheck your steps - you probably forgot something. Here are some examples of issues:

## I get nothing - page completely fails to load

The most likely cause of YouTube not responding at all, as if the website doesn't exist, is Apache not running. Try starting Apache and trying again.

## YouTube loads for me, but I don't get Rehike

This may be an alternate symptom of any of the mistakes you could make. Verify that Apache is running, that SSL is set up properly, that the definition is in hosts file, that the OS isn't caching DNS resolves, and that the browser isn't loading from cache (Ctrl+F5).

To refresh your DNS cache, run the following command:

  - `ipconfig /flushdns` (Windows)
  - `sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder` (macOS)
  - Linux instructions are case-specific; look up instructions for your distribution and configuration.

## I get a certificate error in my browser

This is caused by an improper SSL configuration. Verify that the browser has the Rehike master certificate installed in your browser as an authority (it should be called "www.youtube.com" and be issued by "Taniko Yamamoto"), and that Apache is configured to use the corresponding SSL certificates.

## This breaks yt-dlp

Pass the `--no-check-certificates` argument. This is because yt-dlp has its own certificate validation process that ignores the OS-wide one.

**Comment by YukisCoffee** [comment]
Merged into the wiki. https://github.com/Rehike/Rehike/wiki/Installation

Closing...
