### ISSUE TITLE
Add toggleable option to show the video count in rehike settings

### ISSUE THREAD

**Issue by TrulyJamal** [Rehike/Rehike#231]
![Screenshot (84)](https://user-images.githubusercontent.com/109087381/209098220-aa7dc8c8-4ff5-47f5-bbb7-2f927c334c9e.png)

**Comment by YukisCoffee** [comment]
This is not in the plans for Rehike, which officially implements a Nirvana frontend; the version Rehike intends to emulate already lacked this feature.

I recommend you find an old userscript or extension that implements this feature instead.
