### ISSUE TITLE
Rehike Player doesnt play video

### ISSUE THREAD

**Issue by NetFly795** [Rehike/Rehike#233]
When I click (on any video) comments and the video do not load. There doesn't seem to be a way to use embed player or anything, so I don't know what to do...

**Comment by aubymori** [comment]
are you using rehike on youtube.com or localhost?

**Comment by YukisCoffee** [comment]
Sounds like you're using localhost. You can force the player to load using a CORS bypass extension, but comments aren't possible to get working on localhost.

The correct way to use Rehike is to forward `www.youtube.com` to it. Please see [the wiki's installation instructions](https://github.com/Rehike/Rehike/wiki/Installation) and/or #226 for details.

Keeping open for additional comment.
