### ISSUE TITLE
360* video support? 

### ISSUE THREAD

**Issue by TrulyJamal** [Rehike/Rehike#234]
I have seen that videos in 360 degree don't work as intended, is this a rehike issue?

**Comment by YukisCoffee** [comment]
Could you elaborate further? Send a example link?

**Comment by aubymori** [comment]
Not a Rehike issue. Rehike's player is completely non-custom, it uses the exact same player which Polymer uses, although the experiment flags are tweaked, which explains some of the differences. Anyways, it's not like there's some player initialization variable we're missing to get 360 video. See [this video](https://youtu.be/nv-ih5tKDzg).

Closing.
