### ISSUE TITLE
Videos with warning for "suicide or self-harm topics" don't show an option to proceed

### ISSUE THREAD

**Issue by carsuki** [Rehike/Rehike#238]
On videos that YouTube has placed a topic warning on, there usually should be a button to proceed to the video, but while using Rehike there isn't an option and as a result the video can't be played. 

Here is an example link to test: https://www.youtube.com/watch?v=qVPlWFKUBCI

<img width="850" alt="Screenshot 2023-01-11 at 11 43 02 AM" src="https://user-images.githubusercontent.com/35876384/211904057-fe105f45-a0d0-4a3d-80cb-503e639503f9.png">

**Comment by YukisCoffee** [comment]
Duplicate of #43.

Closing...
