### ISSUE TITLE
issue on Firefox (video unavailable error only shows for a split second and then this shows)

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#240]
![uhh](https://user-images.githubusercontent.com/107463768/213613752-dfc18fb5-e54c-423e-86e8-8e4401d63ff1.PNG)

**Comment by YukisCoffee** [comment]
Do you have age restrict bypass installed at all?

**Comment by AshtyBoi** [comment]
yes

**Comment by YukisCoffee** [comment]
Not a Rehike issue then. This is an issue with a fix for that extension that cannot be easily solved, and we don't intend to bother. Sorry.
