### ISSUE TITLE
The subscriber count reads "No" instead of "0" for channels that have no subscribers

### ISSUE THREAD

**Issue by syndiate** [Rehike/Rehike#251]
![image](https://user-images.githubusercontent.com/67703687/218610475-d9c41389-f054-4144-9bc8-81167f5a1710.png)

**Comment by aubymori** [comment]
Channel link?

**Comment by syndiate** [comment]
https://www.youtube.com/channel/UCZCIRnzS_FBqfi31JOPTKRg/

**Comment by aubymori** [comment]
Hmm, that's odd... it there's no count element at all for me. 
![image](https://user-images.githubusercontent.com/44238627/218611681-3229fb1d-79e1-4575-b54d-5fb043f4a424.png)

**Comment by syndiate** [comment]
Well the channel I provided is my own channel
![image](https://user-images.githubusercontent.com/67703687/218611749-54368389-3b1e-49a6-8e86-199507081621.png)

Also I get this

**Comment by aubymori** [comment]
I think you might have a shot at patching this yourself. The code for subscriber counts is in `modules/Rehike/Util/ExtractUtils.php` at the `isolateSubCnt` method. (Make sure to use i18n!)

**Comment by syndiate** [comment]
Should the count variable be initialized as zero instead of just an empty string?

**Comment by aubymori** [comment]
I guess, but also replace "No" (grab this part from an i18n string) with "0".

**Comment by syndiate** [comment]
![image](https://user-images.githubusercontent.com/67703687/218614785-65fd1179-29e7-489b-9384-ffaf8034b2bd.png)
![image](https://user-images.githubusercontent.com/67703687/218614811-4e341db7-9afd-4fd4-96f1-8d0f019cdf83.png)


It should look like this, correct?

**Comment by aubymori** [comment]
Yes, that's good.
