### ISSUE TITLE
Playlist By appears on empty creators & missing numbers on certain playlists.

### ISSUE THREAD

**Issue by tersiswilvin** [Rehike/Rehike#256]
### Rehike version

0.5

### Operating system

Windows NT 10.0.19045.2604 (Windows 10 Home)

### PHP version

8.2.0

### What's going on?

1.) When Show "by" before the author's name on video links is enabled any playlist (e.g My Mix) with no creator still shows 'by'.
2.) Certain playlists don't show any numbers on the left side of the thumbnail.
Example playlists /w both issues present :
https://www.youtube.com/watch?v=PIE5QtkxzvM&list=RDMM&start_radio=1&rv=GxBSyx85Kp8
https://www.youtube.com/watch?v=kVpv8-5XWOI&list=RDkVpv8-5XWOI&start_radio=1&rv=kVpv8-5XWOI#t=0
![image](https://user-images.githubusercontent.com/52929976/220508947-79f23de0-5307-47e9-a2a1-cc8657b07a89.png)
![image](https://user-images.githubusercontent.com/52929976/220512010-c8d9a645-740a-4f09-a66b-9a7c9d3883c9.png)

**Comment by aubymori** [comment]
Fixed in 4b86dac1d66bd94290b21603638e456cfe774362. Closing.
