### ISSUE TITLE
/ @handle (the slash shouldn't be there)

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#257]
### Rehike version

0.5

### Operating system

Windows 10 21H2

### PHP version

8.1.10.0

### What's going on?

![image](https://user-images.githubusercontent.com/107463768/221085660-5bc00b5b-b0c3-4196-8e68-cb83847de5d5.png)
I don't think that slash should be there.

**Comment by aubymori** [comment]
post video link

**Comment by AshtyBoi** [comment]
https://www.youtube.com/watch?v=HAyfIlrgWgY

**Comment by aubymori** [comment]
![image](https://user-images.githubusercontent.com/44238627/221085931-11f05e81-635b-4e71-8b7d-529bfb3f24ca.png)
????????????

**Comment by aubymori** [comment]
this isn't even the same video

**Comment by AshtyBoi** [comment]
https://www.youtube.com/watch?v=xwZOsmXS2Sw

**Comment by AshtyBoi** [comment]
here's the true link
i posted the wrong link 💀
