### ISSUE TITLE
Fix SimpleFunnel

### ISSUE THREAD

**Issue by aubymori** [Rehike/Rehike#266]
### Rehike version

0.7

### Operating system

Windows NT 10.0 build 17763 (Windows 10) AMD64

### PHP version

8.2.0

### What's going on?

When SimpleFunnel was changed over to use CoffeeRequest, it lost the functionality of returning the response, and now always directly outputs the response. This breaks live chat; it now uses dark theme and modern icons, as the response is directly outputted, meaning the `get_live_chat` controller can't do its modifications. 
![image](https://user-images.githubusercontent.com/44238627/223603604-7112c0af-91dd-4ca6-ba9f-becf1b0b82ad.png)

**Comment by YukisCoffee** [comment]
Yeah yeah I'll fix it tomorrow

**Comment by YukisCoffee** [comment]
Yeah I see why I did this, I just didn't want to rewrite the API to be asynchronous. Will fix tomorrow :3

**Comment by YukisCoffee** [comment]
Nevermind I am so tired but here it's fixed in latest commit
