### ISSUE TITLE
Roboto cyrillic

### ISSUE THREAD

**Issue by ten4dinosaur** [Rehike/Rehike#269]
### Rehike version

0.5

### Operating system

Microsoft Windows [Version 10.0.19044.2604]

### PHP version

8.2.0

### What's going on?

In current state roboto font doesn't work with cyrillic symbols. 
Quick fix: replace the fonts in the file /template/hitchhiker/core/roboto.twig to [Regular 400/Regular 400 Italic/Medium 500/Medium 500 Italic](https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;1,400;1,500&display=swap).
But I don't know if all fonts are required/present, so just issue, not a pull request

[Screenshot](https://imgur.com/a/UzIoAjM)

**Comment by aubymori** [comment]
Fixed in ad8ec32f2cffb41a91ffe76f20b85d8721ef6837. Closing.
