### ISSUE TITLE
I cant get rehike to work with firefox

### ISSUE THREAD

**Issue by Shrexyobunger** [Rehike/Rehike#271]
### Rehike version

0.5

### Operating system

WIndows 10

### PHP version

I dont know

### What's going on?

It keeps saying " Firefox detected a potential security threat and did not continue to www.youtube.com because this website requires a secure connection. "

**Comment by Shrexyobunger** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/121275982/226492393-cde0b27e-1716-47cc-aae3-47f26641ee1d.png)

**Comment by aubymori** [comment]
Install the certificate in Firefox.

**Comment by Shrexyobunger** [comment]
I did

**Comment by Shrexyobunger** [comment]
i got it to work

**Comment by SatinFoil** [comment]
> i got it to work

How did you get that to work? I can't find a fix.
