### ISSUE TITLE
I cant get rehike to work on linux because of this error

### ISSUE THREAD

**Issue by Shrexyobunger** [Rehike/Rehike#272]
### Rehike version

0.5

### Operating system

Fedora 37

### PHP version

8.2.0

### What's going on?

It's giving me this error
Uncaught Rehike\ConfigManager\DumpFileException: fwrite(): Argument #1 ($stream) must be of type resource, bool given
Technical info

File: /opt/lampp/htdocs/modules/Rehike/ConfigManager/ConfigManager.php:34

Stack trace:
#0 /opt/lampp/htdocs/modules/Rehike/ConfigManager/ConfigManager.php(39): YukisCoffee\CoffeeException::from(Object(TypeError))
#1 /opt/lampp/htdocs/modules/Rehike/ConfigManager/ConfigManager.php(65): Rehike\ConfigManager\ConfigManager::dump('config.json', '{\n    "appearan...')
#2 /opt/lampp/htdocs/modules/Rehike/RehikeConfigManager.php(99): Rehike\ConfigManager\ConfigManager::dumpDefaultConfig()
#3 /opt/lampp/htdocs/index.php(49): Rehike\RehikeConfigManager::loadConfig()
#4 {main}

How do I fix this?

**Comment by Shrexyobunger** [comment]
![Screenshot from 2023-03-31 12-58-40](https://user-images.githubusercontent.com/121275982/229184245-dc33705d-f9b4-42e0-b93d-9075777817d5.png)

**Comment by YukisCoffee** [comment]
This occurs when there are no write permissions for the Rehike directory. Just `chmod 777 /opt/lampp/htdocs` and then it should work.

**Comment by Shrexyobunger** [comment]
Thank you so much. It fixed the problem and rehike appears to be working without issues!
