### ISSUE TITLE
Links replaced with shortcuts

### ISSUE THREAD

**Issue by coffeemccoffeeeeeee** [Rehike/Rehike#273]
### Rehike version

0.7

### Operating system

Windows 10 64 bit

### PHP version

PHP 8.0

### What's going on?

Description links replaced with shortcuts (just like the polymer layout)
![image](https://user-images.githubusercontent.com/111658911/229308001-8e6d791c-6c96-4d55-8219-fb365a9923eb.png)

**Comment by aubymori** [comment]
Video link?

**Comment by aubymori** [comment]
Fixed in c5db79754863f1481ae70bec65382b4b1b878c2e. Closed.
