### ISSUE TITLE
Playlist pages are completely broken

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#274]
### Rehike version

0.7

### Operating system

Windows 10 21H2

### PHP version

8.1.10.0

### What's going on?

Playlist pages do not work at all and show an error. Details from [the important videos playlist](https://www.youtube.com/playlist?list=PLFsQleAWXsj_4yDeebiIADdH5FMayBiJo):
Unhandled Promise(YukisCoffee\CoffeeRequest\Promise) in C:\xampp\htdocs\controllers\playlist.php:68
Stack trace:
#0 C:\xampp\htdocs\controllers\playlist.php(68): then(Object(Closure))
#1 C:\xampp\htdocs\controllers\core\HitchhikerController.php(117): onGet(Object(Rehike\YtApp), Object(Rehike\ControllerV2\RequestMetadata))
#2 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(51): get(Object(Rehike\YtApp), "", Object(Rehike\ControllerV2\RequestMetadata))
#3 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(73): _cv2WrappedCallControllerMethod("get", Array)
#4 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(209): __call("get", Array)
#5 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(156): pointerHandler("playlist", "get")
#6 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(26): baseRequestMethod(Array, "get")
#7 C:\xampp\htdocs\router.php(74): get(Array)
#8 C:\xampp\htdocs\modules\Rehike\Boot\Bootloader.php(44): require("C:\xampp\h...")
#9 C:\xampp\htdocs\modules\Rehike\Boot\Bootloader.php(22): postboot()
#10 C:\xampp\htdocs\index.php(61): startSession()
#11 {main}

Full trace:
#0 C:\xampp\htdocs\modules\YukisCoffee\CoffeeRequest\Promise.php(192): __construct()
#1 C:\xampp\htdocs\controllers\playlist.php(68): then(Object(Closure))
#2 C:\xampp\htdocs\controllers\core\HitchhikerController.php(117): onGet(Object(Rehike\YtApp), Object(Rehike\ControllerV2\RequestMetadata))
#3 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(51): get(Object(Rehike\YtApp), "", Object(Rehike\ControllerV2\RequestMetadata))
#4 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(73): _cv2WrappedCallControllerMethod("get", Array)
#5 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(209): __call("get", Array)
#6 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(156): pointerHandler("playlist", "get")
#7 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(26): baseRequestMethod(Array, "get")
#8 C:\xampp\htdocs\router.php(74): get(Array)
#9 C:\xampp\htdocs\modules\Rehike\Boot\Bootloader.php(44): require("C:\xampp\h...")
#10 C:\xampp\htdocs\modules\Rehike\Boot\Bootloader.php(22): postboot()
#11 C:\xampp\htdocs\index.php(61): startSession()
#12 {main}

**Comment by aubymori** [comment]
Fixed in 9a8c327158c34c8dca8dfadf5b730fdf42b7e13a. Closing.
