### ISSUE TITLE
Adding videos to "Watch Later" from the "Watch later" button on video thumbnails do not work

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#279]
### Rehike version

0.7

### Operating system

Windows 10 21H2

### PHP version

8.1.10.0

### What's going on?

It shows an error.
![image](https://user-images.githubusercontent.com/107463768/233493491-aca05c6e-4793-4f0f-8ffd-a2bb04e66d50.png)
According to Inspect's console, it returns with a 400 (Bad Request) error.

**Comment by YukisCoffee** [comment]
Can't reproduce.
