### ISSUE TITLE
Improving documentation for macOS installation

### ISSUE THREAD

**Issue by carsuki** [Rehike/Rehike#280]
_To clarify up front, this is more of an offer than a request, and just involves the Rehike wiki._

---

In my experience, getting Rehike to actually work on macOS ended up taking a lot of trial and error. Most of the problems I dealt with weren't covered in the installation guide (which, unsurprisingly, mainly focusses on Windows). My concern is that there are some noticeable holes in the info in cases when things differ between the platforms. Even Apache and XAMPP have a couple Mac-specific quirks that should probably be highlighted for easier troubleshooting.

For a proper example, the section about browser certificates only recommends installing certs system wide on Windows. But Safari and other WebKit browsers on macOS don't have any built in certificate management. For them to use Rehike at all, you need to install the certificates system wide through the Keychain Access system app. But this is honestly a simpler solution for anyone, regardless of the browser. Ideally it should just be recommended across the board for macOS, with browser specific config being a fallback.

**I assume the developers primarily use Windows and this isn't me complaining about that.** I'd be happy to contribute to improving the Mac documentation in any way that works for the project and maintainers. If there's interest for it, I could even write/help write an entire dedicated guide for setting Rehike up on macOS. (If that happens, splitting the manual installation section into Windows and Linux/Mac at that point might be preferable for organisation and readability.)

My original idea was to just fork the wiki and start a pull request with some suggested revisions to the macOS areas. But apparently Github doesn't allow forking wikis. So if there's an alternate way I can help, let me know.

I also totally understand if this just isn't a concern at this stage of the project. Please feel free to close the issue if that's the case. Thanks either way :)

**Comment by YukisCoffee** [comment]
Oof, we aren't sure about how to merge things either, but previous documentation updates have just posted their contents as issue comment bodies which we could tend merge into the wikis ourselves. And yeah, the installation instructions needs some sorting out in general.

We definitely appreciate the help with macOS support, especially since none of us on the development team have regular access to the operating system.

**Comment by carsuki** [comment]
Didn't expect such a quick reply lol, appreciate it. I'll probably put everything in a gist instead of a comment, just so this issue isn't a pain in the ass to scroll through. As for formatting, I'm thinking I'll just write all my additions for each applicable section in the same order as the current wiki without including any existing stuff. Then from there you guys can pick what you want to use and where/how you'll integrate it into the guide.

**Comment by YukisCoffee** [comment]
Sounds good to me!

**Comment by carsuki** [comment]
[Here](https://gist.github.com/carsuki/cc2f460529143f01f18beec6d908d6c8) is what I whipped up. Wrote it all on no sleep so there are probably a few minor grammatical/terminology errors, but hopefully some of the info is useful overall.

**Comment by YukisCoffee** [comment]
Thank you so much for this! We will make something out of it... eventually lol.

I see you mentioned that it works on Apple Silicon/ARM, have you tested this? We don't have access to any ARM machines for testing, much less Macs, and we have assumed x86-64 usage in the past. Although I guess it should work just fine as long as the dependencies all support it.

**Comment by carsuki** [comment]
Yeah I have, my main Mac is an M1 MacBook Air. It's the only Mac I've tested Rehike on but the Intel experience/install process shouldn't be any different. Didn't experience any problems with compatibility either. Whenever Apple inevitably cuts support for Rosetta 2, I'm guessing XAMPP probably still won't be updated for arm64, which could be a minor issue? Probably mostly just in user friendliness since iirc brew and MacPorts both have arm64 binaries for Apache and PHP.

**Comment by YukisCoffee** [comment]
I just decided to link to the gist and keep the official instructions mostly as they are. Unfortunately, GitHub's wiki feature is pretty awful and I don't want it getting even more cluttered than it already is.

https://github.com/Rehike/Rehike/wiki/Installation
