### ISSUE TITLE
(FIXED) Rehike not working on Waterfox/Firefox

### ISSUE THREAD

**Issue by SatinFoil** [Rehike/Rehike#282]
### Rehike version

0.5

### Operating system

Windows 10 21H2

### PHP version

I'm not sure, I am having trouble checking

### What's going on?

Rehike works on Edge perfectly, but on Waterfox (browser based off of Firefox) it just loads the modern YouTube site. On Firefox, it just gives an error when loading it (Error: Proxy server refuses to connect

An error occurred while connecting to www.youtube.com.
Please check if the proxy settings are correct
Please contact your network administrator to make sure that the proxy server is working). I am using the host file and the apache server is started. I have also installed both apache and browser certificates, restarted my PC, and cleared DNS cache (both by pressing ctrl+f5 and ipconfig /flushdns).

**Comment by GabrielMiceli** [comment]
Here's what you can try to do:

1.
    - Go to about:preferences
    - Scroll all the way down to Network Settings, and click the "Settings…" button
    - Choose the "No proxy" radio at the top, and click OK
    - Try again.
2.
    - Go to about:config
    - Click the "Accept the Risk and Continue" button
    - Search for "network.trr.builtin-excluded-domains"
    - Add "youtube.com,www.youtube.com" to the list (separating an already existing entry, if any, with a comma).
    This second solution is what worked for me.

**Comment by SatinFoil** [comment]
> Here's what you can try to do:
> 
> 1. * Go to about:preferences
>    * Scroll all the way down to Network Settings, and click the "Settings…" button
>    * Choose the "No proxy" radio at the top, and click OK
>    * Try again.
> 2. * Go to about:config
>    * Click the "Accept the Risk and Continue" button
>    * Search for "network.trr.builtin-excluded-domains"
>    * Add "youtube.com,www.youtube.com" to the list (separating an already existing entry, if any, with a comma).
>      This second solution is what worked for me.

Thank you, it worked! The second option also was the one that worked for me!
