### ISSUE TITLE
0.7 Homepage doesn't work on IE11, shows errors

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#283]
### Rehike version

0.7

### Operating system

Windows 10

### PHP version

8.2.0

### What's going on?

Whenever I try to go to youtube.com on Internet Explorer 11, it doesn't work and gives me an error. Other youtube pages work fine however
![image](https://user-images.githubusercontent.com/32617562/234481694-23992794-087a-4ff5-8b21-4d7b8f03b38a.png)

**Comment by aubymori** [comment]
Fixed in 0389e773e0e1dbf46d93c5df92988dd3b198e705.

Closing.
