### ISSUE TITLE
Some all comments pages redirect me to youtube.com/oops

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#284]
### Rehike version

0.7

### Operating system

Windows 10

### PHP version

8.2.0

### What's going on?

Certain all comments pages such as https://www.youtube.com/all_comments?v=zvLTJFyYySA redirect me to https://www.youtube.com/oops
![image](https://user-images.githubusercontent.com/32617562/234482317-879d412b-7db0-40ad-baf8-418c96853fdb.png)

**Comment by YukisCoffee** [comment]
All comments was removed, so this issue is now completely stale. Closing...
