### ISSUE TITLE
CORS Policy error

### ISSUE THREAD

**Issue by DrChic0** [Rehike/Rehike#285]
when i try to load a video it doesn't load and instead outputs this error into the console '_**Access to fetch at 'https://rr5---sn-nx5s7n7y.googlevideo.com/videoplayback?expire=1683351473&ei=UZNVZJ3KCpKgsfIP7ZmFuAY&id=o-ADcDP4VwzMDDRZrAeSntA-ofA75GTkigFGyPmo2LOOCk&itag=396&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=C6&mm=31%2C29&mn=sn-nx5s7n7y%2Csn-nx57ynss&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=2213750&spc=qEK7BxuVP47sWqUvy2J4qRdVPkxC-9OsVB7wHB018A&vprv=1&svpuc=1&mime=video%2Fmp4&ns=PqExgTRIphvl6IK2bYx_KEEN&gir=yes&clen=3148691&dur=174.480&lmt=1683289632783194&mt=1683329596&fvip=5&keepalive=yes&fexp=24007246&c=WEB&txp=5537434&n=6vALbvJWMbejCA&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgdmsQyO_grTdPS305oi08S8_Df6Ls9-KzMNGpBBD63ZQCIQDAFvUWSNK7KNdzw2K92zVB0LvEnimt-NXJJZJN1CIMVg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANd-RTwny4_y_dYb8qQhM4IdixUz8P_k4a2IzevCQhsAAiB2G4GwmSX3xBwlC9JFcQlvuY_-K2wMHCPJNYhDXT7hew%3D%3D&alr=yes&cpn=IXVvHjPVvADl2mHk&cver=2.20210623.00.00&range=0-1091&rn=12&rbuf=0&pot=MmQofACP2IyG8ihEhKC6KPDJfptdlmJAeYr3orc-mCNnC9uDTKj03qWTkF1Sv1oVISE0f5KCT4yDKiky4cbb2e5i2ijilcLkisCyhg0wNCson1ADbxYQg8cClI0L15eqm7cQYKKc' from origin 'http://localhost:8899' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**_'

How can I fix it?
![image](https://user-images.githubusercontent.com/62633768/236585249-0712f65e-f07c-4592-a716-cf5776064f9b.png)

**Comment by aubymori** [comment]
[Make sure you've installed Rehike correctly.](https://github.com/Rehike/Rehike/wiki/Installation)

**Comment by DrChic0** [comment]
> [Make sure you've installed Rehike correctly.](https://github.com/Rehike/Rehike/wiki/Installation)

I made sure to check if I installed it correctly, but from what I can tell it seems like I installed it correctly (the only steps I didn't do in my installation is change my httpd-vhosts.conf file to have www.youtube.com lead to the Rehike server)

**Comment by YukisCoffee** [comment]
You need to do that. Rehike will not work from localhost, because the browser will block these requests to YouTube's video server.

**Comment by DrChic0** [comment]
When I try to add the code to my httpd-vhosts.conf file and restart the server it still leads to the normal YT and not the server

**Comment by YukisCoffee** [comment]
You need to have the Rehike server hosted on port 443 in order for it to override it with hostsfile.

**Comment by YukisCoffee** [comment]
And you need to have it in hostsfile in the first place

**Comment by DrChic0** [comment]
i tried to rewrite my hosts file but it didnt work, i put in '127.0.0.1 www.youtube.com' in my hosts file but it made the www.youtube.com page not load anymore and i also am my server on port 443 and also tried hosting it on different ports but it does not work
![image](https://user-images.githubusercontent.com/62633768/236602597-bf41b741-38c4-4bf7-bd37-ac9da55aca85.png)
![image](https://user-images.githubusercontent.com/62633768/236602645-f48395e0-bb20-4627-8c3d-cf3fa430573b.png)
![image](https://user-images.githubusercontent.com/62633768/236602661-e2656577-8acb-4884-a5db-3b514fbe17e4.png)

**Comment by YukisCoffee** [comment]
You also need to install the Rehike certificate into your browser.

**Comment by DrChic0** [comment]
> You also need to install the Rehike certificate into your browser.

how do i do that?

**Comment by aubymori** [comment]
> > You also need to install the Rehike certificate into your browser.
> 
> how do i do that?

it says how in the installation guide

**Comment by DrChic0** [comment]
> > > You also need to install the Rehike certificate into your browser.
> > 
> > 
> > how do i do that?
> 
> it says how in the installation guide

thank you i was able to fix it

**Comment by Erizur** [comment]
maybe close this now? it has been fixed for a while i think
