### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by petimo59** [Rehike/Rehike#287]
### Describe the feature

I decided to start using Rehike in hopes of it making youtube load faster on my laptop. Recently, I found out that RSS feeds don't work when using Rehike. My suggestion is to implement RSS feeds as they work on the real youtube website.

**Comment by YukisCoffee** [comment]
Should be fixed by 3e2c8f2c5b62c5ac097b538beec792d2b6c1cd76. Closing...
