### ISSUE TITLE
You can't watch videos

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#288]
### Rehike version

0.7

### Operating system

Windows NT 10.0 build 19044 (Windows 10) AMD64 

### PHP version

8.1.10

### What's going on?

I tested this on many browsers. Chrome and Internet Explorer return a 500 error, while Firefox displays a blank page.
I believe this is a Rehike issue, as embedded videos still play.

**Comment by aubymori** [comment]
update
