### ISSUE TITLE
Load more browse_ajax not returning anything

### ISSUE THREAD

**Issue by Objectful** [Rehike/Rehike#29]
In the recent new-mvc and exp-signin-rework updates the Load more button on homepage stopped working. When you click on it, it's blank. 
![image](https://user-images.githubusercontent.com/73402079/178099838-31462b9c-2cef-4eaa-ba99-86da9f1d90d2.png)

**Comment by YukisCoffee** [comment]
Solved across both branches by e4d20fa2cd596f826803a566c15af4ac719d1977. Closing...
