### ISSUE TITLE
Uncaught Rehike\ConfigManager\DumpFileException when loading Rehike for the first time

### ISSUE THREAD

**Issue by asynkitty** [Rehike/Rehike#292]
### Rehike version

0.7

### Operating system

Darwin/XNU 21.6.0 (macOS 12.6.5 21G531 arm64)

### PHP version

Whatever the latest XAMPP for macOS (8.2.4) uses. I couldn't tell otherwise.

### What's going on?

Upon loading `http://localhost/index.php`, I get the error message `Uncaught Rehike\ConfigManager\DumpFileException: fwrite(): Argument #1 ($stream) must be of type resource, bool given`

File and stack trace:

```
File: /Applications/XAMPP/xamppfiles/htdocs/modules/Rehike/ConfigManager/ConfigManager.php:34

Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/modules/Rehike/ConfigManager/ConfigManager.php(39): YukisCoffee\CoffeeException::from(Object(TypeError))
#1 /Applications/XAMPP/xamppfiles/htdocs/modules/Rehike/ConfigManager/ConfigManager.php(65): Rehike\ConfigManager\ConfigManager::dump('config.json', '{\n    "appearan...')
#2 /Applications/XAMPP/xamppfiles/htdocs/modules/Rehike/RehikeConfigManager.php(99): Rehike\ConfigManager\ConfigManager::dumpDefaultConfig()
#3 /Applications/XAMPP/xamppfiles/htdocs/index.php(49): Rehike\RehikeConfigManager::loadConfig()
#4 {main}
```

Screenshots:

<img width="1765" alt="Screenshot 2023-05-25 at 11 58 17 PM" src="https://github.com/Rehike/Rehike/assets/88356560/607d6932-e623-48a3-a250-a7dceb3b57ac">

**Comment by aubymori** [comment]
Try running `chmod -R 777 /Applications/XAMPP/xamppfiles/htdocs` and see if it works.

**Comment by asynkitty** [comment]
> Try running `chmod -R 777 /Applications/XAMPP/xamppfiles/htdocs` and see if it works.

This worked great! Thank you, I think I can close the issue now.
