### ISSUE TITLE
a blacklist feature to hide and block videos [Optional]

### ISSUE THREAD

**Issue by UnderscoreAngel** [Rehike/Rehike#294]
### Describe the feature

Ever since i began using Rehike i have been aware that current/kevlar extensions can't be used with it due to the code being vastly different, i use an extension called "BlockTube" to block a certain type of videos because of personal issues, however there is no way of it working with Rehike as the extension's code relies on kevlar/current, in the past there used to be a similar extension for hitchhiker called "YouTube+" (https://web.archive.org/web/20171004163727/https://greasyfork.org/en/scripts/9932-youtube) but using that with Rehike, again doesn't work, i assume this is because of Rehike usage with the new/fixed API, again correct me if i'm wrong, again this isn't a "must-have" feature and it's something completely optional, but it will be useful to have one, even if it's a sepearated addon from Rehike itself

**Comment by UnderscoreAngel** [comment]
> you can try hide it with stylus using .yt-shelf-grid-item:has(a[href="/@ChannelHandleHere"]) {display:none;} Its doesn't work with firefox and old browsers

yes i've been aware of this method, the thing is, it only blocks certain videos and the channel, but it still allows the user to access such channel with a link or by doing an advanced search, it just hides it, it doesn't block it, i don't know if i'm explaining myself correctly, although the method works, it still doesn't hide the videos that well

**Comment by Felting** [comment]
it would also be nice if there was a list of hitchhiker addons and themes that work with rehike

**Comment by UnderscoreAngel** [comment]
> it would also be nice if there was a list of hitchhiker addons and themes that work with rehike

yeah it seems like a cool idea!

**Comment by syndiate** [comment]
OK, why is this an issue? This is something that should be done throughout some extension or something....it shouldn't be baked directly into Rehike
