### ISSUE TITLE
Subscriptions not displaying

### ISSUE THREAD

**Issue by NIQUETARACE911** [Rehike/Rehike#299]
### Rehike version

0.7

### Operating system

Windows 7 Ultimate

### PHP version

8.2.0

### What's going on?

Videos in the subscriptions tab seem to suddenly not display anymore, I haven't done anything & restarted everything, with no changes. Worked fine just this morning & the home page works as intended

**Comment by CrocodileCroco** [comment]
I'm having the same issue.

**Comment by YukisCoffee** [comment]
Fixed in c1174e9a68fedfe2f668d22ee9c85bfa7e7d3e7a.
