### ISSUE TITLE
InnerTube returns URLs for blurred thumbnails on age restricted videos

### ISSUE THREAD

**Issue by aubymori** [Rehike/Rehike#3]
![image](https://user-images.githubusercontent.com/44238627/157137994-4d6f62ce-89fb-4fde-be55-412df8cb7aef.png)

**Comment by aubymori** [comment]
just remove `sqp` param from url tbf it's not that big of a deal

**Comment by YukisCoffee** [comment]
Have you fixed this yet, or are we to remain this issue open longer?

**Comment by aubymori** [comment]
remains unfixed

**Comment by aubymori** [comment]
Okay. This issue has literally been open for almost a year at this point. I don't think anyone cares about this. Besides, it's kind of useful so that you know which videos require you to sign in to watch.
