### ISSUE TITLE
Merge dev-0.7-asynchike-main into master

### ISSUE THREAD

**Issue by ephemeralViolette** [Rehike/Rehike#303]
Because the most crucial features of Asynchike have finished their implementation and work quite well for all users on the Asynchike branch, the 0.5 version on the master branch should be replaced by Asynchike, where development shall continue as normal. It is stated in various areas in the Rehike repository that the project is in development anyway, and 0.5 currently lacks critical maintenance.

An update screen should be implemented before the migration in order to inform users who are still on PHP 7 to upgrade to PHP 8. PHP 8 does not have greater system requirements than PHP 7, so it should not be an issue to force this upgrade.

**Comment by aubymori** [comment]
`dev-0.7-asynchike-main` merged to `master` via 4129e8cc2953cb5d4e33d8883a37455dc2b9ad82. Closing.
