### ISSUE TITLE
Add /attribution_link support

### ISSUE THREAD

**Issue by Objectful** [Rehike/Rehike#304]
### Rehike version

0.7

### Operating system

Windows 11 21H2 build 22000.2057

### PHP version

8.1.6

### What's going on?

When opening new comment or new reply notifications from an email, it opens up `https://www.youtube.com/attribution_link?a=`
Rehike just 404s.

**Comment by YukisCoffee** [comment]
Fixed in 780dc8bdc3c3f419fe1d131dbd028dc39985f840.
