### ISSUE TITLE
Handles are shown in reply comments

### ISSUE THREAD

**Issue by blue-dragon-cairo** [Rehike/Rehike#305]
### Rehike version

0.5

### Operating system

Windows 7

### PHP version

not sure but i think the latest one

### What's going on?

Handles are shown in reply comments instead of channel names. Normal comments show the channel names correctly. Would like to see channel names in reply comments too.

![image](https://github.com/Rehike/Rehike/assets/76606635/4b532ce4-477a-45eb-a332-32cb04a6678d)

don't know why those YouTube developers made their stupid handles to be shown in comments, YouTube is just getting worse & worse since 2021)

**Comment by GabrielMiceli** [comment]
Holy crap; I was about to open this same issue. Thank you both for this lightning-fast patch! I had actually experimented with Rehike on another computer, and the June 20 permanent change to handles is what convinced me to make it my main, so I'm very glad that this was fixed.

**Comment by aubymori** [comment]
> Holy crap; I was about to open this same issue. Thank you both for this lightning-fast patch! I had actually experimented with Rehike on another computer, and the June 20 permanent change to handles is what convinced me to make it my main, so I'm very glad that this was fixed.
> 
> Edit: Mentions still use the handle format, though I'm not sure if that should be a separate issue.

Comment display names have been generally fixed in 0.7, so I'd refrain from opening an issue.
