### ISSUE TITLE
add mixes/playlists to the side bar of the watch page

### ISSUE THREAD

**Issue by DrChic0** [Rehike/Rehike#310]
### Describe the feature

i've attached a picture that shows what I mean, basically a few playlists show up on the sidebar that are related or a mix of random videos
![image](https://github.com/Rehike/Rehike/assets/62633768/7b0c2561-0881-4983-b05a-b2c41ca0a15e)

**Comment by aubymori** [comment]
These are already handled in Rehike. However, they are very uncommon unless you're on a music video, which is most likely why you weren't seeing them.

**Comment by DrChic0** [comment]
> These are already handled in Rehike. However, they are very uncommon unless you're on a music video, which is most likely why you weren't seeing them.

are they going to be shown more often in the future? or are they going to stay like how they are right now

**Comment by aubymori** [comment]
> > These are already handled in Rehike. However, they are very uncommon unless you're on a music video, which is most likely why you weren't seeing them.
> 
> are they going to be shown more often in the future? or are they going to stay like how they are right now

We are not YouTube, therefore we don't control the recommendations, so we don't know.

**Comment by DrChic0** [comment]
> > > These are already handled in Rehike. However, they are very uncommon unless you're on a music video, which is most likely why you weren't seeing them.
> > 
> > 
> > are they going to be shown more often in the future? or are they going to stay like how they are right now
> 
> We are not YouTube, therefore we don't control the recommendations, so we don't know.

oh i thought you guys could control that mb
