### ISSUE TITLE
Comment creation layout issues, extremely minor

### ISSUE THREAD

**Issue by DavidCGranger** [Rehike/Rehike#314]
### Rehike version

0.7

### Operating system

Windows NT 10.0 build 23486 (Windows 11) 

### PHP version

8.2.4

### What's going on?

When clicking to write a comment, the border around the input box has small layout issues in the CSS, really minor.
![grafik](https://github.com/Rehike/Rehike/assets/96387429/45a46b0b-1747-4889-b3f3-97735afa72b6)

**Comment by aubymori** [comment]
Hitchhiker issue.
