### ISSUE TITLE
Can't go to my channel when logged in

### ISSUE THREAD

**Issue by PanMarSagYT** [Rehike/Rehike#315]
### Rehike version

0.7

### Operating system

Windows NT 10.0 build 22621 (Windows 11) AMD64

### PHP version

8.2.4

### What's going on?

![chrome_o1otOQVUJn](https://github.com/Rehike/Rehike/assets/81510862/23fc639a-9605-4985-9c65-7f75d47e9ffd)

**Comment by Clasurol** [comment]
+1. I'm getting the same - I've also lost the ability to switch accounts; if I try either through Youtube or Youtube Studio, it will just default back to the same account.

**Comment by Felting** [comment]
0.7 has been merged into master, switch to master and see if it works

**Comment by aubymori** [comment]
Should be fixed.
