### ISSUE TITLE
Can you do Hitchhiker Account settings?

### ISSUE THREAD

**Issue by alpharetzy** [Rehike/Rehike#317]
### Describe the feature

I was watching an old YouTube Viewers video from 2018 on how to adjust video caption settings. And at some point in the video, when clicking the Settings button in the options menu, it got redirected to the Hitchhiker Settings page, which looks like this:

![Screenshot (1468)](https://github.com/Rehike/Rehike/assets/112749084/6c41f5ba-935e-4429-b041-6a6fdef76a66)

![Screenshot (1469)](https://github.com/Rehike/Rehike/assets/112749084/5395f3d3-012c-4c86-b6ba-eba676306ee2)

I hope this page will look like this in the future to match the theme of Rehike!

**Comment by aubymori** [comment]
We decided against doing account settings due to how complicated of a page it is. However, going to the account settings URL will take you to the Polymer version so you can still change your account settings.

**Comment by THErlego** [comment]
https://cdn.discordapp.com/attachments/336628093483614210/1143953732913070240/message.txt made a userstyle that goes with the extension stylus to make the settings page look somewhat like it does in the screenshots

**Comment by Techfromthepast123** [comment]
YouTube settings is no longer accessible due to it being replaced with "Rehike settings" how do I access regular YouTube settings now ?

**Comment by aubymori** [comment]
> YouTube settings is no longer accessible due to it being replaced with "Rehike settings" how do I access regular YouTube settings now ?

youtube.com/account
