### ISSUE TITLE
Accurate subscriber counter.

### ISSUE THREAD

**Issue by Matt-Manhack** [Rehike/Rehike#318]
I propose to make it as a separate function in the Rehike setup. So that the number of subscribers is shown exactly, and not in shortened form.

It was changed somewhere in the middle of 2017. To Abbreviated.

![изображение](https://github.com/Rehike/Rehike/assets/124304931/7745b29e-f266-4a22-9d59-2e1af45f45bb)

**Comment by aubymori** [comment]
This is impossible. You can only see your own unabbreviated subscriber count through Studio, and there is no known way to see anyone else's full subscriber count.
