### ISSUE TITLE
How the HECK do you actually log in?

### ISSUE THREAD

**Issue by lewdlicorice** [Rehike/Rehike#319]
### Rehike version

0.7

### Operating system

Windows 10 Pro 22H2 19045.3208

### PHP version

8.2.1

### What's going on?

So, Rehike works. Videos load. But there seems to be this REALLY weird authentication error. For reference, I am using Rehike with the hosts file proxy method, and I am accessing Rehike using www.youtube.com and not localhost (how would you even play videos like that?)

My subscriptions tab is missing, and I have to manually re-subscribe to channels that I have subscribed to before. When I attempt to "create a channel" even though I have a channel, the page freezes. The "Your channel" button or whatever it used to say back in the Hitchhiker days is missing, so I have to type in my YouTube channel manually to access it. I can subscribe to myself apparently?

The YouTube Studio/Creator Studio also seems to be missing, and clicking on "Upload video" redirects me to YouTube.com, so I have to manually type in the YouTube Studio URL to access it. If I upload a private video, nope, it says "This video is private" but I uploaded the video myself, so why can't I access the video I uploaded myself?

It might just be some weird authentication error that I can't seem to figure out, but I can't figure it out. How to I actually sign into YouTube?

**Comment by aubymori** [comment]
Are you signed in to multiple Google accounts? At the moment, Rehike doesn't support using multiple Google accounts.

**Comment by lewdlicorice** [comment]
> Are you signed in to multiple Google accounts? At the moment, Rehike doesn't support using multiple Google accounts.

I think this was the issue! Thank you :]
