### ISSUE TITLE
Rehike is not loading things properly

### ISSUE THREAD

**Issue by starterbeeee** [Rehike/Rehike#320]
### Rehike version

0.7

### Operating system

Windows NT 6.3 build 9600

### PHP version

8.2.4

### What's going on?

It worked properly up until a few days, now thumbnails, comments, and videos sometimes do load and other times dont load. (This happens on almost all pages.)
Things seem to work fine if i open Rehike in a private tab, i cleared my cookies and cache in rehike in non private mode but nothing changes.
Im using Firefox 115.0.3esr (64-bit)
Below is a couple of errors i found in apache's logs:
```[Thu Jul 20 12:46:03.817696 2023] [php:error] [pid 11560:tid 1644] [client 127.0.0.1:59816] PHP Fatal error:  Uncaught (in promise) YukisCoffee\\CoffeeRequest\\Exception\\PromiseAllException: Promise 1 rejected in Promise::all() call with reason "" in C:\\xampp\\htdocsrehike\\modules\\YukisCoffee\\CoffeeRequest\\Util\\PromiseAllBase.php:90\nStack trace:\n#0 C:\\xampp\\htdocsrehike\\modules\\YukisCoffee\\CoffeeRequest\\Util\\PromiseAllBase.php(130): YukisCoffee\\CoffeeRequest\\Util\\PromiseAllBase->handlePromiseRejection(Object(YukisCoffee\\CoffeeRequest\\Promise))\n#1 C:\\xampp\\htdocsrehike\\modules\\YukisCoffee\\CoffeeRequest\\Promise.php(356): YukisCoffee\\CoffeeRequest\\Util\\PromiseAllBase->YukisCoffee\\CoffeeRequest\\Util\\{closure}(Object(Rehike\\Exception\\Network\\InnertubeFailedRequestException))\n#2 C:\\xampp\\htdocsrehike\\modules\\YukisCoffee\\CoffeeRequest\\Promise.php(376): YukisCoffee\\CoffeeRequest\\Promise->reject(Object(Rehike\\Exception\\Network\\InnertubeFailedRequestException))\n#3 C:\\xampp\\htdocsrehike\\modules\\Rehike\\Network.php(126): YukisCoffee\\CoffeeRequest\\Promise->YukisCoffee\\CoffeeRequest\\{closure}(Object(Rehike\\Exception\\Network\\InnertubeFailedRequestException))\n#4 C:\\xampp\\htdocsrehike\\modules\\YukisCoffee\\CoffeeRequest\\Promise.php(274): Rehike\\Network::Rehike\\{closure}(Object(YukisCoffee\\CoffeeRequest\\Network\\Response))\n#5 C:\\xampp\\htdocsrehike\\modules\\YukisCoffee\\CoffeeRequest\\Util\\QueuedPromiseResolver.php(57): YukisCoffee\\CoffeeRequest\\Promise->resolve(Object(YukisCoffee\\CoffeeRequest\\Network\\Response))\n#6 C:\\xampp\\htdocsrehike\\modules\\YukisCoffee\\CoffeeRequest\\Loop.php(240): YukisCoffee\\CoffeeRequest\\Util\\QueuedPromiseResolver->finish()\n#7 C:\\xampp\\htdocsrehike\\modules\\YukisCoffee\\CoffeeRequest\\Loop.php(230): YukisCoffee\\CoffeeRequest\\Loop::finishQueuedPromises()\n#8 C:\\xampp\\htdocsrehike\\modules\\YukisCoffee\\CoffeeRequest\\Loop.php(84): YukisCoffee\\CoffeeRequest\\Loop::cleanup()\n#9 C:\\xampp\\htdocsrehike\\modules\\YukisCoffee\\CoffeeRequest\\CoffeeRequest.php(121): YukisCoffee\\CoffeeRequest\\Loop::run()\n#10 C:\\xampp\\htdocsrehike\\modules\\Rehike\\Network.php(214): YukisCoffee\\CoffeeRequest\\CoffeeRequest::run()\n#11 C:\\xampp\\htdocsrehike\\controllers\\core\\HitchhikerController.php(119): Rehike\\Network::run()\n#12 C:\\xampp\\htdocsrehike\\modules\\Rehike\\ControllerV2\\GetControllerInstance.php(50): Rehike\\Controller\\core\\HitchhikerController->get(Object(Rehike\\YtApp), '', Object(Rehike\\ControllerV2\\RequestMetadata))\n#13 C:\\xampp\\htdocsrehike\\modules\\Rehike\\ControllerV2\\GetControllerInstance.php(73): Rehike\\ControllerV2\\GetControllerInstance->_cv2WrappedCallControllerMethod('get', Array)\n#14 C:\\xampp\\htdocsrehike\\modules\\Rehike\\ControllerV2\\Router.php(209): Rehike\\ControllerV2\\GetControllerInstance->__call('get', Array)\n#15 C:\\xampp\\htdocsrehike\\modules\\Rehike\\ControllerV2\\Router.php(156): Rehike\\ControllerV2\\Router::pointerHandler('watch', 'get')\n#16 C:\\xampp\\htdocsrehike\\modules\\Rehike\\ControllerV2\\Router.php(26): Rehike\\ControllerV2\\Router::baseRequestMethod(Array, 'get')\n#17 C:\\xampp\\htdocsrehike\\router.php(76): Rehike\\ControllerV2\\Router::get(Array)\n#18 C:\\xampp\\htdocsrehike\\modules\\Rehike\\Boot\\Bootloader.php(44): require('C:\\\\xampp\\\\htdocs...')\n#19 C:\\xampp\\htdocsrehike\\modules\\Rehike\\Boot\\Bootloader.php(22): Rehike\\Boot\\Bootloader::postboot()\n#20 C:\\xampp\\htdocsrehike\\index.php(72): Rehike\\Boot\\Bootloader::startSession()\n#21 {main}\n  thrown in C:\\xampp\\htdocsrehike\\modules\\YukisCoffee\\CoffeeRequest\\Exception\\UncaughtPromiseException.php on line 38, referer: https://www.youtube.com/watch?v=ct74PKs4TcI&pp=ygUlZXNldCBub2QzMiBhbnRpdmlydXMgZGVzY2FyZ2FyIGdyYXRpcw%3D%3D```
But, as of recently the video im trying to watch and nothing loads dosent seem to make Rehike throw any error.

![imagen](https://github.com/Rehike/Rehike/assets/83183177/7ed92986-a3aa-486a-8788-4bbcaeb6afa3)

**Comment by YukisCoffee** [comment]
Haven't been able to replicate in months, so I will close this now.

Given how foreign resources from YouTube's static server (s.ytimg.com, unaffected by Rehike) seem to also not be loading, I will assume that you were having internet issues at the time. Unfortunately, Rehike just isn't very pretty about handling network connection errors, so it will just throw general network request failure exceptions, and error like such.
