### ISSUE TITLE
Fatal error on Firefox

### ISSUE THREAD

**Issue by Techfromthepast123** [Rehike/Rehike#322]
### Rehike version

0.7

### Operating system

Windows 11 22H2 (Build 22621)

### PHP version

8.2.4

### What's going on?

I get this Fatal error screen on Firefox while on Google Chrome it works fine.
Google Chrome (114):
![Capture d'écran 2023-07-27 172258](https://github.com/Rehike/Rehike/assets/112059671/b9367698-d802-451f-9717-cd43f50efe7d)
Firefox (Versions 115):
![Capture d'écran 2023-07-27 172241](https://github.com/Rehike/Rehike/assets/112059671/036062f4-fa3e-4002-aee9-0a3102911328)

**Comment by YukisCoffee** [comment]
This is a login cookie issue. Clear your cookies for YouTube and try again.
