### ISSUE TITLE
Community tab returns error(s)

### ISSUE THREAD

**Issue by tersiswilvin** [Rehike/Rehike#324]
### Rehike version

0.7

### Operating system

Windows 10 Home

### PHP version

8.2.4

### What's going on?

First Screenshot Error (No Post) :
```
Warning:
foreach() argument must be of type array|object, null given
C:\xampp\htdocs\models\Browse\InnertubeBrowseConverter.php:90
```
Second Screenshot Error (With Post) :
```
Warning:
Undefined property: stdClass::$backstagePostThreadRenderer
C:\xampp\htdocs\models\Channels\Channels4Model.php:355
Warning:
Attempt to read property "post" on null
C:\xampp\htdocs\models\Channels\Channels4Model.php:355
Warning:
Attempt to read property "backstagePostRenderer" on null
C:\xampp\htdocs\models\Channels\Channels4Model.php:355
```

![image](https://github.com/Rehike/Rehike/assets/52929976/5ab673a2-879e-4047-a9a9-5494b8355640)
![image](https://github.com/Rehike/Rehike/assets/52929976/06140316-8669-4476-b620-ff35d03739d5)

**Comment by ephemeralViolette** [comment]
I think this can be closed. As pointed out in #117, community in general is broken; no need to have issues for specific ways in which it is broken.
