### ISSUE TITLE
cannot switch between brand accounts

### ISSUE THREAD

**Issue by jkrosado** [Rehike/Rehike#326]
### Rehike version

0.7

### Operating system

macOS Monterey 12.5 (21G72)

### PHP version

8.2.4

### What's going on?

when i first set up rehike, i was signed into a brand account, and now i can't switch out. when i click a channel in the account switcher, the page refreshes without switching accounts. i'm running on XAMPP.

**Comment by bongur** [comment]
I found a workaround. You can change it on the rehike settings page. It might not work on the first try, try a couple times

**Comment by YukisCoffee** [comment]
> I found a workaround. You can change it on the rehike settings page. It might not work on the first try, try a couple times

What exactly do you mean?

**Comment by bongoje** [comment]
Bongur is my old account, logged in by mistake.

On youtube.com/rehike/config switching between brand accounts through the profile menu at the top right works, but it does not work on any other page. On those pages, when you click on another brand account, something starts loading but nothing ends up happening and the page doesn't change.

**Comment by bongoje** [comment]
I just updated from and older version (from around May) and it no longer works.

**Comment by YukisCoffee** [comment]
Should be fixed in 3ae4bc6.

Closing...
