### ISSUE TITLE
Youtube comments containing the @ handle in their usernames

### ISSUE THREAD

**Issue by zimmilarit** [Rehike/Rehike#328]
### Rehike version

0.7.961
### Operating system

Windows 10

### PHP version

8.2.4

### What's going on?

The youtube comments contain their @handles in the youtube comments listed in this image below
![qweasdaxcz](https://github.com/Rehike/Rehike/assets/118943950/a89fac37-4258-48d4-a4a5-1be15da02e0a)

**Comment by aubymori** [comment]
known.

**Comment by aubymori** [comment]
haven't seen this issue in a while, data api seems to be back to normal
