### ISSUE TITLE
YouTube shows blank homepage due to a YouTube change

### ISSUE THREAD

**Issue by Techfromthepast123** [Rehike/Rehike#330]
### Rehike version

0.7

### Operating system

Windows 11 22H2 (Build 22621)

### PHP version

8.2.4

### What's going on?

![Capture d'écran 2023-08-17 093757](https://github.com/Rehike/Rehike/assets/112059671/563655ea-b356-43f8-87d3-3c409271368c)
Youtube shows a blank homepage due to a YouTube update where it blocks the homepage if you have watch history turned off.
I dont want to turn on watch history because of privacy reasons.

Is there any way to fix this ?

**Comment by ephemeralViolette** [comment]
Just enable watch history or sign out.

**Comment by YukisCoffee** [comment]
Fixed in 99d6dade20087fa5253fed0077cd643ef86abf1d.

Go to https://www.youtube.com/rehike/config/experiments and toggle the "Disable authenticated home requests" option to force Rehike to treat the homepage as if you aren't logged in.
