### ISSUE TITLE
Theater mode doesn't show black bars on the left & right sides of the video

### ISSUE THREAD

**Issue by alpharetzy** [Rehike/Rehike#331]
### Rehike version

0.7

### Operating system

Windows NT 10.0 build 22631 (Windows 11) AMD64

### PHP version

8.2.4

### What's going on?

I don't usually watch videos in theater mode. But when watching widescreen videos, this mode can come in handy. But in Rehike however, the usual black bars aren't showing at all. Screenshot:

![Screenshot (1495)](https://github.com/Rehike/Rehike/assets/112749084/f705cf4c-4b38-4d58-a221-9eb407895d98)

**Comment by aubymori** [comment]
Doesn't occur for me. Most definitely one of your Stylus styles causing this.

**Comment by alpharetzy** [comment]
> Doesn't occur for me. Most definitely one of your Stylus styles causing this.
Even after turning off all of my scripts, turning off Tampermonkey, disabling all other styles except for YT Player Classicifer, it still happens

**Comment by aubymori** [comment]
Does the theater background show up at all if you resize the window, change your DPI, etc. etc.?

**Comment by alpharetzy** [comment]
![image](https://github.com/Rehike/Rehike/assets/112749084/a597b909-e8cd-47c4-ace7-4ae0e49d5025)

Finallt found the culprit that was causing this. I turned off this & now the black bars are now shown again!
