### ISSUE TITLE
Rehike does not skin "/playlist" pages, either loads them with the Polymer layout or returns a 404

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#34]
The title of this issue is self-explanatory. Let's say I'm using Rehike and I wanted to see my liked videos, but this is what I see:
![image](https://user-images.githubusercontent.com/107463768/178505141-64111a03-9b8d-4332-a58e-b3f1cdc13dab.png)
Because the "Liked videos" tab in the sidebar is a playlist, it has the same rules as other playlists that exist. In this case, it loads the 404 page. This needs to be fixed.
I am using the exp-signin-rework branch.

**Comment by aubymori** [comment]
![image](https://user-images.githubusercontent.com/44238627/178622756-386286de-b4a3-49b2-81b1-0860bfdec8d5.png)
Currently being worked on.
