### ISSUE TITLE
Subscriptions don't load on grid mode

### ISSUE THREAD

**Issue by Avolition777** [Rehike/Rehike#343]
### Rehike version

0.7

### Operating system

Windows 10

### PHP version

8.2.4

### What's going on?

![Screenshot_1](https://github.com/Rehike/Rehike/assets/143215610/b3857d8b-6589-421b-bf2a-56e88128cc4a)

**Comment by YukisCoffee** [comment]
I think this may be a duplicate of #299. In any case, closing because it's a very related topic.
