### ISSUE TITLE
SPF no longer working on navigation

### ISSUE THREAD

**Issue by Objectful** [Rehike/Rehike#346]
### Rehike version

0.7

### Operating system

Windows 11 21H2 build 22000.2057

### PHP version

8.1.6

### What's going on?

Pretty self explanatory. SPF doesn't work and throws &spfreload=10 on every url.

**Comment by aubymori** [comment]
can't reproduce

**Comment by syndiate** [comment]
Please describe the exact circumstances in detail.

**Comment by Felting** [comment]
> ### Rehike version
> 
> 0.7
> ### Operating system
> 
> Windows 11 21H2 build 22000.2057
> ### PHP version
> 
> 8.1.6
> ### What's going on?
> 
> Pretty self explanatory. SPF doesn't work and throws &spfreload=10 on every url.

Happening to me also. I fixed it by using [youtube plus](https://github.com/ParticleCore/Particle) and enabling disable spf.

**Comment by Objectful** [comment]
[message (10).txt](https://github.com/Rehike/Rehike/files/12640147/message.10.txt)
Here is my ytInitialData dump.

**Comment by YukisCoffee** [comment]
Not a YouTube issue, as detailed here. I will close this issue since the same problem is addressed in the linked one:

https://github.com/Rehike/Rehike/issues/347#issuecomment-1723163326
