### ISSUE TITLE
Remove "views" text setting doesn't work

### ISSUE THREAD

**Issue by VexorionReal** [Rehike/Rehike#350]
### Rehike version

0.8.0

### Operating system

Windows NT 10.0 build 19044 (Windows 10) AMD64

### PHP version

8.2.4

### What's going on?

I enabled removal of "views" text in Rehike configuration, but the text is not removed.
![chrome_uArgFBsAdL](https://github.com/Rehike/Rehike/assets/81510862/2ba3cacb-db98-4380-90b5-6bc0c35b89a9)
![chrome_v04A6i7Qxt](https://github.com/Rehike/Rehike/assets/81510862/56872150-8d12-4880-a035-0515ccbda05f)

**Comment by YukisCoffee** [comment]
Sorry I broke the config saving function.

Fixed in 647a50694ee3a8ed6d661cc48adc63b0b63c28c1
