### ISSUE TITLE
Swap "X views" and "X years ago" text in search results page.

### ISSUE THREAD

**Issue by VexorionReal** [Rehike/Rehike#352]
### Describe the feature

In the Hitchhiker search results page, "X views" and "X days/weeks/months/years ago" text were the other way around. Is it possible to add such a setting in Rehike configuration? Thank you.
![chrome_qzog7Dze1D](https://github.com/Rehike/Rehike/assets/81510862/fe8c35df-7b29-4fbc-9178-d66fc6b74fda)

**Comment by YukisCoffee** [comment]
I added this option in 2e67887a6ab45ac3660c7f22800285661fca464b. The default option is that it appears in the order that you demonstrate, and toggling the configuration option will revert it to view count before date like it was before in Rehike.
