### ISSUE TITLE
Age-restricted videos are not handled correctly on the exp-signin-rework branch and returns a fatal error or a "Video unavailable" error

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#36]
If you are wondering, I use XAMPP.
Scenario 1:
![image](https://user-images.githubusercontent.com/107463768/178988002-9bd9fee6-4745-43a6-bb17-02d0273f5bda.png)
Scenario 2:
![image](https://user-images.githubusercontent.com/107463768/178988110-6992b8c6-0490-4682-b18e-4c6ec09da54d.png)
Please fix this.

**Comment by aubymori** [comment]
Video links?

**Comment by AshtyBoi** [comment]
This happens with every single age-restricted video I try to play. Sometimes, it will load in the Polymer layout.

**Comment by aubymori** [comment]
Not sure what's going on with the first scenario, will check out.
However, for the second scenario (the page with the stack of TVs), could you please click "More information", copy everything there into a text file, and post it here?

**Comment by AshtyBoi** [comment]
Unfortunately, I am unable to reproduce the second scenario anymore, because it is instead replaced with the third scenario (Polymer layout)
Either way, age-restricted videos are broken.

**Comment by YukisCoffee** [comment]
Fixed by 709ab8e14017477631b8e4fb3ea4352ce0bcf1dc. Closing...
