### ISSUE TITLE
YouTube thumbnails and videos are not loading

### ISSUE THREAD

**Issue by nick2000s** [Rehike/Rehike#364]
### Rehike version

0.8.0

### Operating system

Windows 10 Home

### PHP version

8.2.4

### What's going on?

YouTube thumbnails and videos are not loading I didn't install anything I was just watching YouTube then the next video it stop working. I have tried resetting my pc, restarting both xampp and fiddler and update Rehike but nothing is working. 

![bandicam 2023-10-10 13-09-03-935](https://github.com/Rehike/Rehike/assets/147461805/733fad64-dd0b-4e5d-baa5-5f68434573f6)

**Comment by aubymori** [comment]
Not a Rehike issue. Thumbnails are obtained from `i.ytimg.com`, not `www.youtube.com`.
