### ISSUE TITLE
Discrepancy b/w Liking a Video and the Number

### ISSUE THREAD

**Issue by pixelrelay128** [Rehike/Rehike#366]
### Rehike version

0.7

### Operating system

Windows NT 10 22H2

### PHP version

8.2.0

### What's going on?

So what I mean by it is that when I'm liking a video, the Number of Likes goes up by 2 (while in reality it should be 1), and when I remove the like, it goes down by 2, and not by 1.

without liking:
![image](https://github.com/Rehike/Rehike/assets/147918855/913c4818-27fa-44ad-8f99-76d7f9ceaf94)

with liking, and a page refresh:
![image](https://github.com/Rehike/Rehike/assets/147918855/60a3a598-f38d-4dbe-b6bf-4f7b2b938b3e)

I think Rehike's just (accidentally) adding one because I've already liked it.

**Comment by pixelrelay128** [comment]
Found a similar issue with comments, for a comment with two likes (one being me), It shows up as 1, removing the like and refreshing the page still says the number of likes is 1.

**Comment by ephemeralViolette** [comment]
fixed in 72fb5069123fa42bc37beae815002f1c010ee5c1
