### ISSUE TITLE
Rehike is absolutely broken!!! HELP!!!

### ISSUE THREAD

**Issue by alpharetzy** [Rehike/Rehike#369]
### Rehike version

0.8.0

### Operating system

Windows NT 10.0 build 22635 (Windows 11) AMD64

### PHP version

8.2.4

### What's going on?

![2023-10-17](https://github.com/Rehike/Rehike/assets/112749084/78223840-0f64-4d53-b110-017b968e1ae3)

In the screenshot, the video player is just black, thumbnails won't load.

**Comment by alpharetzy** [comment]
When clicking something on Rehike it will just force reload the page to the new page, rather than smoothly transition to it with a red bar at the top.

**Comment by alpharetzy** [comment]
and settings will not apply even when clicking the Save changes button in Rehike settings

**Comment by ephemeralViolette** [comment]
It's uBlock Origin's fault.

https://github.com/Rehike/Rehike/wiki/I-can-connect-to-Rehike,-but-nothing-loads

**Comment by alpharetzy** [comment]
In that wiki it says that Rehike has a built-in adblocker since day one. How does it get undetected??

**Comment by aubymori** [comment]
> In that wiki it says that Rehike has a built-in adblocker since day one. How does it get undetected??

YouTube's adblock detection is completely client-sided, it has to be, since adblockers are completely client-sided too.
