### ISSUE TITLE
Live chat

### ISSUE THREAD

**Issue by aubymori** [Rehike/Rehike#37]
* Live chat doesn't get properly funneled through, and thus does not load.
* Chat replay is hidden by default, and thus shows "Show chat replay" on the hide label, and "Hide chat replay" on the show label.
![image](https://user-images.githubusercontent.com/44238627/179372609-988c605d-c179-4caa-8d4f-9bf630975370.png)
![image](https://user-images.githubusercontent.com/44238627/179372613-28905127-d41b-43a1-a013-60b76255d084.png)

**Comment by YukisCoffee** [comment]
Elaborate?

Live chat has always worked fine for me during testing, however chat replay never did.

Are you referring to all live chats (active and replay) or just replay?

**Comment by aubymori** [comment]
Live chat doesn't work at all for me.
And the replay shows the wrong toggled/untoggled text.

**Comment by aubymori** [comment]
The response from `special/get_live_chat.php` is literally empty.

**Comment by randomperson189** [comment]
I can also confirm that live chat doesn't work for me

**Comment by randomperson189** [comment]
Ok so as of the recent simplefunnel fix, I was able to get live chat somewhat working by passing it though the simplefunnel. Now I say somewhat becaust it works for a but until it just saying chat disconnected and then have to reload it

**Comment by aubymori** [comment]
Fixied by 9588cbad54f8e06aa860c4174cc974e0f46a5809.

Closing...
