### ISSUE TITLE
It Doesn't Work Homer

### ISSUE THREAD

**Issue by HARANARATE** [Rehike/Rehike#370]
### Rehike version

0.8.0

### Operating system

ubuntu 16

### PHP version

Idk

### What's going on?

![image](https://github.com/Rehike/Rehike/assets/148234876/d471f727-c509-4cbf-81c6-e572e72d6060)
IT Doesn't Work So Please Fix It Or Tell Me A Solution Pal Pal Pal

**Comment by ephemeralViolette** [comment]
`chmod -R 777 /path/to/rehike` or whatever you prefer.

you need to be able to write to the directory

**Comment by HARANARATE** [comment]
Write What? , I Made Myself Able And It Still Not Solved
