### ISSUE TITLE
Images/videos don't load anymore

### ISSUE THREAD

**Issue by DrChic0** [Rehike/Rehike#371]
### Rehike version

0.8.0

### Operating system

Windows 11 Home

### PHP version

8.0.12

### What's going on?

Images and videos don't load anymore as of yesterday it did from when I'm making this issue, when i turn off rehike everything loads, I've tried:
- updating rehike (from 0.7)
- updating windows
- restarting xampp
- restarting my pc

photos:
![image](https://github.com/Rehike/Rehike/assets/62633768/53a0cf08-4a79-4886-bd01-f135be07ec55)
![image](https://github.com/Rehike/Rehike/assets/62633768/0b291163-6734-4d6e-a80b-47883954dc0e)

**Comment by aubymori** [comment]
https://github.com/Rehike/Rehike/wiki/I-can-connect-to-Rehike,-but-nothing-loads
