### ISSUE TITLE
YouTube not loading

### ISSUE THREAD

**Issue by syndiate** [Rehike/Rehike#373]
### Rehike version

0.8.0

### Operating system

Windows 10 Version 2004

### PHP version

8.2.6

### What's going on?

Help me why isnt anything loading

![image](https://github.com/Rehike/Rehike/assets/67703687/b27b2ec2-ae48-4083-8319-7ebbb7a590e9)

**Comment by ephemeralViolette** [comment]
I will fucking kill you.
