### ISSUE TITLE
white space on homepage with 2013 theme

### ISSUE THREAD

**Issue by nope312** [Rehike/Rehike#383]
### Rehike version

0.8.0

### Operating system

windows 10 pro 64 bit version 1803

### PHP version

latest

### What's going on?

youtube is showing a weird blank space with youtube 2013 restored theme.
![2023_10_21_0xm_Kleki](https://github.com/Rehike/Rehike/assets/65314830/95ede037-ff98-4c64-abf0-b24e7d1d5d1c)

**Comment by YukisCoffee** [comment]
1. This is intended. It is meant to look like this. This is how YouTube looked in 2013.
2. We don't provide support for custom themes, in any case.
