### ISSUE TITLE
Trying to view the channel page of a channel that doesn't exist will crash Rehike

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#39]
Trying to view the channel page of a channel that doesn't exist will crash Rehike and give these details:
```
Uncaught TypeError: ChannelUtils::getUcid(): Return value must be of type string, null returned in C:\xampp\htdocs\controllers\utils\channelUtils.php:17
Stack trace:
#0 C:\xampp\htdocs\controllers\channel.php(43): ChannelUtils::getUcid(Object(Rehike\ControllerV2\RequestMetadata))
#1 C:\xampp\htdocs\controllers\core\HitchhikerController.php(109): Rehike\Controller\ChannelController->onGet(Object(stdClass), Object(Rehike\ControllerV2\RequestMetadata))
#2 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(51): Rehike\Controller\core\HitchhikerController->get(Object(stdClass), '', Object(Rehike\ControllerV2\RequestMetadata))
#3 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(73): Rehike\ControllerV2\GetControllerInstance->_cv2WrappedCallControllerMethod('get', Array)
#4 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(204): Rehike\ControllerV2\GetControllerInstance->__call('get', Array)
#5 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(148): Rehike\ControllerV2\Router::pointerHandler('channel', 'get')
#6 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(25): Rehike\ControllerV2\Router::baseRequestMethod(Array, 'get')
#7 C:\xampp\htdocs\router_v2.php(27): Rehike\ControllerV2\Router::get(Array)
#8 C:\xampp\htdocs\index.php(45): require('C:\\xampp\\htdocs...')
#9 {main}
  thrown
```
Please fix this.

**Comment by ineedseriousmentalhelp** [comment]
[README.md](https://github.com/Rehike/Rehike#readme)
⚠ ATTENTION ⚠
REHIKE IS VERY EARLY IN DEVELOPMENT.
THERE ARE VERY MANY MISSING FEATURES AND IT SHOULD NOT BE USED FOR ANY REASON OTHER THAN DEVELOPMENT.

**Comment by AshtyBoi** [comment]
Yes, I know.

**Comment by YukisCoffee** [comment]
> [README.md](https://github.com/Rehike/Rehike#readme) ⚠ ATTENTION ⚠ REHIKE IS VERY EARLY IN DEVELOPMENT. THERE ARE VERY MANY MISSING FEATURES AND IT SHOULD NOT BE USED FOR ANY REASON OTHER THAN DEVELOPMENT.

@ineedseriousmentalhelp This isn't the point. Issues like this _should be_ reported and that's the entire point of the issues tab here. It's redundant to restate that the project is early in development, and it can cause unnecessary conflict.

Please don't do that.

**Comment by AshtyBoi** [comment]
still broken...

**Comment by AshtyBoi** [comment]
It's getting a bit better, but this is still not normal.
![image](https://user-images.githubusercontent.com/107463768/183526710-c43778e0-aa4c-4ce9-9205-2e93cfd5eed7.png)

**Comment by aubymori** [comment]
Fixed some time ago. Closing.
