### ISSUE TITLE
2 issues with watch page with playlist and mix

### ISSUE THREAD

**Issue by Objectful** [Rehike/Rehike#40]
THis error shows when there's a playlist or mix.
![image](https://user-images.githubusercontent.com/73402079/180979629-d8b0d29f-3062-4f2f-aa9c-eab95a5c9638.png)

Also when a video in the playlist ends, it just loops the video and doesn't navigate to the next.

**Comment by YukisCoffee** [comment]
Recommendations bug should be fixed by 46f540e9d52783add8898416e559892207754a36

And other playlist related bugs on watch should all be fixed by e7bf9a07663950544a1c9a3cf458efd113ef9e27.

Closing...
