### ISSUE TITLE
Captions/subtitles not working

### ISSUE THREAD

**Issue by Felting** [Rehike/Rehike#404]
### Rehike version

0.7

### Operating system

Fedora 38 KDE spin x64

### PHP version

8.20

### What's going on?

Subtitles don't appear or load due to the request failing.

**Comment by YukisCoffee** [comment]
Cannot replicate, although why are you still on 0.7?

**Comment by Felting** [comment]
> Cannot replicate, although why are you still on 0.7?

Oops, forgot to change it, was the default in the issue page.
