### ISSUE TITLE
Project: Kill SpfPhp

### ISSUE THREAD

**Issue by YukisCoffee** [Rehike/Rehike#405]
SpfPhp was a bad design from the beginning, and it's about time that we throw it out. The entire design was facilitated upon keeping the templates simple, but I don't like this approach for a few reasons:

1. **It obfuscates what's actually going on.** How many people do you think could intuitively understand that, for SPF requests, we bake the HTML document and then reparse it to extract element information.
2. **It's very slow.** As it turns out, parsing giant HTML documents with PHP's "built-in" XML/HTML document parser is actually not all that efficient. This is very, very noticeable on playlist watch pages, which, although they can be parsed fine by a sophisticated HTML parser found in a web browser, slows to a crawl when parsed from the rudimentary one in PHP.
3. **It makes us rely on some hefty external packages.** As a matter of fact, we double wrap the PHP DOMDocument extension, going from SpfPhp to voku's parser (some random composer package I guess?) to DOMDocument.
4. **DOMDocument is an extension.** If you were closely reading, you would have noticed that I said "extension" earlier. While DOMDocument comes with XAMPP for Windows, so it hasn't been too bad for Rehike's general userbase, the extension still isn't really guaranteed to come with a PHP distribution. This may make things confusing, particularly due to the nature of SPF requests; errors will simply get dropped and the page will refresh, which end users probably will not know how to debug.

With all the flaws of this system, I propose moving away from the architecture. Well, then... What should we replace it with? Our original plan, dating back to 2022, was to make a Twig extension that was aware of SPF. I find that a syntactically nice implementation would run contrary to the philosophy of Twig, and the project remained dormant for a year before we removed the empty repository and officially scrapped that idea. **Instead, the SPF JSON responses should also be formed in Twig, just like HTML.**

As it stands, there are a few things that we must consider in transitioning toward a better, more considerate system:

- [x] Transition core headers (scripts, links, etc.) in the head and body into a standard format that can be utilised by both standard HTML templates and SPF JSON templates.
    - As it stands, the head is mostly scripts and links, anyways. The head can probably be copied into a general Twig template with some conditional logic to remove things that aren't supposed to be there in an SPF response.
    - Scripts in the body also tend to be at the bottom, so these can be treated in a similar manner, and I believe we already exclude certain scripts in the output in the case of an SPF response.
- [x] Transition page title handling to PHP.
    - The page titles are currently formed within Twig, specifically for given page types. We should migrate page title into the controllers instead.
- [x] Migrate SPF element bodies into unique Twig templates. I propose creating a subdirectory like `template/hitchhiker/spf` for this.
- [x] Move auxiliary pages (watch fragments AJAX, etc.)

Since this is a broad change for which we cannot create an experiment, we should create a branch to work on these changes collaboratively, and then merge them into master when they are considerably stable for general use. I think the benefits of making these changes outweigh the challenge of such a restructuring.

**Comment by YukisCoffee** [comment]
Also, worth consideration: element tag name is not considered at all by SPF. I wonder what happens even if you were to supply inner-HTML data to a void tag like img via SPF.js lol. That's why the syntax in Twig still has the tag name like normal.

**Comment by ephemeralViolette** [comment]
I created a branch for this: `dev-0.8-spf-rewrite`.

I think transitioning page titles to PHP will be the easiest task, so I will work on that first. I will add a new field to the yt global since we tend to compose the title with data from the model.

**Comment by ephemeralViolette** [comment]
Actually, as this is a non-breaking change, I will perform it on master.

**Comment by ephemeralViolette** [comment]
Title handling transition completed in 5f394ff.

**Comment by ephemeralViolette** [comment]
>Migrate SPF element bodies into unique Twig templates. I propose creating a subdirectory like `template/hitchhiker/spf` for this. 

Because they will be shared between SPF and standard Twig HTML templates, how about `page_fragments` instead?

**Comment by YukisCoffee** [comment]
Yeah that's good

**Comment by ephemeralViolette** [comment]
Instead of using conditional templates, I suppose we could simply use Twig's `renderBlock` instead of just `render` for things like `#content` and `#appbar-content`. If we keep the separation between HitchhikerController and NirvanaController, it should be no big deal, and it'd be a lot cleaner. https://twig.symfony.com/doc/3.x/api.html

We could've done this for title as well, but I think it makes more sense in general to form that in PHP and then just echo a HTML-escaped string, rather than whatever it is that we were doing before.

By the way, do we even use the `alerts` block at all? It's defined in the base templates, but to my knowledge, we only ever used them for the old fatal error screen, and it seemingly goes completely unused now. I think we should just remove it.

**Comment by ephemeralViolette** [comment]
>Migrate SPF element bodies into unique Twig templates.

Done in 190373c to the extent it most likely will be done. Feel free to untick if we end up going a different direction than using `renderBlock` for the blocks.

**Comment by YukisCoffee** [comment]
Oh, I didn't consider that. Sorry, I just hacked up the original issue earlier this morning.

Do you plan to implement it? If not, I'll get around to it in the next 1-2 days.

**Comment by ephemeralViolette** [comment]
Yeah, I could implement it. Although, since we're going out of our way to structure this nicely, I suppose you'd want some input on the API at least.

**Comment by aubymori** [comment]
fuck off

**Comment by YukisCoffee** [comment]
> Yeah, I could implement it. Although, since we're going out of our way to structure this nicely, I suppose you'd want some input on the API at least.

Sorry for the late response, but yeah I don't really care. You know how to make a good API, just make a commit and if there's something to change I guess we could change it later.

**Comment by YukisCoffee** [comment]
Okay, I made some backend classes in d220c37.

The PHP API should look something like this (of course, these calls in practice would be scattered across the codebase):

```php
Spf::createElement("player-playlist");
$element = Spf::getElementById("player-playlist");
$element->setAttribute("class", "whatever");
```

and the Twig API should look something like this:

```twig
<div {{ rehike.spf.element("player-playlist").attributes }}>
```

Although, I noticed there's another big issue with the templates, particularly regarding classes. Obviously the body class is a mess that we'll have to figure out how to work around, but did you notice that the class for `#page` is kinda worse? It's defined like this in `core.twig`:

```twig
<div id="page" class="{{ pageType }} {% block page_class %}{% endblock %}  clearfix ">
```

Where `pageType` is a variable declared in the child template, and page_class is a block. Additionally, for appbar-less pages, it doesn't even have clearfix. I suppose the best course of action would be to move this over to HitchhikerController (+ NirvanaController), in any case.

**Comment by YukisCoffee** [comment]
@aubymori You haven't expressed your thoughts on this yet, is all good or should be reworked?

**Comment by aubymori** [comment]
looks good to me

**Comment by ephemeralViolette** [comment]
I will migrate `pageType` and `#page[class]` to the controllers. Honestly, that's where they should have been in any case.

I'm more curious on what we are to do with the body class. Although it's already a standalone template because it needs to be shared between the two core templates, it is the primary consumer of template-defined variables, as far as I can tell.

Come to think of it, wouldn't it just be a much better solution to migrate all template-defined variables over to a PHP object? I think it would make the template code much cleaner, plus allow us to access these outside of the Twig context without some particularly nasty hacks.

**Comment by ephemeralViolette** [comment]
I migrated all of these view configuration variables in bcd8852.

There's a new class, `Rehike\ViewProperties`, which is used for `yt.viewProps` for frontend view configuration purposes. Configuration was moved to a simple function in the controllers, which runs during `postInit`, so you have access to a complete page model when it's called.

This should make it easy to migrate the formation of SPF element classes to PHP, although I'm curious how we are to go about that in an elegant manner. Regardless, please review the changes made and critique them. I'm very iffy on configuring the player class there; even though it is also a variable declared in the Twig context, it is used for an element class name, which is only different on one specific page. This seems more like a job reserved for the actual class builders, which are the next thing we must get to.

**Comment by YukisCoffee** [comment]
> I'm very iffy on configuring the player class there; even though it is also a variable declared in the Twig context, it is used for an element class name, which is only different on one specific page. This seems more like a job reserved for the actual class builders, which are the next thing we must get to.

I think it should be an SPF element.

**Comment by YukisCoffee** [comment]
It is over. See c1685b2172e9b655e6b95713057dcb8a181e40ee.

The way we've been going about things just really doesn't work. It made the codebase messier, harder to understand, and much less stable. Even if we could technically finish this the way we're going about it, I just don't see it as a very good idea. I guess I should've seen this coming.

I think the best path forward would be to form the SPF responses in JSON, like Rehike originally did. You may think it's crazy to go back to that, right? Well, SPF responses are just another type of view. They are fundamentally closer to HTML than PHP. And, apart from that, it is way easier and way *nicer* to share data between our HTML and SPF JSON responses within the Twig environment than it is to force half of it out into the PHP world.

Resetting from 190373c would be ideal, since that early work only affects Twig templates and makes sense to use in such a rewrite as well.

And I mean, seriously, Rehike only had 19 commits before SpfPhp was created. https://github.com/Rehike/Rehike/tree/e1bc63b8eb42a10e56d1217b273dbb0e5d107140

Surely we could do better now...

@aubymori @ephemeralViolette I would appreciate your thoughts on the matter. Personally, I think a development reset with this approach would be a really good idea.

**Comment by ephemeralViolette** [comment]
Yes, good idea.

**Comment by YukisCoffee** [comment]
I worked on this a bit in 0d82c4e and HOLY SHIT IT IS SO FAST. Give it a try!

Currently, page loading via SPF is a bit buggy. More classes need to be accounted for, as well as head and foot changes, and `data` (player data) and `rebug_data` fields.

**Comment by ephemeralViolette** [comment]
>More classes need to be accounted for

dd86630

**Comment by ephemeralViolette** [comment]
For `rebug_data`, we could cheat a little bit (to get the advantage of post-templating exposure). SPF JSON responses are always only one object layer deep, so we could just cut off the closing `}` and replace it with the exposed Rebug content.

**Comment by YukisCoffee** [comment]
Well, I think I completed all work necessary today. I will review it myself and determine if it is worth merging into master. Until then, I will close this issue, but please try out the working branch and let me know if it works out for you guys.

**Comment by YukisCoffee** [comment]
Update: I merged it into master. It seems very stable, so if there are any issues with it, I think it they would be best noticed in a public release.
