### ISSUE TITLE
New comment notification not having &lc url

### ISSUE THREAD

**Issue by Objectful** [Rehike/Rehike#41]
The link just redirects to the current url you're on.
![image](https://user-images.githubusercontent.com/73402079/181515696-2767451e-86c1-4e59-9938-a97038099d81.png)

**Comment by aubymori** [comment]
I believe this is due to the way Kevlar lets you view these inline. I'll see if I can find an LC link anywhere in the code.

**Comment by aubymori** [comment]
Yeah, this should work.
![image](https://user-images.githubusercontent.com/44238627/182036160-3677021f-6d53-4f26-94fe-4a3eb627b899.png)
