### ISSUE TITLE
Old comment count separator

### ISSUE THREAD

**Issue by VexorionReal** [Rehike/Rehike#413]
### Describe the feature

Prior to 2016 or 2015, the comment count separator was (X,XXX), but this has been changed to a bullet. Can you implement a config that changes the comment count separator back to the old one?
![chrome_ANFNNGARAq](https://github.com/Rehike/Rehike/assets/81510862/510ad085-7a73-40c2-bfd5-31827fa49cd8)

**Comment by YukisCoffee** [comment]
I think this is more reserved to the responsibility of third-party modifications to Rehike.

The comments change happened in 2016, and was a rewrite of the frontend HTML entirely. It always had the new styling. Also, the comments string before this time would actually be "All Comments".

**Comment by VexorionReal** [comment]
Right.
