### ISSUE TITLE
SPF navigation to /shorts/ gives a watch URL with `?spfreload=10` encoded into the `v` param

### ISSUE THREAD

**Issue by aubymori** [Rehike/Rehike#42]
![image](https://user-images.githubusercontent.com/44238627/182040104-ec02c1da-1b5d-4c90-98b1-b102f5ec0729.png)

**Comment by YukisCoffee** [comment]
Fixed by 0ca7eca1c7a35237802f6fe35e6c8dfa1d498430.

Closing...
