### ISSUE TITLE
Blurry icons with zoom or Windows display scaling

### ISSUE THREAD

**Issue by Ten2O** [Rehike/Rehike#423]
### Rehike version

0.8.0

### Operating system

Windows 11 Pro

### PHP version

8.2.4

### What's going on?

When zoom or display scaling is set to anything other than 100, many of the icons, logos, and buttons become blurry. A good example is the help button for the autoplay switch, and the like/dislike buttons, as well as the logo in the top left. This is very ugly, and it doesn't happen in the new layout.

On anything higher than 1080p, or on 1080p on things like laptop screens, everything is very small, making scaling a necessity, especially with limited vision.

**Comment by YukisCoffee** [comment]
This is how YouTube actually did things. We will not fix it. Use a userstyle instead.
