### ISSUE TITLE
Built-in CSS to reduce player button size

### ISSUE THREAD

**Issue by TorutheRedFox** [Rehike/Rehike#424]
### Describe the feature

The sizes of player buttons are designed around the (massive) sizing of current-day polymer. This is actually too big for smaller screen sizes where elements of the player chrome literally can't fit anymore. A solution would be to add some extra CSS that simply overrides the sizing of the elements in the player chrome to make them smaller.

I guess this technically falls under a stylistic change but it directly affects the player's functionality.

**Comment by YukisCoffee** [comment]
I will consider it, actually. In the meantime, check out https://github.com/YukisCoffee/yt-player-classicifier, which is probably what will be implemented into Rehike. I actually never tested without it, so I didn't know that anything was broken.

**Comment by TorutheRedFox** [comment]
I personally use a larger screen size now but I remember that when I used my MacBook with a 1280x800 display and the smaller youtube player size (640x360) via YouTube Redux things started to get very cramped with the default size (especially when chapters were involved)

**Comment by VexorionReal** [comment]
@YukisCoffee How exactly are you going to implement the smaller player size into Rehike?

**Comment by YukisCoffee** [comment]
I will embed optional CSS that is appended to the end. Probably using fragments of the source code of https://github.com/YukisCoffee/yt-player-classicifier.

You will be able to disable it.

**Comment by YukisCoffee** [comment]
Fixed in ac6e082. A new configuration option was added that embeds my local configuration of Player Classicifier, which feels quite comfortable on a small viewport.
