### ISSUE TITLE
Page titles sometimes don't get escaped correctly

### ISSUE THREAD

**Issue by TorutheRedFox** [Rehike/Rehike#425]
### Rehike version

0.8.0

### Operating system

Windows NT 10.0 19045.3086 (Windows 10 22H2)

### PHP version

8.2.11

### What's going on?

![image](https://github.com/Rehike/Rehike/assets/15708278/264ef3ff-6aa0-4da0-96fc-7277110cdc70)
This seems to be an SPF issue, as if the first page that gets loaded has such a character (in this case it's a ') it displays fine, but if you navigate to it (from, say, homepage, other video or channel page) you get this.

Example of a video affected: https://www.youtube.com/watch?v=_GARcKCaUfI

**Comment by ephemeralViolette** [comment]
yeah it was a small typo
