### ISSUE TITLE
category labels on channel page weird behavior

### ISSUE THREAD

**Issue by SpinThwomp** [Rehike/Rehike#427]
### Rehike version

0.8.0

### Operating system

macOS Sonoma 14.1.1

### PHP version

8.2.12

### What's going on?

the "videos" category on channel pages is labeled:

"video
s"

This occasionally happens with other categories on a given channel page but it's inconsistent, see screenshot

 
![Screenshot 2023-11-10 at 1 00 16 PM](https://github.com/Rehike/Rehike/assets/102715128/d690f43a-9455-4664-880a-d45ef567fb2c)

**Comment by YukisCoffee** [comment]
Is this Safari?

**Comment by SpinThwomp** [comment]
Yes

**Comment by ephemeralViolette** [comment]
safari issue.

**Comment by ephemeralViolette** [comment]
update: i tested in a windows build of webkit; same issue. not a rehike issue, but a safari/webkit issue.

use chrome or firefox.
