### ISSUE TITLE
Videos with content warnings cannot be watched, even signed in

### ISSUE THREAD

**Issue by aubymori** [Rehike/Rehike#43]
![image](https://user-images.githubusercontent.com/44238627/182266807-25bf759d-62fd-43fb-b3b9-c2089dde64e1.png)
[Video](https://www.youtube.com/watch?v=C8d12w6pMos)

**Comment by aubymori** [comment]
Something I also noticed. The "Learn more" isn't a link. Probably due to using `getText` instead of formatting properly.

**Comment by aubymori** [comment]
The video above now does not have the warning. [New video, which does](https://www.youtube.com/watch?v=k8jw3JVfK0w)

**Comment by ephemeralViolette** [comment]
Fixed in 9d9b829.
