### ISSUE TITLE
Can you bring this player storyboard back?

### ISSUE THREAD

**Issue by alpharetzy** [Rehike/Rehike#431]
### Describe the feature

Was browsing through the Wayback
Machine on my iPhone when i found this:

![IMG_3463](https://github.com/Rehike/Rehike/assets/112749084/8ad9a729-3076-4469-8738-94cb0587f471)

It’s the one that has large frames. Old storyboard with player classicifer style is different. Can you bring this back with upcoming video player appearance settings?? it could be belong on a 2019 option

*The video seek thumbnail is not displayed, just a large black rectangle with a video timestamp.

Mockup of what it mean:

![IMG_3463](https://github.com/Rehike/Rehike/assets/112749084/e6614be5-d44b-4eb5-91c3-db3ca9248a06)

**Comment by aubymori** [comment]
Rehike doesn't touch player. You can use [YT Player Classicifier](https://github.com/YukisCoffee/yt-player-classicifier) for this.

**Comment by alpharetzy** [comment]
But it’s different on the classicifer style. It’s the same as normal but the frames are black & the timestamp being at the bottom center of the thumbnail preview.

**Comment by aubymori** [comment]
> But it’s different on the classicifer style. It’s the same as normal but the frames are black & the timestamp being at the bottom center of the thumbnail preview.

then fix it yourself idk what to say lol

**Comment by alpharetzy** [comment]
> > But it’s different on the classicifer style. It’s the same as normal but the frames are black & the timestamp being at the bottom center of the thumbnail preview.
> 
> then fix it yourself idk what to say lol

I need to start working oh this

**Comment by alpharetzy** [comment]
> > > But it’s different on the classicifer style. It’s the same as normal but the frames are black & the timestamp being at the bottom center of the thumbnail preview.
> > 
> > 
> > then fix it yourself idk what to say lol
> 
> I need to start working on this.

![image](https://github.com/Rehike/Rehike/assets/112749084/55849ecf-a870-4c6f-b390-01f2a272dac8)
 
now done.
