### ISSUE TITLE
Videos won't load, browser console is full of errors

### ISSUE THREAD

**Issue by nulcow** [Rehike/Rehike#439]
### Rehike version

0.8.0

### Operating system

Microsoft Windows 10 version 1809 (build 17763.5122)

### PHP version

PHP 8.2.4

### What's going on?

When I try to watch a video using Rehike, this is what the watch page looks like:
![BugReport_watchpage](https://github.com/Rehike/Rehike/assets/88356560/fdf34547-7ee5-4ee5-9cda-8f41bb715666)
It will not load no matter how much I wait for it.

This is the browser console while loading a video:
![BugReport_console](https://github.com/Rehike/Rehike/assets/88356560/8bd10887-d540-4e0e-842c-0bd8ec9bc074)

There seems to be something wrong with the requests the application is making.

**Comment by aubymori** [comment]
you did not install rehike correctly
