### ISSUE TITLE
Rehike treating channel profile pictures in Search, feautured channels sidebar and Channels tab as video thumbnails

### ISSUE THREAD

**Issue by Objectful** [Rehike/Rehike#44]
![image](https://user-images.githubusercontent.com/73402079/182352509-e0f79f9f-bd9c-4aa2-98ca-d2b66cf9d7c2.png)
![image](https://user-images.githubusercontent.com/73402079/182352576-d32b1c6d-687f-47b2-8406-29391c686e0b.png)
![image](https://user-images.githubusercontent.com/73402079/182352628-126a5b2e-5594-4458-9b93-e11ae600e100.png)

**Comment by aubymori** [comment]
I have yet to replicate this.

**Comment by aubymori** [comment]
Seems disabling `yt.config.enableRehikeDebugger` triggers this. Working on it right now.
