### ISSUE TITLE
Autoplay settings do not persist

### ISSUE THREAD

**Issue by dollhaus** [Rehike/Rehike#448]
### Rehike version

0.8.0

### Operating system

Windows NT 10.0 build 17763 (Windows Server 2019)

### PHP version

8.2.4

### What's going on?

- build 1238, 2023-12-02

On pulling the current nightly available as of today, autoplay persists in it's enabled state, despite being toggled off. 

This behaviour occurs when opening a new tab, but not when navigating to a video in the same tab. I have attached a demonstration below: 
[Sequence #1(1)-1.webm](https://github.com/Rehike/Rehike/assets/33754407/615e42d4-dd15-4906-89a8-f6ab06048806)

**Comment by YukisCoffee** [comment]
Does clearing cookies correct it? Depending how old the version you had before pulling, it may actually predate the bug in question.

If it was reintroduced, I will kill Aubrey.

**Comment by YukisCoffee** [comment]
![image](https://github.com/Rehike/Rehike/assets/99076687/b5e9d3ad-aa1c-4287-a39d-33047de19947)

I am technically a few versions behind because I have some uncommitted changes, but it seems to be working alright for me.

**Comment by aubymori** [comment]
> Does clearing cookies correct it? Depending how old the version you had before pulling, it may actually predate the bug in question.
> 
> If it was reintroduced, I will kill Aubrey.

dawg it's not my fuckin fault literally the last change i made in like weeks is the comment mentions commit i did

**Comment by YukisCoffee** [comment]
> > Does clearing cookies correct it? Depending how old the version you had before pulling, it may actually predate the bug in question.
> > If it was reintroduced, I will kill Aubrey.
> 
> dawg it's not my fuckin fault literally the last change i made in like weeks is the comment mentions commit i did

Daylin then.

**Comment by dollhaus** [comment]
> Does clearing cookies correct it? Depending how old the version you had before pulling, it may actually predate the bug in question.
> 
> If it was reintroduced, I will kill Aubrey.

I didn't specifically test for this, but I did try it in another browser and in private browsing, neither of which changed this behaviour.

The build I ran prior, and the one to which I reverted, is 2023-10-26.

**Comment by YukisCoffee** [comment]
The issue is probably that you have multiple instances of the PREF cookie, one which is read by the server and one which is written to by the browser. There should only be one.

A Rehike bug was causing malformed duplicate PREF cookies to be formed, which causes the desynchronization. Indeed, the code responsible to generate this is gone, from what I can tell, but there are persistent side effects in reading it.

**Comment by dollhaus** [comment]
ya I had a fair few, perhaps fifty or so in all. Unfortunately, getting rid just results in a handful returning: 

![Capture](https://github.com/Rehike/Rehike/assets/33754407/22f6818b-7c5a-4f18-b415-03d50ce11d47)

**Comment by YukisCoffee** [comment]
I wonder why the changes in 809e021001823c25d359e56b1d7ceaa3e0300b26 aren't affecting your use. Does this bug also affect private tabs? Indeed, you seem to have the same bug as before this change...

**Comment by kawapure** [comment]
I believe this issue has been patched. I'll close this unless more information is provided.
