### ISSUE TITLE
"Save changes" button stays greyed out even after modifying settings and the old logo does not show up inside the Youtube tab.

### ISSUE THREAD

**Issue by OleExploder** [Rehike/Rehike#449]
### Rehike version

0.8.0

### Operating system

Windows 11 22H2 2261.2715

### PHP version

8.2.12

### What's going on?

I tried modifying my ReHike settings back after replacing all of the files to update it but the "Save changes" button still appears to be greyed out which means I couldn't change the settings back unless I got the file with the original settings from another computer which is what I did. About the logo inside the Youtube tab, it did not show the older logo after updating rehike and showed the current logo in the tab instead.

**Comment by YukisCoffee** [comment]
Fixed in https://github.com/Rehike/Rehike/commit/12e97524423ffc198d5afa78233835bb33f11275.
