### ISSUE TITLE
Add a "Load more" button to the search results

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#45]
![image](https://user-images.githubusercontent.com/107463768/182367336-ecee2a9c-6a5a-40d3-86fb-427b23b6a250.png)
Sometimes, you need to dig deep within the search results to see the video that you're looking for. You will probably need a couple of "Load more" button clicks to find it. It seems that in Rehike, the button is absent. Adding it in the search results would save people a lot of searches.

**Comment by randomperson189** [comment]
I remember there used to be a bunch of number buttons down there pretty much showing pagination, it would be nice to add an option for pagination or load more in the config
