### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by TheOnlyOne12315** [Rehike/Rehike#452]
### Rehike version

0.7

### Operating system

Windows NT OS Build 22621.2792

### PHP version

idk

### What's going on?

The certificate in the install instructions expired.

**Comment by aubymori** [comment]
no??????

**Comment by TheOnlyOne12315** [comment]
> no??????

![Screenshot 2023-12-13 144648](https://github.com/Rehike/Rehike/assets/152047025/355074d5-39ae-4db7-989f-57a343121e14)

**Comment by aubymori** [comment]
> > no??????
> 
> ![Screenshot 2023-12-13 144648](https://private-user-images.githubusercontent.com/152047025/290310688-355074d5-39ae-4db7-989f-57a343121e14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0OTcyMzAsIm5iZiI6MTcwMjQ5NjkzMCwicGF0aCI6Ii8xNTIwNDcwMjUvMjkwMzEwNjg4LTM1NTA3NGQ1LTM5YWUtNGRiNy05ODlmLTU3YTM0MzEyMWUxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxOTQ4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjUzNWY3ZTk1MWRmNzM1M2MzNGRhM2U5YjMxOGFjOTIzODlhNjE2NTI3ODMxZjMyNTJlYWYzMjlhM2Y0NGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IZp0xR5qM0NOWBjS9bZxMakerOeFZT6BFpd_e9e0O70)

jesus christ if you would take 5 fucking seconds to read you can see it clearly says 2032 and not 2023. bogus ass issue
