### ISSUE TITLE
Light Theme for 2015 Player

### ISSUE THREAD

**Issue by OleExploder** [Rehike/Rehike#461]
### Describe the feature

I know you can set the player's background to gray for this but I think it would be interesting to see a light theme with actual black buttons on the Youtube player itself to make it more accurate to this light-mode player that actually existed on Youtube back in 2014 which I found here: https://www.reddit.com/r/oldyoutubelayout/comments/18uaiwz/screenshot_of_a_lightmode_youtube_player_seen_in/

I also see no options to change the button colors on the player so that is another reason I request a feature that can recreate the light-mode theme.

**Comment by OleExploder** [comment]
I am so sorry about this, I meant to type this for PlayerTube but I wasn't aware I was on the ReHike website.

**Comment by YukisCoffee** [comment]
All good!

**Comment by OleExploder** [comment]
Thank you.
