### ISSUE TITLE
Revision hopping

### ISSUE THREAD

**Issue by VexorionReal** [Rehike/Rehike#467]
### Describe the feature

I know this is something you can do with CSS and Stylus, but I was thinking of adding a Hitchhiker revision choice in the config (2015 Hitchhiker, for example). If you don't want to add it, that's fine.

**Comment by YukisCoffee** [comment]
This would require too much effort.

**Comment by VexorionReal** [comment]
Right.

**Comment by VexorionReal** [comment]
@YukisCoffee What do you mean by too much effort?
