### ISSUE TITLE
2014 player not working in older browsers

### ISSUE THREAD

**Issue by TorutheRedFox** [Rehike/Rehike#484]
### Rehike version

0.8.0

### Operating system

N/A

### PHP version

N/A

### What's going on?

2014 player doesn't work in older browsers due to it being set up using newer JS syntax.

**Comment by ephemeralViolette** [comment]
If the newer JS syntax is used in the player itself, then this will not be fixed.

**Comment by TorutheRedFox** [comment]
> If the newer JS syntax is used in the player itself, then this will not be fixed.

that wouldn't make sense though

browsers that were the latest version at the time of the player's release don't work while the literal latest does

**Comment by TorutheRedFox** [comment]
fixed in #489
