### ISSUE TITLE
Apostrophe Glitch In 2014 Player While in Full Screen

### ISSUE THREAD

**Issue by OleExploder** [Rehike/Rehike#485]
### Rehike version

0.8.0

### Operating system

Windows 11 23H2 (OS Build 22621.3007)

### PHP version

Version 0.8.1 (build 1293, 2024-01-16)

### What's going on?

In full screen mode while using the experimental 2014 player, apostrophes in video titles show up as "&#039;" but without the quotation marks if a video title has one.

**Comment by ephemeralViolette** [comment]
Fixed in fb66c3f

**Comment by OleExploder** [comment]
Thanks.
