### ISSUE TITLE
Issue with JDownloader 2

### ISSUE THREAD

**Issue by docrR** [Rehike/Rehike#488]
### Rehike version

0.7

### Operating system

Windows NT 6.1 7601

### PHP version

8.2.12

### What's going on?

Hello,
I am unable to use JDownloader 2 to save content from YouTube. When I enter a link to save a video/audio, only the video thumbnail is fetched. I was reading in the manual that --no-check-certificates can be used with youtube-dl, but I am unsure how JDownloader enforces certificates.
Thanks.

**Comment by TorutheRedFox** [comment]
I'm pretty sure that these downloaders scrape the watch page for data which could be causing it to not work because I don't expect them to support hitchhiker anymore

**Comment by kawapure** [comment]
This issue has been closed for inactivity, and there are not enough details to work off of. We are unfamiliar with this software and thus unable to provide support.
