### ISSUE TITLE
[2014 player] Subtitles/CC button not working for videos which don't include their own subtitles

### ISSUE THREAD

**Issue by CatmanFan** [Rehike/Rehike#491]
### Rehike version

0.8.0

### Operating system

Windows 10 build 10.0.18363.418 (1909)

### PHP version

8.2.4

### What's going on?

While the subtitles/CC button on the 2014 player works for videos which already contain manually-created subtitles, it does not behave properly with those that don't and the auto-generate feature seems to be missing for them.

For example, here is a video without manually-created subtitles, the button is visible when the player is first loaded:

![image](https://github.com/Rehike/Rehike/assets/30674270/078e6b1b-aac5-4435-b6c7-90bd6fb19731)

but when either it or the Settings icon is clicked, the CC icon disappears along with the subtitled languages list in Settings:

![image](https://github.com/Rehike/Rehike/assets/30674270/dc0ecdb0-621c-4094-934a-b6ee3747a7af)

**Comment by TorutheRedFox** [comment]
forgot to mark this as fixed
![image](https://github.com/Rehike/Rehike/assets/15708278/ba879532-cff5-41c3-8a59-01034c85b7f3)
