### ISSUE TITLE
Inconsistent player theming options

### ISSUE THREAD

**Issue by DavidCGranger** [Rehike/Rehike#494]
### Rehike version

0.7

### Operating system

/

### PHP version

/

### What's going on?

Theming options for current player are in their own category, theming options for 2014 are part of the 2014 player settings category or how you want to call it
![grafik](https://github.com/Rehike/Rehike/assets/96387429/81e68483-cbce-4209-9ba7-01d2bbc9a8aa)
![grafik](https://github.com/Rehike/Rehike/assets/96387429/8b0e428e-2d96-41de-ae31-362e8fe7340e)

**Comment by YukisCoffee** [comment]
This was an intentional design choice, but you're right that it's pretty weird. It will likely be improved in the future.

**Comment by TorutheRedFox** [comment]
yeah player theming should probably be its own section that shows options relevant to the current player selected
