### ISSUE TITLE
Unsubscribing does not work.

### ISSUE THREAD

**Issue by ineedseriousmentalhelp** [Rehike/Rehike#50]
### protip: tjhis is a gif
Ag,
![msedge_07lzDd7A8Z](https://user-images.githubusercontent.com/109477049/182980117-b2314f23-8b8a-4ff1-9030-dd5acdcac342.gif)

**Comment by aubymori** [comment]
`subscription_ajax` doesn't work at all

**Comment by ineedseriousmentalhelp** [comment]
oh how ironic

**Comment by aubymori** [comment]
Yeah, I'm working on it at the moment. I was stumped at giving it the subscribe button params from InnerTube but it turns out adding `data-params` makes it work.

**Comment by ineedseriousmentalhelp** [comment]
cool

**Comment by YukisCoffee** [comment]
Moved to megathread #75. Closing...
