### ISSUE TITLE
2020 and 2022 players are still rate limited

### ISSUE THREAD

**Issue by SpinThwomp** [Rehike/Rehike#503]
### Rehike version

0.8.0

### Operating system

macOS 14.2.1

### PHP version

8.2.4

### What's going on?

Exactly what the title says, I'd really like to use the 2020 player but it is beyond sluggish. Anything above 480p takes minutes to load.

**Comment by syndiate** [comment]
What branch is this on?

**Comment by SpinThwomp** [comment]
master

**Comment by TorutheRedFox** [comment]
n decoding isn't implemented for them yet

doing that should be simple tbh

**Comment by TorutheRedFox** [comment]
![image](https://github.com/Rehike/Rehike/assets/15708278/9556905c-aea5-43b0-92df-e5c5693270d5)
seem to have fixed it

**Comment by TorutheRedFox** [comment]
spf navigation doesn't work yet though

**Comment by TorutheRedFox** [comment]
it's still a bit iffy but it seems to mostly work

**Comment by SpinThwomp** [comment]
Works great on my end, let me know if I should leave this open if there are still issues, otherwise ill close it. Thanks!

**Comment by danielah05** [comment]
i still have this issue even on the latest master commit, makes videos really unwatchable

**Comment by i-lost-my-bagel** [comment]
I've found that this happens if you switch to the 2014 player and then back to the 2020 or 2022 one.
