### ISSUE TITLE
option to use 'cc' caption button on older players

### ISSUE THREAD

**Issue by SpinThwomp** [Rehike/Rehike#507]
### Describe the feature

On players before 2020, the cc button isn't consistent with how it looks in certain parts of the world (see below).

Rehike:
![Screenshot 2024-01-31 at 2 51 21 PM](https://github.com/Rehike/Rehike/assets/102715128/5118ee96-ba62-4828-a4b2-1c90ea82779b)

non-rehike example:
![Screenshot 2024-01-31 at 2 51 10 PM](https://github.com/Rehike/Rehike/assets/102715128/2bab74a2-2a23-4b40-b208-4ff3b2345d87)

**Comment by TorutheRedFox** [comment]
tbh idk what makes it show as cc and not as cc

**Comment by TorutheRedFox** [comment]
this was actually caused by an oversight in the player init
