### ISSUE TITLE
Literally every music video still fails to play back both on 2014/2015 and 2020/2022

### ISSUE THREAD

**Issue by DavidCGranger** [Rehike/Rehike#520]
### Rehike version

0.8.0

### Operating system

Fedora 39 and some build of Windows 11

### PHP version

8.2.4

### What's going on?

https://www.youtube.com/watch?v=Soa3gO7tL-c
https://www.youtube.com/watch?v=hT_nvWreIhg
https://www.youtube.com/watch?v=RBumgq5yVrA
etc.

**Comment by YukisCoffee** [comment]
This was a side effect of a logic error in the cache expiration code that caused it to never regenerate. This has been fixed in 7235979.
