### ISSUE TITLE
Like counts is one more for that I pressed like.

### ISSUE THREAD

**Issue by bluedragon-cairo** [Rehike/Rehike#523]
### Rehike version

~~0.7~~ 0.8 (master branch)

### Operating system

For the client Windows XP and the PHP server running is Windows Server 2019

### PHP version

latest

### What's going on?

I'm using the near recent version of rehike.

For example, if there is a video with 5 likes, and I press like and refresh, the like count displays as 7 (If I go to a different account it shows 6). And when it's 7 with me like pressed and unlike and refresh, it becomes 5 again. This happens in comments too

**Comment by syndiate** [comment]
Are you on the latest GitHub version? I (at least likely considering the existence of this issue) fixed it a week or two ago.

**Comment by bluedragon-cairo** [comment]
I'm using the master branch... what branch is the fixed one? I tried the latest brange now but issue persists

**Comment by syndiate** [comment]
Master should be the one. Go to https://www.youtube.com/rehike/version and send a screenshot of what's here just to make sure that you are indeed using the latest version.

**Comment by bluedragon-cairo** [comment]
![image](https://github.com/Rehike/Rehike/assets/76606635/b4425b4c-7022-4078-b690-bd677e2eb239)

**Comment by bluedragon-cairo** [comment]
So It's 0.8.

**Comment by syndiate** [comment]
Tried doing it and couldn't reproduce.

**Comment by syndiate** [comment]
The screenshot didn't include the current branch information, can you please send that?

**Comment by ephemeralViolette** [comment]
> The screenshot didn't include the current branch information, can you please send that?

It's pointless to request this. Commit 1355 (fbe96884cb56430f5c438b466ab38c76267ee1ff) is the important part, which only exists on master and whichever new branch was made (most likely master though).

**Comment by syndiate** [comment]
Tried this and couldn't reproduce. Anyone else?

**Comment by syndiate** [comment]
Why the hell is it happening to me now? I feel like it _may_ have something to do with the new "view model" system (I didn't look through the code yet, so take that "hypothesis" with a grain of salt).
