### ISSUE TITLE
"The certificate is not trusted because it is self-signed" ERR on Firefox

### ISSUE THREAD

**Issue by mrbatguy0314** [Rehike/Rehike#524]
### Rehike version

0.8.0

### Operating system

WIndows 8.1 Professional

### PHP version

8.2.0

### What's going on?

i am on rehike 0.8.1
![rehike is evil](https://github.com/Rehike/Rehike/assets/141572235/f0c0a565-141b-48f9-a4cf-95835997ee67)

**Comment by syndiate** [comment]
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate
https://github.com/Rehike/Rehike/wiki/Installation#importing-the-certificate

**Comment by ephemeralViolette** [comment]
Also remember to restart the server

**Comment by syndiate** [comment]
+  ipconfig /flushdns
+ Restart Firefox and go to about:networking#dns and click Clear DNS (if that's even a thing in old Firefox)
