### ISSUE TITLE
The player change setting doesnt work after the update + <2020 players problems with livestreams

### ISSUE THREAD

**Issue by vistafan12** [Rehike/Rehike#525]
### Rehike version

0.8.0

### Operating system

Microsoft Windows 11 [Version 10.0.22631.2861] (Pro)

### PHP version

8.2.4

### What's going on?

After the latest update ("[player hard reset on failure](https://github.com/Rehike/Rehike/commit/15a76e8da02cbed93c86d6e1324561b8581241a3)"), the "change player" setting no longer works properly (the player doesn't change after the update):
![image 1](https://github.com/Rehike/Rehike/assets/20767476/ec08985d-778c-4c33-a189-b48dd5fef7db)
![image 2](https://github.com/Rehike/Rehike/assets/20767476/a933612b-9d00-40d0-a016-64a936cc4743)

I tried to clear the cache and use Private mode in Firefox, but still with no effect. Other browsers (Chrome-based Edge) have the same problem.

Before the update, players older than 2020 (even the 2020 player had some issues with it) had a problem with live streams (they just didn't work or worked improperly). I know that this is _probably not fixable_, but I prefer to let you guys know. _Maybe_ if the uploaded video is a livestream, changing the player to the newest one is the correct answer to fix that bug, but that's just my thought.

Firefox version: Mozilla Firefox 122.0.1 (64-bit), Windows

**Comment by TorutheRedFox** [comment]
most streams should work now

there's a small handful that still don't though and I'm not exactly sure why yet

**Comment by YukisCoffee** [comment]
Player changing should be fixed in 7235979.

**Comment by vistafan12** [comment]
works like a charm, thanks!
