### ISSUE TITLE
Playlist that video is contained in does not function properly with SPF

### ISSUE THREAD

**Issue by syndiate** [Rehike/Rehike#526]
### Rehike version

0.8.0

### Operating system

Windows 10

### PHP version

8.2.4

### What's going on?

When warm loading into say a playlist from a search page, the section where the playlist should be is totally blank.
When cold loading it loads the playlist, but navigating into another video from the playlist won't update the playlist (navigating to a separate video gets rid of it)

**Comment by syndiate** [comment]
Latest, although I'm not sure that the issue still occurs on that due to the latest player experiments being reverted. I'd have to test that.

**Comment by YukisCoffee** [comment]
I can't seem to replicate this, so please confirm with me that it's been resolved in the past few days. It could have been a bug with the range of commits from Toru that I had reverted a few days ago.

**Comment by kawapure** [comment]
Any updates?
