### ISSUE TITLE
watch page errors (2)

### ISSUE THREAD

**Issue by ineedseriousmentalhelp** [Rehike/Rehike#53]
![image](https://user-images.githubusercontent.com/109477049/183228566-95ee4b3e-1450-4e9a-8561-49810697c7a8.png)
lo

**Comment by aubymori** [comment]
try deleting `cache/player_cache.php` and see if there's any errors still

**Comment by ineedseriousmentalhelp** [comment]
ok

**Comment by ineedseriousmentalhelp** [comment]
it fixed it, but playlists also have issues 😀 how ironic

**Comment by aubymori** [comment]
please open an issue for playlists

**Comment by ineedseriousmentalhelp** [comment]
ok
