### ISSUE TITLE
Certain videos do not load or show an error message.

### ISSUE THREAD

**Issue by OleExploder** [Rehike/Rehike#531]
### Rehike version

0.8.0

### Operating system

Windows 10 22H2 x64 (OS Build 19045.3930)

### PHP version

8.2.12

### What's going on?

Sometimes when I try to watch a video it keeps buffering nonstop or sometimes it may say that an error occurred and that I need to try again later. This is also not an internet issue since I have a very good internet connection especially since my pc is hardwired.
![Capture 2](https://github.com/Rehike/Rehike/assets/113773450/52642246-e5e9-4325-9553-b3299f0d410f)
![Capture 3](https://github.com/Rehike/Rehike/assets/113773450/c3feee79-21e9-48f0-8bcf-9176feb1bedb)

**Comment by alpharetzy** [comment]
![image](https://github.com/Rehike/Rehike/assets/112749084/a5ed5a91-39af-4b94-9728-540aa1581848)

![image](https://github.com/Rehike/Rehike/assets/112749084/f79e1684-9c01-47d7-8f2a-3cf181c900c7)

Same issue as you, even when turning off all extensions & turning off the video player settings experiment.

**Comment by OleExploder** [comment]
I wonder if anything can be done to resolve this problem though.

**Comment by DavidCGranger** [comment]
Already mentioned in #520

**Comment by OleExploder** [comment]
Ok, thanks.
