### ISSUE TITLE
SPF navigation in Firefox doesn't remove existing player

### ISSUE THREAD

**Issue by TorutheRedFox** [Rehike/Rehike#532]

**Comment by YukisCoffee** [comment]
Autoplay being blocked should have no effect on this behavior. It shouldn't even affect SPF navigation at all, because autoplay is enabled once the user clicks anywhere on the tab. But even if autoplay were to be blocked, it shouldn't break that at all.

**Comment by TorutheRedFox** [comment]
from what i've noticed is it causes the player failure to trigger mid-navigation causing firefox to get massively confused i guess?

**Comment by ephemeralViolette** [comment]
Toru, you introduced this bug. It does not happen in fbe9688 from 2 weeks ago.

**Comment by TorutheRedFox** [comment]
yeah i realized that

introducing a bug while fixing another one is just average software dev experience lol

now to figure out an approach that fixes both..

**Comment by YukisCoffee** [comment]
Since I reverted all of Toru's commits made in the past 2 weeks, this issue is now fixed.
