### ISSUE TITLE
Like & dislike buttons in the comments section do not work properly and heart button shows on my comments even though they aren't on my own videos.

### ISSUE THREAD

**Issue by OleExploder** [Rehike/Rehike#535]
### Rehike version

0.8.0

### Operating system

Windows 10 22H2 x64 (OS Build 19045.3930)

### PHP version

8.2.12

### What's going on?

When I try to put a like on a comment someone made on a video, the like number does not change and the button does not turn blue like it is supposed to. The dislike button also does not turn another color when I click it either and the heart button was showing up on my comments even though the comments I made are not on my own videos.

**Comment by YukisCoffee** [comment]
Related to #505.
