### ISSUE TITLE
Comments doesn't load if there are no comments

### ISSUE THREAD

**Issue by bluedragon-cairo** [Rehike/Rehike#537]
### Rehike version

0.8.0

### Operating system

Windows 7 x64

### PHP version

latest

### What's going on?

Version: master commit 3 hours ago

If there are no comments, then the comments section hangs at "loading..." (bug does not happen if there are any comments posted)

Also, when I post a comment, it just shows a loading spinner infinitely until I refresh the page, and my new comment is only visible after refresh.

Tested on SeaMonkey 2.53 (my main browser), Firefox 88.0, and latest version of Chrome (Supermium) v121

**Comment by YukisCoffee** [comment]
Side effect of #505, so this issue will be referred to there.
