### ISSUE TITLE
Posting a comment gets stuck on loading

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#540]
### Rehike version

0.8.0

### Operating system

Windows 10

### PHP version

8.2.0

### What's going on?

Whenever I post a comment on a video, it gets stuck on the loading spinner
![image](https://github.com/Rehike/Rehike/assets/32617562/4a719f27-2b62-4e18-a4e0-c8ae5bf961c6)

**Comment by YukisCoffee** [comment]
Related to #505.
