### ISSUE TITLE
Add J And L Hotkeys Please

### ISSUE THREAD

**Issue by HARANARATE** [Rehike/Rehike#541]
### Describe the feature

The Video Player 2014 Lacks Three Hotkeys.
 First Is **J** That Makes Video The Rewind By 10 Seconds.
 Second Is **K** That Makes The Video Pause.
 Third Is **L** That Makes The Video Fast Forward By 10 Seconds.
The Hotkeys **J** And **L** Were Made Back In 2013 And Here Is The Proof:
https://www.reddit.com/r/LifeProTips/comments/1h69bn/lpt_press_k_to_pause_your_youtube_video_instead/?sort=old
![fd](https://github.com/Rehike/Rehike/assets/148234876/fbc01dd0-9e8c-461f-91f7-d1fcf55362e7)
The Hotkey **K** Was Made Back In 2012 And Here Is The Proof:
https://www.reddit.com/r/LifeProTips/comments/ruh5k/lpt_while_on_a_youtube_video_hit_k_to_playpause/

**Comment by YukisCoffee** [comment]
This feature was not supported by old HTML5 players (before 2015), but we added an event listener to reimplement it for the 2014 player anyways. But the implementation is a little buggy at the moment, and it only applies if you hard refresh on the watch page.

**Comment by HARANARATE** [comment]
So You Will Have To Code It As A HTML5 Player For It To Work

**Comment by YukisCoffee** [comment]
The player is already HTML5, and the code to add this extra feature already exists; it just doesn't get executed unless you hard refresh a page because of a Rehike bug.

**Comment by kawapure** [comment]
The aforementioned bug ("it just doesn't get executed unless you hard refresh a page because of a Rehike bug") has since been fixed. Closing...
