### ISSUE TITLE
[Failed InnerTube request] Rehike keeps constantly failing

### ISSUE THREAD

**Issue by elaymm4** [Rehike/Rehike#543]
Used to work absolutely fine, but lately often crashes when trying to open any page or refresh.
[20240303215339-home.txt](https://github.com/Rehike/Rehike/files/14474550/20240303215339-home.txt)

**Comment by kawapure** [comment]
Are you still experiencing this issue? It seems to me like this was just a local network hiccup. All three requests had failed for you, but poor design on our end made the exception hide the actual reason.
