### ISSUE TITLE
bug reporting speedrun 🤯 (RehikeConfigManager does not get the config shit)

### ISSUE THREAD

**Issue by ineedseriousmentalhelp** [Rehike/Rehike#55]
![image](https://user-images.githubusercontent.com/109477049/183229672-0515ec34-897a-4dfd-b6d4-1e2dae3e09a3.png)

**Comment by aubymori** [comment]
this is not a bug, `$defaultConfig` sets the default config for when you first install rehike or when values are missing and it needs to set them again.

**Comment by ineedseriousmentalhelp** [comment]
oh so im just a dumbass cool
