### ISSUE TITLE
Turkish Localization needed

### ISSUE THREAD

**Issue by supermarioglitchy10** [Rehike/Rehike#553]
### Describe the feature

i have seen the team add new languages to rehike, such as Korean, Dutch, etc.
it would be nice to have the Turkish language to be included, while it may not be a problem to use English for me, but for other turks the language is needed for easier, non alienating guiding

**Comment by YukisCoffee** [comment]
Translations aren't maintained by the core developers of Rehike (we can only speak English or Japanese), but by translation contributors.

The appropriate course of action to submit a new translation would be opening a pull request with new translation files. You can get started by simply copying a different i18n subdirectory, then rewriting the strings in your target language.
