### ISSUE TITLE
The player dosen't load ALL buttons...

### ISSUE THREAD

**Issue by coffeemccoffee** [Rehike/Rehike#57]
The Player does only show few buttons, not the ones like the options and full screen.
![image](https://user-images.githubusercontent.com/104205144/183259863-1f8ada58-7506-443e-8399-aec95d82a458.png)

**Comment by aubymori** [comment]
this is most likely a bug on your end. disable any css that may be affecting the player

**Comment by aubymori** [comment]
even if it isn't a bug on your side it's probably a bug on youtube's side

**Comment by YukisCoffee** [comment]
This is certainly a local bug; Rehike does not touch the player, and that camera icon should not be ordinarily displayed.

I presume this is an issue with:

1. Chrome usage (you ordinarily get the Cast to TV button)
2. Rehike not supporting Cast to TV
3. Userstyle that hides other icons based on precise :nth-child() selectors.
