### ISSUE TITLE
post notifications pop out doesnt work most of the time

### ISSUE THREAD

**Issue by blockedrex** [Rehike/Rehike#570]
### Rehike version

0.8.1

### Operating system

Windows 10 build 19045 x64

### PHP version

8.2.12

### What's going on?

when you attempt to turn on post notifications for a subscribed youtuber its supposed to open a popout with the different options, however most of the time it does open, however it is blank.

**Comment by kawapure** [comment]
Can you look in the network tab of the browser debugger (Ctrl+Shift+I or F12)? When you click the button to open this popup, it should send a request. I think that it may be blank specifically if this request fails.

**Comment by kawapure** [comment]
This issue has been marked as inactive, and will be closed in 3 days if no follow up is provided.
