### ISSUE TITLE
"Save changes" button still greyed out when configuring Rehike

### ISSUE THREAD

**Issue by anonymous11111111111111** [Rehike/Rehike#571]
### Rehike version

0.8.1

### Operating system

Windows 10 build 19045 x64

### PHP version

8.2.12

### What's going on?

When i installed the new version of Rehike. Everytime i try to change any setting in the configuration page. The "Save changes" button is still greyed out.

https://github.com/Rehike/Rehike/assets/107899240/e1429ad1-2f3d-475a-bee9-9e422efb6de3

**Comment by kawapure** [comment]
I already fixed this locally, but I thought it was a side effect of other local changes. I'll just go ahead and check in my tiny local changes.
