### ISSUE TITLE
Multiple Loop Options on 2014 YouTube Player

### ISSUE THREAD

**Issue by Xammand** [Rehike/Rehike#575]
### Rehike version

0.8.1

### Operating system

Windows 10 Home 22H2

### PHP version

8.2.4

### What's going on?

If you are on a playlist, the number of loop options will be the same number as the number of videos in the playlist. For example, a playlist with 5 videos means there will be 5 loops options in the context menu. I only tested that on 2014 player.
![Screenshot_153](https://github.com/Rehike/Rehike/assets/84749558/1cf2f9bf-b348-4ad9-bfd8-47de85d24bb1)

**Comment by kawapure** [comment]
😭 

I'll look into this, but I'm more confused on how it ever even happened in the first place.
