### ISSUE TITLE
The link for a channel comment is the video's url

### ISSUE THREAD

**Issue by Xammand** [Rehike/Rehike#576]
### Rehike version

0.8.1

### Operating system

Windows 10 Home 22H2

### PHP version

8.2.4

### What's going on?

If you try to click the channel name or picture on a comment, it always sends you to the same page you are already on (the video) due to the link being the video url.

Clicking on a reply channel link (@whateverchannelname) takes you to the channel like normal.

**Comment by Xammand** [comment]
Just to add, I heard about an update on Rehike that is supposed to make the comment channel names be the actual name instead of the @ symbol name but it still is the @ symbol name for me.

**Comment by kawapure** [comment]
> Just to add, I heard about an update on Rehike that is supposed to make the comment channel names be the actual name instead of the @ symbol name but it still is the @ symbol name for me.

It's probably a simple fix, but we haven't looked into it yet.

**Comment by kawapure** [comment]
Hm, wait. I had this experiment a few days ago, but I don't have it anymore at all.

**Comment by VORAPIS** [comment]
this is because innertubeCommand of commentViewModel author changed to profile card info, but you can recreate original command browseEndpoint by using property channelId of author object
