### ISSUE TITLE
LGBT logo

### ISSUE THREAD

**Issue by Zeytetoon** [Rehike/Rehike#578]
### Describe the feature

![Screenshot_86](https://github.com/Rehike/Rehike/assets/95986344/ce8293cf-c71f-413d-bc21-a8c175022f9f)
Google translate:

hi, I have a question. Who came up with the idea to replace the YouTube logo with LGBT? As a person who does not support this movement, I don’t want to see this logo even on the old logo. why can't this be turned off? Are you creators even fucking?

**Comment by kawapure** [comment]
lmao of course you're russian

If you don't "support this [LGBT] movement", then you're free to not use Rehike. Every one of the developers who have worked hard to bring it to you are members of the LGBT community. We feel that this is appropriate to signal during pride month to those in our userbase who hate us. We don't want people like that using our products or asking for our support.

You can simply stop using Rehike or wait until July, where the logo will be automatically reverted.

**Comment by VORAPIS** [comment]
L homophobes

**Comment by YukisCoffee** [comment]
> Are you creators even fucking?

ye
