### ISSUE TITLE
Can Rehike support extensions?

### ISSUE THREAD

**Issue by coffeemccoffee** [Rehike/Rehike#58]
Can Rehike support extensions that are affecting the main layout? like YouTube Downloaders, or for example "Enhancer for YouTube"?
![image](https://user-images.githubusercontent.com/104205144/183259964-69fc4e4e-d6fd-4815-b8c7-7fdb3db3b011.png)
![image](https://user-images.githubusercontent.com/104205144/183260000-0fcd7e40-361e-41c4-8dd9-2662308e2fba.png)

**Comment by aubymori** [comment]
Rehike only supports extensions that modify Hitchhiker. If you're lucky, some of these extends may leave Hitchhiker code in-tact, however, we do not plan on adding support for any extensions that only work on Polymer. However, I'm not saying that this won't happen in the future.
