### ISSUE TITLE
Black Video Player

### ISSUE THREAD

**Issue by dogemanttv** [Rehike/Rehike#586]
### Rehike version

0.8.1

### Operating system

Windows 10 Service Pack 1 build 19044 x64 (21H2)

### PHP version

8.0.3.0 (XAMPP)

### What's going on?

1. go to youtube.com
2. click on video
3. video doesn't load at all not even the player
![image](https://github.com/Rehike/Rehike/assets/80775876/06491e33-eaec-4d7c-881c-9010b1296cc8)

The video player worked fine yesterday, but for some reason not today? Maybe YouTube broke something with video loading??
Also the same thing happens in a private window and a different browser (chromium) with no extensions.

**Comment by kawapure** [comment]
Are you using classic player or latest player?

**Comment by kawapure** [comment]
I can replicate the same error on classic players, but latest player works fine.

Looks like YouTube changed how the video decryption function is stored. This should be fixed shortly, but as of right now we're waiting on a classic player expert to consult.

**Comment by dogemanttv** [comment]
alright cool i'm using the 2015 Modern UI, old icons player but if i switch to latest it works
thanks ;)

**Comment by TorutheRedFox** [comment]
> I can replicate the same error on classic players, but latest player works fine.
> 
> Looks like YouTube changed how the video decryption function is stored. This should be fixed shortly, but as of right now we're waiting on a classic player expert to consult.

pretty sure the decryption function parsing was done by reprety

**Comment by kawapure** [comment]
> > I can replicate the same error on classic players, but latest player works fine.
> > Looks like YouTube changed how the video decryption function is stored. This should be fixed shortly, but as of right now we're waiting on a classic player expert to consult.
> 
> pretty sure the decryption function parsing was done by reprety

Yes, I already fixed this :3

I'm writing the commit right now.

**Comment by kawapure** [comment]
Should be fixed now. Please test with the classic player as you were before this issue started occurring.

**Comment by dogemanttv** [comment]
it works!
thank you so much <3
