### ISSUE TITLE
Video player won't load, multiple errors in console regarding yt_www and decoding

### ISSUE THREAD

**Issue by nulcow** [Rehike/Rehike#587]
### Rehike version

0.8.1

### Operating system

macOS 14.3.1 build 23D60 (arm64) (Rehike identifies it as x86_64, although this is incorrect)

### PHP version

8.2.4

### What's going on?

I'm currently trying to view a YouTube video through Rehike on Firefox 128.0. I configured everything according to the instructions on the wiki, but the YouTube player will not load, even though it worked perfectly fine on Vivaldi (my previous browser). This is the information I could find in the developer console:

```
performance.now precision has been modified for compatibility reasons. See https://bugzilla.mozilla.org/show_bug.cgi?id=1756970 for details. [bug1842437-www.youtube.com-performance-now-precision.js:18:9](moz-extension://f3791386-a005-417a-a54d-51ddaa7bc5f9/injections/js/bug1842437-www.youtube.com-performance-now-precision.js)
undefined [watch:10:13](https://www.youtube.com/watch?v=yPfagLeUa7k)
Uncaught ReferenceError: _yt_www is not defined
    <anonymous> https://www.youtube.com/watch?v=yPfagLeUa7k:1699
    <anonymous> https://www.youtube.com/watch?v=yPfagLeUa7k:1711
    <anonymous> https://www.youtube.com/watch?v=yPfagLeUa7k:1720
[watch:1699:12](https://www.youtube.com/watch?v=yPfagLeUa7k)
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[blank](about:blank)
initializing selectors [ryd.content-script.js:843:11](moz-extension://48162966-c653-42d4-993e-af95a10ad40e/ryd.content-script.js)
Object { buttons: {…}, dislikeTextContainer: (4) […], likeTextContainer: (4) […], menuContainer: (1) […], roundedDesign: (2) […] }
[ryd.content-script.js:853:11](moz-extension://48162966-c653-42d4-993e-af95a10ad40e/ryd.content-script.js)
Some cookies are misusing the recommended “SameSite“ attribute 11
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. [www-base-rehike.js:390:342](https://www.youtube.com/rehike/static/js/www-base-rehike.js)
MouseEvent.mozInputSource is deprecated. Use PointerEvent.pointerType instead. [www-base-rehike.js:390:342](https://www.youtube.com/rehike/static/js/www-base-rehike.js)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at data:text/plain;base64,Cg==. (Reason: CORS request not http).

[Rehike.NDecode]Failed to extract decode expression. [watch:2273:17](https://www.youtube.com/watch?v=yPfagLeUa7k)
Uncaught (in promise) TypeError: fnDecodeN is not a function
    streamUrlVisitor https://www.youtube.com/watch?v=yPfagLeUa7k:2538
    buildPlayer https://www.youtube.com/watch?v=yPfagLeUa7k:4380
[watch:2538:45](https://www.youtube.com/watch?v=yPfagLeUa7k)
Source map error: Error: URL constructor:  is not a valid URL.
Resource URL: about:blank
Source Map URL:
```
As you can see, there are numerous errors relating to decoding JSON and the yt_www API (both of which the player is dependent on, if I'm not mistaken). Is there any way to fix this?

**Comment by kawapure** [comment]
Try using latest player. If you have any success, then please send the script link for that specific player JS, which you can find by searching base.js in inspect element.

**Comment by nulcow** [comment]
> Try using latest player. If you have any success, then please send the script link for that specific player JS, which you can find by searching base.js in inspect element.

I set the player style to "latest", which seems to work. 2022 and 2020 sort of work, but I can't get the actual video to load when using either of those styles. The other ones don't load at all.
Which player do you want me to send the JS for btw?

**Comment by kawapure** [comment]
Use the latest player and link the script for it. In order to support older players, we have to extract certain algorithms relating to video stream decryption from the latest JS URL because it updates constantly. That's what the Rehike.NDecode log is about.

**Comment by nulcow** [comment]
I think the link is https://www.youtube.com/s/player/9ed4a7e1/player_ias.vflset/en_US/base.js

**Comment by kawapure** [comment]
This player JS does work for me in the latest commit 5224e369e569c1e6b33794cbe73e9b05b8a14aa6. Please try updating Rehike.

I heard reports that the update checker on [/rehike/version](//www.youtube.com/rehike/version) stopped working for some reason, so if you have issues there, please try manually updating via the Git CLI.

**Comment by nulcow** [comment]
> This player JS does work for me in the latest commit [5224e36](https://github.com/Rehike/Rehike/commit/5224e369e569c1e6b33794cbe73e9b05b8a14aa6). Please try updating Rehike.
> 
> I heard reports that the update checker on [/rehike/version](//www.youtube.com/rehike/version) stopped working for some reason, so if you have issues there, please try manually updating via the Git CLI.

I forgot to say this, but I ran `git pull` just a few minutes before submitting this issue. It should be fully up to date. I'm using the Master branch.

**Comment by kawapure** [comment]
Could you check the version page linked above? What version are you using?

**Comment by kawapure** [comment]
![image](https://github.com/Rehike/Rehike/assets/165211464/bd8252c6-5ac4-4460-9756-38f5049f7e6c)

For the record, on the latest, you should have invalid information because of some commit name parsing bug that we have yet to address.

**Comment by kawapure** [comment]
> > Could you check the version page linked above? What version are you using?
> 
> It says "Version 0.8.1 (build 1441, 2024-04-23)". Apparently it's also the "nightly" version, but I don't know what that's supposed to mean in this context, since I'm just using the regular master branch.

Oh damn, that's real far from the latest version. Try `git fetch && git checkout -B master origin/master` to force an update to the latest commit.

Nightly is there on all versions, don't worry about that.

**Comment by nulcow** [comment]
> Oh damn, that's real far from the latest version. Try `git fetch && git checkout -B master origin/master` to force an update to the latest commit.

I ran that command and got the following output:
```
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.
```

**Comment by kawapure** [comment]
Check the version page now. It should be a little buggy like mine is. If it is, then the classic players should work again.

**Comment by nulcow** [comment]
> Check the version page now. It should be a little buggy like mine is. If it is, then the classic players should work again.

It's complaining about "dubious ownership" in the repository. I tried what it suggested but that didn't do anything. Also, I just now realised that the real location of htdocs is /Applications/XAMPP/xamppfiles/htdocs, not /Applications/XAMPP/htdocs like I thought it was. I might try re-installing Rehike to the proper location and see if anything changes.

**Comment by kawapure** [comment]
You can ignore the dubious ownership thing. Just copy/paste the code to add an exception that the Git CLI shows.

But yeah, that'll do it lol. Make sure you're actually changing the active installation directory.

**Comment by nulcow** [comment]
I ended up breaking my XAMPP installation, so I had to reinstall and reconfigure it, but after following the installation instructions, the 2015 player is now working. I'll have to open a separate issue regarding the playback errors on the 2020 player, and the need to pause and unpause the video before it will play properly on the 2015 player.

**Comment by kawapure** [comment]
> and the need to pause and unpause the video before it will play properly on the 2015 player.

This is because Firefox blocks autoplay. You can enable that manually: https://support.mozilla.org/en-US/kb/block-autoplay
