### ISSUE TITLE
"g is not defined" on older players

### ISSUE THREAD

**Issue by not-nullptr** [Rehike/Rehike#597]
### Rehike version

0.8.2

### Operating system

Windows 10 22H2

### PHP version

8.2.12

### What's going on?

when trying to use the 2014 and 2015 (classic) players, there is just a black screen where the player should be. in the console, an error, "g is not defined", is visible.

**Comment by kawapure** [comment]
Classic players are broken anyway because of #593.

**Comment by kawapure** [comment]
I ended up commiting a fix I was working on for this particular issue in 8dc3444. Video playback will still not work as a side effect of the aforementioned issue.
