### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by micxdev** [Rehike/Rehike#598]
![image](https://github.com/user-attachments/assets/a2e8dfc4-625d-4dde-974c-c21ae855e2df)

I attempted to install on my MacOS 10.13.6 2011 iMac and got this error shown above.

**Comment by kawapure** [comment]
Try `chmod -R 777`ing the whole installation folder.

**Comment by kawapure** [comment]
The presentation of this error is fixed in 03c6663.

**Comment by micxdev** [comment]
> chmod -R 777

That didn't work for me either so after a long while I just resorted to right clicking the htdocs folder in Finder and changing permissions that way. Much easier anyway.

**Comment by kawapure** [comment]
Alright, glad to hear you managed to resolve it.
