### ISSUE TITLE
WEB v1 w2w (home) API going down

### ISSUE THREAD

**Issue by Nightlinbit** [Rehike/Rehike#6]
Rehike uses requests `youtubei/v1/browse` with browseId "FEwhat_to_watch" for the home page, as does regular YouTube. In order to get the old homepage, it uses the client name `WEB` and version `1.0`. This is the very client configuration that the real old YouTube layout was believed to use. However, as of the past month (April 2022), many people across related Discord servers have reported irregularities in being able to access it.

It seems that many people, typically those who access the site logged in, have an issue with this API failing to return.

As it stands, implementation of an alternative seems important.

**Comment by pixdoet** [comment]
Would using ANDROID shelves be a sufficient replacement for this? From what I've played with on ANDROID responses they seem to be easily replacable for WEB client

**Comment by sydia1103** [comment]
It seems this API is down at least on the homepage. It returns 400 on Rehike.

**Comment by YukisCoffee** [comment]
Partially resolved by ac7a50428fd13c5b467283ba248b300ad9ee5c8a.

There are still issues with the ANDROID API: it cannot display badges, and continuations are currently broken.

**Comment by sydia1103** [comment]
> Partially resolved by [ac7a504](https://github.com/Rehike/Rehike/commit/ac7a50428fd13c5b467283ba248b300ad9ee5c8a).
> 
> There are still issues with the ANDROID API: it cannot display badges, and continuations are currently broken.

Yes, the homepage now works again, but as you mentioned continuations are currently broken on the homepage because clicking load more gives an 500 internal error. Either way, it definitely is nice to have the homepage back.

**Comment by sydia1103** [comment]
It seems this is fully fixed by [``](https://github.com/Rehike/Rehike/commit/da86b8dbc7b0a721dbd2ab82b94b8d285abb1043)
