### ISSUE TITLE
You can't "Add To" while still signed in.

### ISSUE THREAD

**Issue by coffeemccoffee** [Rehike/Rehike#61]
You can't "Add To" while still signed in.
![image](https://user-images.githubusercontent.com/104205144/183261881-3a9a59d9-6138-49b4-96b3-8a5e5e57e525.png)

**Comment by aubymori** [comment]
There are no archives of addto_ajax and no recreations I can find, so in its current state, I cannot do this. I might pester Taniko to make a recreation, but as it stands, this is not possible at the moment.

**Comment by YukisCoffee** [comment]
Fixed by 0695ed4db9142396d9d90a3feb872d9943c511b6.

Closing...
