### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by SailingTheMoon** [Rehike/Rehike#610]
EDIT: disabling cookies for youtube.com will make the site load on waterfox, but i am unable to sign in like this and the watch page becomes one giant embed.

TypeError: Rehike\ContextManager::setVisitorData(): Argument #1 ($visitor) must be of type string, null given, called in C:\xampp\htdocs\modules\Rehike\Boot\Tasks.php on line 164
  at Rehike\ContextManager::setVisitorData(null)(rehike://modules/Rehike/ContextManager.php:42)
  at Rehike\Boot\Tasks::setupVisitorData()(rehike://modules/Rehike/Boot/Tasks.php:164)
  at Rehike\Boot\Bootloader::runSetupTasks()(rehike://modules/Rehike/Boot/Bootloader.php:199)
  at Rehike\Boot\Bootloader::boot()(rehike://modules/Rehike/Boot/Bootloader.php:114)
  at Rehike\Boot\Bootloader::startSession()(rehike://modules/Rehike/Boot/Bootloader.php:26)
  at {main}(rehike://index.php:73)

This issue keeps occuring for me and I can't access youtube. I have tried using a dfferent browser, brave, and in that case the page loads but the player gives a playback error and no video is displayed. This is on the latest version and latest player. Note that both these issues occur on Waterfox and brave respectively even if I attempt to disable rehike.

Log:
[20240920220008-home.txt](https://github.com/user-attachments/files/17080341/20240920220008-home.txt)

Waterfox 115 / Firefox 130 / Brave 1.70.117

**Comment by YukisCoffee** [comment]
That seems odd... Could you edit index.php to contain:

```php
<?php
$cookies = $_COOKIE;

unset($cookies["LOGIN_DATA"]);
unset($cookies["SAPISID"]);
unset($cookies["__Secure-1PAPISID"]);
unset($cookies["__Secure-1PSIDCC"]);
unset($cookies["__Secure-1PSIDTS"]);
unset($cookies["__Secure-1PSID"]);
unset($cookies["__Secure-3PAPISID"]);
unset($cookies["__Secure-3PSIDCC"]);
unset($cookies["__Secure-3PSIDTS"]);
unset($cookies["__Secure-3PSID"]);
unset($cookies["APISID"]);
unset($cookies["SIDCC"]);
unset($cookies["SID"]);
unset($cookies["SSID"]);
unset($cookies["HSID"]);

var_dump($cookies);
```

This code will dump the cookies which Rehike can read, while redacting your personal account tokens.

After you're done, send us the dump so we can investigate.

**Comment by SailingTheMoon** [comment]
When adding the lines to index.php, i get the following result upon opening the page. is there still a dump? if so, where would I find it?

![image](https://github.com/user-attachments/assets/7a256593-f318-441f-a2fc-ce43c23be7e6)

**Comment by YukisCoffee** [comment]
Don't add lines, replace the contents of the file.

**Comment by SailingTheMoon** [comment]
here it is:

array(8) { ["PREF"]=> string(26) "f5=30030&f4=4000000&tz=UTC" ["__Secure-YEC"]=> string(44) "Cgt6VFFHcVBwcm53MCi08be3BjIKCgJVUxIEGgAgEg==" ["VISITOR_PRIVACY_METADATA"]=> string(16) "CgJVUxIEGgAgEg==" ["LOGIN_INFO"]=> string(407) "AFmmF2swRQIhAM3-DjJRMbHpVomJpxYFsRYMAEcERlFMm4pOJf0LTnrjAiApy68sKWYNUVof3x7iMe6p7H6ih4RZK0HqIRbqWwpvdA:QUQ3MjNmeURjVWZBOWkxbXltWjRiWmhvT21EVDBLUHpKMEpnTG9kNDJFUWwtbXdMcDJ1OTZEdXA4elZGdHdubFR5NDk1a2k1dFkya1EyYlNqZWNBeW9SenZVOE1kVm9sZ1B1bGtuajhPd1QzOTg2b21kYW1mdk5UQnV4T3JsbFpuREt3eGxvazFITnpCajZlakQzLWFBaDQ5Y1R3R1BRVjI5UHpUZUxsZW1pcWlid2NBWW9xVk13SXlzUEtZT05JX1ZmLURQT04wOHhEYXBPWEhDbFVXSDZWSjlqNnJvRnFPUQ==" ["VISITOR_INFO1_LIVE"]=> string(11) "wEPBcibjGy0" ["CONSENT"]=> string(11) "PENDING+742" ["SOCS"]=> string(87) "CAESNQgDEitib3FfaWRlbnRpdHlmcm9udGVuZHVpc2VydmVyXzIwMjMwOTEyLjA4X3AwGgJlbiACGgYIgOCTqAY" ["YSC"]=> string(11) "BUCtIbe-WhE" }

**Comment by YukisCoffee** [comment]
Your browser isn't sending an invalid value for VISITOR_INFO1_LIVE, so I don't see what the problem is.

Please try loading a page normally again. It may have just been a temporary problem.

**Comment by YukisCoffee** [comment]
In any case, I went ahead and added some type safety checks into the offending file. 7a1fea5 should solve your issues. Reopen if it's still a problem.
