### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#612]
So I just randomly got this error for no reason when trying to open the youtube homepage (same issue happens for any other page), this had never happened until now and I tried clearing cache and restarting but that still didn't fix it

[Uploading 20240926022133-home.txt…]()

**Comment by kawapure** [comment]
Oh wait. I looked in the edit history. This bug has since been fixed. Please check out the latest version and try again.

**Comment by kawapure** [comment]
It was from Niko experimenting with syntactic improvements for the network library we use.
