### ISSUE TITLE
hey how can i disable rehike

### ISSUE THREAD

**Issue by Sooub** [Rehike/Rehike#616]
### Rehike version

0.8.3

### Operating system

windows 10 22h2

### PHP version

72

### What's going on?

hey i gonna disable rehike but i don know how to disable

**Comment by kawapure** [comment]
There's a button on the crash page; otherwise, you can visit https://www.youtube.com/rehike/version and click the "Disable Rehike" button.

**Comment by TorutheRedFox** [comment]
alternatively, you can just remove the youtube-related entries from your hosts file or proxy, whichever you used to redirect youtube to rehike
