### ISSUE TITLE
how to uninstall rehike

### ISSUE THREAD

**Issue by Sooub** [Rehike/Rehike#623]
### Rehike version

0.8.3

### Operating system

windows 10 22h2

### PHP version

7.2

### What's going on?

how do I uninstall a rehike please help me I don't know how to uninstall

**Comment by YukisCoffee** [comment]
Do you know how you installed it? Do the opposite of those steps.

**Comment by Sooub** [comment]
but I forget it

**Comment by YukisCoffee** [comment]
We have documented the installation instructions. You manually repeated these steps. I'm sure you can do them in reverse, too.

**Comment by Sooub** [comment]
oh ok

**Comment by Sooub** [comment]
thx
