### ISSUE TITLE
hey i have question hey i gonna make ui like yt 2017 

### ISSUE THREAD

**Issue by Sooub** [Rehike/Rehike#624]
### Describe the feature

can someone help me how i gonna to make UI like yt 2017

**Comment by aubymori** [comment]
https://github.com/Rehike/Rehike/discussions

**Comment by Sooub** [comment]
can someone help me how to make ui like 2017

**Comment by YukisCoffee** [comment]
Seriously man, how do you keep failing to read the giant fucking text we have saying, and I quote:

> THIS FORM IS NOT FOR QUESTIONS! MAKE A NEW DISCUSSION TO ASK A QUESTION!

![image](https://github.com/user-attachments/assets/604e4103-ed3f-48a5-844f-a06debdf8877)

**Comment by YukisCoffee** [comment]
Make one more spammy issue and we're going to block you from the org dude.
