### ISSUE TITLE
Why Is No Number Dislike Show?

### ISSUE THREAD

**Issue by TrivaJa** [Rehike/Rehike#629]
### Rehike version

0.8.3

### Operating system

Windows 10 build 19045 x64

### PHP version

8.2.12

### What's going on?

Here Story:
When I Going Watch Anime Moment is fine but the next 6 minutes
I watched another clip video but no number dislike show here proof:
![Screenshot (2)](https://github.com/user-attachments/assets/89ef74d4-dcc6-4ccc-a1f2-9f68bc9b82fe)

**Comment by kawapure** [comment]
This is not an issue. Either: 

- The Return YouTube Dislike service was unavailable for you at the time of the request.
- You have Return YouTube Dislike integration disabled in your settings.
