### ISSUE TITLE
Home page recommended video section is blank

### ISSUE THREAD

**Issue by i-lost-my-bagel** [Rehike/Rehike#631]
### Rehike version

0.8.3

### Operating system

Debian Linux

### PHP version

8.2.24

### What's going on?

My home page recommendation page is blank. Trending and subscriptions tabs along with all other pages work just fine.

![image](https://github.com/user-attachments/assets/35c102e6-5249-4c6a-b540-81f95602b30b)

**Comment by kawapure** [comment]
Should be fixed in https://github.com/Rehike/Rehike/commit/a485353def88cae6a1e74b9075628577f66aedc4

**Comment by i-lost-my-bagel** [comment]
yay it works now!!
