### ISSUE TITLE
Nothing showing up on the homepage

### ISSUE THREAD

**Issue by AndyGaming129** [Rehike/Rehike#633]
### Rehike version

0.8.3

### Operating system

Windows 10 build 19045 x64

### PHP version

PHP 8.2.12

### What's going on?

The videos and the config works, but the thing is when I open up YouTube, the homepage theres no videos. Is there a way to fix this but except when I use 127.0.0.1 it works but none of the videos load
![image](https://github.com/user-attachments/assets/d7cd68dc-a423-41d3-8100-81c875b5827d)

**Comment by kawapure** [comment]
Please update to the latest version of Rehike.

**Comment by AndyGaming129** [comment]
> Please update to the latest version of Rehike.

How do I update Rehike?

**Comment by kawapure** [comment]
If you go to https://www.youtube.com/rehike/version, under the nightly info, there should be an option to update.

**Comment by AndyGaming129** [comment]
Ok ty its working now
