### ISSUE TITLE
after my pc files windows missing and reinsrtall windows i had to reinstall rehike and it happen

### ISSUE THREAD

**Issue by Sooub** [Rehike/Rehike#634]
### Rehike version

0.8.3

### Operating system

windows 10

### PHP version

8.2.12

### What's going on?

i have to reinstall rehike doing some manual on github and 
![Screenshot (1)](https://github.com/user-attachments/assets/7818dd99-7bd2-49a1-98ee-b9ba1f0b79c4)
this

**Comment by kawapure** [comment]
Try clearing your cookies.

**Comment by Sooub** [comment]
oh ok
