### ISSUE TITLE
Rehike error: Failed to find decryption algorithm. For old layouts except new layouts.

### ISSUE THREAD

**Issue by VitoItalianGamer** [Rehike/Rehike#642]
### Rehike version

0.8.3

### Operating system

Windows NT 10.0 Build 19045 (Windows 10)

### PHP version

8.2.12

### What's going on?

On old layouts of the video player, it gives me an error. The latest video player is not affected.
![Screenshot (21)](https://github.com/user-attachments/assets/24c88b4e-c90f-4bcb-8865-da1098cf0b2c)

**Comment by kawapure** [comment]
Duplicate of https://github.com/Rehike/Rehike/issues/601
