### ISSUE TITLE
Rehike stopped working since 24/11

### ISSUE THREAD

**Issue by LucasHood1234** [Rehike/Rehike#645]
### Rehike version

0.8.3

### Operating system

Windows 7 32-bit

### PHP version

8.1.13

### What's going on?

Not sure if everyone has experienced this issue, but it is better to post it here. Like the title suggests, my Rehike has stopped working since 24/11, after I opened xampp and fiddler, I opened Youtube and it displayed a screen saying "No internet." I tried to reload the page multiple times but no avail. Hope this issue will be fixed soon because I really love using Rehike and want to continue using it for as long as I could.

**Comment by kawapure** [comment]
Rehike continues to work for me, so this is possibly an issue with your local configuration. Ensure that the hosts file entry is set.

**Comment by LucasHood1234** [comment]
![Untitled256](https://github.com/user-attachments/assets/71b09ed9-dc50-4e4f-92bf-d190d71bf177)

My Fiddler is like this, is this normal?

**Comment by kawapure** [comment]
Ah, then it's most likely a Fiddler problem. Have you tried the host file method at all?

**Comment by LucasHood1234** [comment]
No I haven't, I usually use Fiddler and Xampp.

**Comment by LucasHood1234** [comment]
![Untitled256](https://github.com/user-attachments/assets/986e68aa-ccd3-4fb3-a259-33a096439a14)

So this is what I got when I press CTRL + F5.

**Comment by kawapure** [comment]
The Fiddler certificate expired.

**Comment by kawapure** [comment]
User error; resolved on IM.
