### ISSUE TITLE
Rehike error when using older players

### ISSUE THREAD

**Issue by Chipert9234** [Rehike/Rehike#651]
### Rehike version

0.8.3

### Operating system

Windows 11 24H2

### PHP version

8.2.12

### What's going on?

When I change the player to a older one it displays this error
![Screenshot 2024-12-16 194615](https://github.com/user-attachments/assets/56aefe1c-9520-4253-8a9a-f9312e929932)
Can you fix this?

**Comment by kawapure** [comment]
Duplicate of https://github.com/Rehike/Rehike/issues/601
