### ISSUE TITLE
Account picker shows other channels under your account when it's supposed to show other accounts

### ISSUE THREAD

**Issue by syndiate** [Rehike/Rehike#66]

**Comment by YukisCoffee** [comment]
It's supposed to show both, but the style selection is messed up at the moment.

**Comment by YukisCoffee** [comment]
Style fixed by 5b9aeff1b697a6b7cfa078b831d24888127d8204.

Still does not show multiple Google accounts' channels. The signin API has to be restructured to account for that.

**Comment by kawapure** [comment]
This commit is overshadowed by #591, so I will close it as it will be resolved as part of it.
