### ISSUE TITLE
You can't Report videos while signed in

### ISSUE THREAD

**Issue by coffeemccoffee** [Rehike/Rehike#67]
![image](https://user-images.githubusercontent.com/104205144/183361120-e2e9f98d-6bdc-4667-afc7-b1cca5937af7.png)
In Rehike, You can't report videos, even when signed in.

**Comment by ephemeralViolette** [comment]
We probably won't ever get around to adding this; reporting videos is a rare action to perform, and this feature request has not been considered even once after being asked. I will consider this similarly to Creator Studio.
