### ISSUE TITLE
Add To missing

### ISSUE THREAD

**Issue by ineedseriousmentalhelp** [Rehike/Rehike#69]
![Gif example](https://user-images.githubusercontent.com/109477049/183460422-6a898a6c-eb8a-4388-80b5-fd1c2f322bff.gif)

**Comment by coffeemccoffee** [comment]
That's probably just css that does affect it

**Comment by syndiate** [comment]
You most likely have a script or style that's affecting this. I went to the video myself and the Add to button is there, soo

**Comment by ineedseriousmentalhelp** [comment]
i dont have a script or style on though

**Comment by YukisCoffee** [comment]
No, this is a known bug. I've had it happen to me as well.

It's difficult to replicate and fixes itself after a refresh typically. Assuming some innertube variance...

**Comment by YukisCoffee** [comment]
Should be completely fixed by 1242c47d62b9b988bbec5af9c6dccb7ebcbe8802, which hardcodes the buttons.

Closing...
