### ISSUE TITLE
"Date Added - Newest / Oldest" and "Most Popular" dosen't even work

### ISSUE THREAD

**Issue by coffeemccoffee** [Rehike/Rehike#70]
I can't look on older videos or newer ones or the most popular ones, because these options won't work.
![image](https://user-images.githubusercontent.com/104205144/183487155-79db6425-e209-40a9-af39-22a2e37ee3d4.png)

**Comment by aubymori** [comment]
Fixed by 71748e26539c49c9557556995a23dda2ee634250.

Closing...
