### ISSUE TITLE
Fails To Obtain Country

### ISSUE THREAD

**Issue by jtakatsuki** [Rehike/Rehike#71]
Good morning.

I notice a bug in Rehike, which is it does not show the right country. It thinks I am from US, so I get US recommendations.

Related issue: #12

![image](https://user-images.githubusercontent.com/110828020/183523036-5b39fe1b-6512-443a-9e7a-617c245d841c.png)

![image](https://user-images.githubusercontent.com/110828020/183523174-8d768176-28e1-45e6-a612-1be0b0344ed7.png)

**Comment by aubymori** [comment]
Will most likely be implemented with i18n. No ETA.

**Comment by aubymori** [comment]
The only way at the moment would be to change `US` to whatever your ISO 3166 country code is on line 115 of `modules/Rehike/InnerTubeContext.php`, which isn't recommended. I might look into letting the user change their language and country soon.

**Comment by ephemeralViolette** [comment]
Now possible with manual configuration file modification as of b58958217c62de9e04e5cad7d8596848932f79db.

**Comment by Felting** [comment]
Close this issue

**Comment by kawapure** [comment]
Finished in 8dc3444.
