### ISSUE TITLE
Subscribe button shows as Channel settings when signed out

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#74]
When I'm signed out, the Subscribe button next to a channel's name says Channel settings for some reason even though it's only supposed to show that when I'm signed in and on my own channel.
![Channel settings bug](https://user-images.githubusercontent.com/32617562/183876730-9b8e719e-cb5e-431e-90ca-e253b39d37fc.png)

**Comment by YukisCoffee** [comment]
Moved to megathread #75. Closing...
