### ISSUE TITLE
[all branches] Subscriptions megathread

### ISSUE THREAD

**Issue by YukisCoffee** [Rehike/Rehike#75]
## The what

A megathread for tracking **subscription** implementation progress. This should be progressively updated throughout **subscriptions** development and **closed only when the feature is completely stable**.

## The why

Many issues have been created separately regarding individual aspects of the subscriptions buttons. For the sake of developmental organisation, I decided it would be better to coalesce all of these into one megathread.

## The guidelines

Please do not make submit separate issues regarding issues, unless they are only secondarily related to the feature (i.e. button renders wrong on one specific page).

Instead, please post a comment under this issue to point out a specific bug or recommendation.

Under submission, please indicate the branch and provide any other necessary details in order to replicate the bug. If any error log is produced, please include it in your submission (enclosed with \`\`\` on both ends for formatting).

## The progress

- [x] Correct signed out "Channel settings" placeholder bug #74 
- [x] Working `subscription_ajax`
- [ ] Implement notification preferences
- [x] i18n support
- [x] Subscriptions feed

**Comment by aubymori** [comment]
coffee has noted that the subscription endpoints used for subscriptions_ajax are protected by google's botguard so that's the issue with it

**Comment by aubymori** [comment]
> coffee has noted that the subscription endpoints used for subscriptions_ajax are protected by google's botguard so that's the issue with it

no they dont dumbass bitch

**Comment by aubymori** [comment]
subscription preferences is like somewhat done but it doesn't work fully

**Comment by aubymori** [comment]
This has been open and pinned for way too long, with only one thing being left unchecked. Splitting into single issue #260.
