### ISSUE TITLE
Clicking a channel name on WEB v1 homepage doesn't take me to the channel

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#77]
So on the WEB v1 homepage you can see videos in those tray menus, underneath each video there's the channel name you can click that's supposed to link you to the channel however it just takes me back to the homepage technically refreshing the page. This issue never happens on WEB v2 homepage however.

**Comment by aubymori** [comment]
this is an issue with the ANDROID response format, will most likely be fixed when moving to web v2 shelves home

**Comment by YukisCoffee** [comment]
> will most likely be fixed when moving to web v2 shelves home

Is fixed now! 110c58c961b4106f9671d1ad2163d500d9946ce7

Closing...
