### ISSUE TITLE
Comments don't load when signed out

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#78]
Whenever I'm signed out and scroll down to the comments, they never load for some reason

**Comment by aubymori** [comment]
this is because you're loading rehike on localhost, which is not the intended way to use rehike

**Comment by randomperson189** [comment]
I'm not loading it on localhost, I'm using charles and comments load fine when I'm signed in so I don't think this is invalid

**Comment by aubymori** [comment]
i can't replicate this

**Comment by randomperson189** [comment]
Let's see if YukisCoffee and others can replicate it since I've tried different browsers, even on my second pc and the issue still occurs

**Comment by randomperson189** [comment]
So I saw a recent update that fixes it so yeah it was an issue afterall lol
