### ISSUE TITLE
Checkmarks on the related video section do not show.

### ISSUE THREAD

**Issue by iamatsomeone** [Rehike/Rehike#8]
Minor bug, but maybe could be fixed with some innertube requests? Idk, just a small touch 🤷🏻‍♂️
![Refrence](https://i.imgur.com/YDoxHTm.png)

**Comment by YukisCoffee** [comment]
Labelled `enhancement` because this is standard behaviour of Hitchhiker.

Hitchhiker didn't ever show some additional metadata on watch recommendations, including the verification status.

However, this may be added down the line as a configuration option.

**Comment by iamatsomeone** [comment]
oh ok
