### ISSUE TITLE
Some channel urls go to page not found

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#82]
Some channel urls seem to not work properly and go to the page not found error. An example is Ray William Johnson's channel https://www.youtube.com/equalsthree

now you could go to the alternate url of the channel which is this: https://www.youtube.com/channel/UCGt7X90Au6BV8rf49BiM6Dg but when I click to go to another page on it such as videos, the url changes to https://www.youtube.com/equalsthree/videos instead which goes to the page not found error.

**Comment by YukisCoffee** [comment]
/c/ and /user/ links will work for now. But yeah, this is bug because there isn't any endpoint checking on fallbacks.

**Comment by YukisCoffee** [comment]
Fixed by ac74514d609685e9a3fb4840acc4dcf1f91f3bd2. Closing...
