### ISSUE TITLE
nice (music thing idk)

### ISSUE THREAD

**Issue by ineedseriousmentalhelp** [Rehike/Rehike#83]
![image](https://user-images.githubusercontent.com/109477049/185509849-02d51400-4108-4c47-bdd5-c6743088f5ab.png)

**Comment by YukisCoffee** [comment]
This technically isn't even a bug (it displays all the metadata InnerTube returns), but it is ugly as fuck.

I'll have to figure out a unique way to fix this.

The InnerTube devs had a fucking stroke implementing this new music "engagement" panel and the data structure is a completely unworkable mess.

**Comment by ineedseriousmentalhelp** [comment]
lmfao
