### ISSUE TITLE
[PlayerCore] Annoying Bug in Rehike (Rehike pre-init error occurred)

### ISSUE THREAD

**Issue by coffeemccoffeeeeeee** [Rehike/Rehike#84]
I use Rehike normally until this error comes up when i refresh youtube or go to a random channel/watch page
It's very annoying and every time i should reinstall rehike for it to work, sometimes it doesn't work at all, also reenabling the apache server doesn't work either.
![image](https://user-images.githubusercontent.com/111658911/185762911-b534d4fc-c7a5-45bd-9ee7-06d2ad585313.png)

**Comment by YukisCoffee** [comment]
As a PHP issue, this will most likely not be solved by reinstalling Apache or Rehike. It may be related to the cache that Rehike stores at the project root, which you can delete.

This is a peculiar issue that I will look into.

**Comment by YukisCoffee** [comment]
Should be fixed by 937f4fe25f99ebd60aa477d5dbf6c3faa420457d.

Closing, please reopen if issues persist.
