### ISSUE TITLE
Clicking Play all on a homepage shelf takes me to an error page

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#86]
Whenever I click the Play all button on a shelf that's on the homepage, it takes me to an 404 not found page. I noticed the url goes to "youtube.com/watch_videos" instead of "youtube.com/watch"

Interestingly the url works when I paste it on polymer which redirects me to the playlist url (watch?v=&list=)

**Comment by YukisCoffee** [comment]
Will be fixed shortly, but the playlist you'll get from the homepage will still have the wrong videos.

**Comment by YukisCoffee** [comment]
Well I guess this is resolved because homepage outright doesn't have this feature anymore... URL endpoint still needs to be implemented though, which we will work on.
