### ISSUE TITLE
Video descriptions sometimes don't show up 

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#87]
So recently the video descriptions sometimes don't show for some reason. It might have to do with the new watch layout that youtube polymer sometimes gives people

**Comment by YukisCoffee** [comment]
Very odd. I'll experiment and see if I can replicate this behaviour.

**Comment by YukisCoffee** [comment]
Could you please provide more details that could allow us to reproduce this bug?

**Comment by aubymori** [comment]
Old issue, not enough details. Seems related to the absolutely traumatizing description layout update, which seems to be completely gone.

Closing.
