### ISSUE TITLE
Add Simple YouTube Age Restriction Bypass

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#9]
There's this userscript that bypasses age restricted videos and also that stupid ass age verification thing
https://greasyfork.org/en/scripts/423851-simple-youtube-age-restriction-bypass

Although it doesn't seem to work when I use ReHike so I have to go back to the new polymer layout for it to work. I think adding it as an option would work best.

**Comment by YukisCoffee** [comment]
I looked into why this doesn't work. This script intercepts the Polymer global variable `ytInitialPlayerResponse`, which Rehike doesn't use.

It would be pretty complicated to implement in the PHP world. However, implementation in the JS world seems quite easy by reworking the Rehike player backend to use this variable (this might also fix proper adblocker support while we're at it).

**Comment by YukisCoffee** [comment]
Hey, I finally got around to it :3

Added in ec2e05805519d9f9d00c0498655de55dfe1404ee. Closing...
