### ISSUE TITLE
Youtube channel pages show undefined property errors

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#91]
Whenever I go onto a youtube channel page for example https://www.youtube.com/user/markipliergame these errors show up.

Warning: Undefined property: stdClass::$selected in D:\xampp\htdocs\models\Channels\Channels4Model.php on line 60

Warning: Undefined property: stdClass::$selected in D:\xampp\htdocs\models\Channels\Channels4Model.php on line 57

**Comment by YukisCoffee** [comment]
Fixed by #94.
