### ISSUE TITLE
Highlighted reply doesn't have like/dislike buttons

### ISSUE THREAD

**Issue by Objectful** [Rehike/Rehike#92]
![image](https://user-images.githubusercontent.com/73402079/188470994-e7ff1f08-6f0d-47af-b96b-ba0a8b918abf.png)

**Comment by YukisCoffee** [comment]
Fixed by d8bc0b03e840da0807d39afbd52252496ef7ee8a. Reply teasers models are now reprocessed like any other comment.

Closing...
