### ISSUE TITLE
Shouldn't the "Playback ID" error message be showing a static background like it did in Hitchhiker?

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#96]
![image](https://user-images.githubusercontent.com/107463768/189751770-745a5b6d-97c6-40fe-8e9a-782655c4beba.png)
The message above shows how it looks on Rehike. It shows the Polymer/Kelvar error. It should be showing a static background with text, as shown below:
![image](https://user-images.githubusercontent.com/107463768/189752094-755da8b3-2486-464d-af80-f48b557240ef.png)

**Comment by YukisCoffee** [comment]
This is a player-level change. Rehike currently does not change the player.

Dismissing...
