### ISSUE TITLE
Rehike doesn't react well to no internet (fatal error)

### ISSUE THREAD

**Issue by AshtyBoi** [Rehike/Rehike#97]
![image](https://user-images.githubusercontent.com/107463768/189752877-23310005-7772-4d6b-826b-14e458a1323e.png)
So, Polymer/Kelvar shows a "No internet" error when you're not connected to the Internet. But, for Rehike, it shows the notorious "Fatal Error" screen with these details: 
`Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in C:\xampp\htdocs\models\Guide\Converter.php:203
Stack trace:
#0 C:\xampp\htdocs\models\Guide\Converter.php(203): count(NULL)
#1 C:\xampp\htdocs\models\Guide\Converter.php(49): Rehike\Model\Guide\Converter::getLibrarySection(NULL)
#2 C:\xampp\htdocs\models\Guide\MGuide.php(32): Rehike\Model\Guide\Converter::fromData(NULL)
#3 C:\xampp\htdocs\controllers\core\HitchhikerController.php(176): Rehike\Model\Guide\MGuide::fromData(NULL)
#4 C:\xampp\htdocs\controllers\core\NirvanaController.php(62): Rehike\Controller\core\HitchhikerController->getPageGuide()
#5 C:\xampp\htdocs\controllers\core\HitchhikerController.php(109): Rehike\Controller\core\NirvanaController->init(Object(stdClass), '')
#6 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(51): Rehike\Controller\core\HitchhikerController->get(Object(stdClass), '', Object(Rehike\ControllerV2\RequestMetadata))
#7 C:\xampp\htdocs\modules\Rehike\ControllerV2\GetControllerInstance.php(73): Rehike\ControllerV2\GetControllerInstance->_cv2WrappedCallControllerMethod('get', Array)
#8 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(210): Rehike\ControllerV2\GetControllerInstance->__call('get', Array)
#9 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(157): Rehike\ControllerV2\Router::pointerHandler('watch', 'get')
#10 C:\xampp\htdocs\modules\Rehike\ControllerV2\Router.php(25): Rehike\ControllerV2\Router::baseRequestMethod(Array, 'get')
#11 C:\xampp\htdocs\router.php(35): Rehike\ControllerV2\Router::get(Array)
#12 C:\xampp\htdocs\index.php(44): require('C:\\xampp\\htdocs...')
#13 {main}
  thrown`

**Comment by aubymori** [comment]
literally not worth the effort

the fuck did you expect to happen when you plugged out your internet and go to a site?
