### ISSUE TITLE
The videos page on certain channels show errors

### ISSUE THREAD

**Issue by randomperson189** [Rehike/Rehike#98]
When I go to the videos page on certain channels such as https://www.youtube.com/c/Yourfavoritemartian/videos they display these errors:

**Warning: Undefined property: stdClass::$sortSetting in D:\xampp\htdocs\models\Channels\Channels4\BrandedPageV2\MSubnav.php on line 29**

**Warning: Attempt to read property "sortFilterSubMenuRenderer" on null in D:\xampp\htdocs\models\Channels\Channels4\BrandedPageV2\MSubnav.php on line 29**

**Warning: Attempt to read property "subMenuItems" on null in D:\xampp\htdocs\models\Channels\Channels4\BrandedPageV2\MSubnav.php on line 33**

**Warning: foreach() argument must be of type array|object, null given in D:\xampp\htdocs\models\Channels\Channels4\BrandedPageV2\MSubnav.php on line 33**

**Comment by YukisCoffee** [comment]
Music channels lack the ability to sort the videos page... for some reason.

Will fix, thanks for the notice!

**Comment by YukisCoffee** [comment]
Fixed by d4effd8c0b8c3c6c925d1bf031feb2d47a9cca4e. The option to sort is currently unavailable for this type of channel, will further research methods to restore it.

Closing...
